In [1]:
!pip -q install gspread gspread-dataframe google-auth

In [2]:
# =======================
# Config & imports (portable: Colab / GitHub / local)
# =======================
import io, threading, requests, pandas as pd, os, time, random
from concurrent.futures import ThreadPoolExecutor, as_completed
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
from IPython.display import display

# ---- Secrets: Colab (userdata) o ENV ----
def _get_secret(name: str) -> str | None:
    try:
        from google.colab import userdata as _ud  # solo existe en Colab
        val = _ud.get(name)
        if val:
            return val
    except Exception:
        pass
    return os.environ.get(name)

USER_API   = _get_secret("USER_API")
SECRET_API = _get_secret("SECRET_API")
if not USER_API or not SECRET_API:
    raise ValueError(
        "Falta USER_API o SECRET_API. En Colab: agrega en 'Secretos'. "
        "En GitHub/local: define variables/Secrets de entorno."
    )

# =======================
# Parámetros "amables"
# =======================
BASE_URL   = "https://mutatio-api.gobravo.dev"
MAX_PAGES  = 2000

# Concurrencia general (facturaciones/reparadoras)
WINDOW_GENERAL      = 6      # tamaño de lote paralelo
MAX_WORKERS_GENERAL = 3      # hilos para paralelizar

# Concurrencia específica para collections (MUY grande)
WINDOW_COLLECTIONS      = 1  # totalmente secuencial
MAX_WORKERS_COLLECTIONS = 1

# Rate limiting y backoff
MIN_INTERVAL_S   = 0.35      # intervalo mínimo entre POST al mismo host
JITTER_S         = (0.05, 0.15)
BACKOFF_BASE_S   = 0.8
BACKOFF_CAP_S    = 8.0
MAX_RETRIES_SOFT = 4         # reintentos suaves por request (además de Retry del adapter)

ENDPOINTS = {
    "facturaciones": "/accounting/facturations/download",
    "reparadoras"  : "/accounting/repairs/download",
    "collections"  : "/accounting/collections/download",
}
TIPOS_COMISION = ["LIQUIDACION_COLOMBIA","MENSUALIDAD_COLOMBIA","INSCRIPCION_COLOMBIA"]

# =======================
# Sesión HTTP y auth
# =======================
def make_session():
    s = requests.Session()
    retry = Retry(
        total=5, connect=3, read=3, backoff_factor=1.2,
        status_forcelist=[408,429,500,502,503,504],
        allowed_methods={"POST"},
        raise_on_status=False,
        respect_retry_after_header=True
    )
    s.mount("https://", HTTPAdapter(max_retries=retry))
    s.mount("http://",  HTTPAdapter(max_retries=retry))
    s.headers.update({
        "User-Agent": "BravoDataClient/1.1 (+colab/local)",
        "Accept-Encoding": "gzip, deflate, br",
        "Connection": "keep-alive",
    })
    return s

session = make_session()

_token_lock = threading.Lock()
_token_cache = {"token": None, "user": USER_API, "secret": SECRET_API}

def _sleep_with_jitter(base_s: float):
    time.sleep(base_s + random.uniform(*JITTER_S))

def _get_new_token():
    # Backoff explícito para el auth (504/timeout)
    attempt = 0
    while True:
        attempt += 1
        try:
            r = session.post(
                f"{BASE_URL}/auth/generate-token",
                json={"user": _token_cache["user"], "secret": _token_cache["secret"]},
                headers={"Content-Type":"application/json","Accept":"application/json"},
                timeout=(10,45)
            )
            if r.status_code in (429, 500, 502, 503, 504):
                # respetar Retry-After si viene
                ra = r.headers.get("Retry-After")
                if ra:
                    try:
                        _sleep_with_jitter(float(ra))
                    except Exception:
                        _sleep_with_jitter(min(BACKOFF_CAP_S, BACKOFF_BASE_S*(2**(attempt-1))))
                    continue
            r.raise_for_status()
            tok = r.json().get("token")
            if not tok:
                raise RuntimeError("Auth OK pero no vino 'token'.")
            return tok
        except requests.RequestException:
            if attempt >= 5:
                raise
            _sleep_with_jitter(min(BACKOFF_CAP_S, BACKOFF_BASE_S*(2**(attempt-1))))

def get_token_cached(force=False):
    with _token_lock:
        if force or not _token_cache["token"]:
            _token_cache["token"] = _get_new_token()
        return _token_cache["token"]

# =======================
# Rate limiter global por host
# =======================
_last_call_lock = threading.Lock()
_last_call_ts = 0.0

def _polite_pause():
    global _last_call_ts
    with _last_call_lock:
        now = time.perf_counter()
        wait = _last_call_ts + MIN_INTERVAL_S - now
        if wait > 0:
            time.sleep(wait)
        _last_call_ts = time.perf_counter()

# =======================
# Utilidades
# =======================
def _read_csv_bytes(content: bytes) -> pd.DataFrame:
    if not content or not content.strip():
        return pd.DataFrame()
    first = content.split(b"\n", 1)[0]
    sep = b';' if first.count(b';') >= first.count(b',') else b','
    return pd.read_csv(io.BytesIO(content), sep=sep.decode(), dtype=str)

def _post_csv_once(resource: str, page: int, body):
    url = f"{BASE_URL}{resource}"
    tok = get_token_cached()
    headers = {
        "Authorization": f"Bearer {tok}",
        "Accept": "text/csv, text/plain",
        "Content-Type": "application/json",
    }
    params = {"pageToDownload": str(page)}
    _polite_pause()
    r = session.post(url, headers=headers, params=params, json=body, timeout=(12,90))
    # Manejo 401 -> refresh token una sola vez
    if r.status_code == 401:
        tok = get_token_cached(force=True)
        headers["Authorization"] = f"Bearer {tok}"
        _polite_pause()
        r = session.post(url, headers=headers, params=params, json=body, timeout=(12,90))
    return r

def _post_csv(resource: str, page: int, body):
    """
    POST con backoff suave + respeto de Retry-After/429.
    Devuelve bytes CSV o lanza excepción si realmente falla.
    """
    attempt = 0
    while True:
        attempt += 1
        r = _post_csv_once(resource, page, body)
        # Respetar Retry-After
        if r.status_code in (429, 500, 502, 503, 504):
            ra = r.headers.get("Retry-After")
            if ra:
                try:
                    _sleep_with_jitter(float(ra))
                    continue
                except Exception:
                    pass
        if r.status_code >= 400:
            if attempt <= MAX_RETRIES_SOFT and r.status_code in (408, 429, 500, 502, 503, 504):
                _sleep_with_jitter(min(BACKOFF_CAP_S, BACKOFF_BASE_S*(2**(attempt-1))))
                continue
            # Si seguimos fallando, levantar con resumen breve
            raise RuntimeError(f"[{resource}] Error {r.status_code} en page={page}. Resumen: {r.text[:300]}")
        return r.content

def _fetch_batch(resource: str, start_page: int, body, workers, window):
    pages = list(range(start_page, start_page + window))
    out = {}
    with ThreadPoolExecutor(max_workers=workers) as ex:
        futs = {ex.submit(_post_csv, resource, p, body): p for p in pages}
        for f in as_completed(futs):
            p = futs[f]
            try:
                out[p] = _read_csv_bytes(f.result())
            except Exception:
                out[p] = pd.DataFrame()
    # Devuelve ordenadas
    return [out[p] for p in pages]

def _download_parallel(resource: str, body, max_pages, workers, window):
    """
    Descarga por lotes paralelos con corte en primer vacío.
    Usa fallback a 1-based si la 0-based arranca vacía.
    """
    frames = []
    # --- 0-based ---
    cur = 0
    while cur < max_pages:
        batch = _fetch_batch(resource, cur, body, workers, window)
        if cur == 0 and all(df.empty for df in batch):  # intentar 1-based
            break
        for df in batch:
            if df.empty:
                return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
            frames.append(df)
        cur += window
    if frames:
        return pd.concat(frames, ignore_index=True)

    # --- 1-based ---
    frames = []
    cur = 1
    while cur < max_pages+1:
        batch = _fetch_batch(resource, cur, body, workers, window)
        if cur == 1 and all(df.empty for df in batch):
            return pd.DataFrame()
        for df in batch:
            if df.empty:
                return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
            frames.append(df)
        cur += window
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()

def _download_sequential(resource: str, body, max_pages):
    """
    Descarga SECUENCIAL (muy respetuosa). Fallback a 1-based.
    Pausa corta entre páginas para reducir presión.
    """
    frames = []
    # 0-based
    for p in range(max_pages):
        try:
            content = _post_csv(resource, p, body)
            df = _read_csv_bytes(content)
        except Exception:
            df = pd.DataFrame()
        if df.empty:
            if p == 0:
                # 1-based fallback
                for p1 in range(1, max_pages+1):
                    try:
                        content1 = _post_csv(resource, p1, body)
                        df1 = _read_csv_bytes(content1)
                    except Exception:
                        df1 = pd.DataFrame()
                    if df1.empty:
                        break
                    frames.append(df1)
                    _sleep_with_jitter(0.12)  # pausa amable
                break
            break
        frames.append(df)
        _sleep_with_jitter(0.12)  # pausa amable
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()

# =======================
# Descargadores
# =======================
def descargar_facturaciones_tres_tipos():
    dfs = []
    for tipo in TIPOS_COMISION:
        body = [{
            "column": "Comision",
            "attribute": "commissionType",
            "columnType": "ENUM",
            "table": "facturation",
            "operation": "IGUAL_A",
            "value": tipo
        }]
        df = _download_parallel(
            ENDPOINTS["facturaciones"], body,
            max_pages=MAX_PAGES,
            workers=MAX_WORKERS_GENERAL,
            window=WINDOW_GENERAL
        )
        if not df.empty:
            dfs.append(df)
        print(f"[Facturaciones/{tipo}] filas: {0 if df is None else len(df)}")
        _sleep_with_jitter(0.3)  # pausa entre tipos
    if not dfs:
        return pd.DataFrame()
    return pd.concat(dfs, ignore_index=True).drop_duplicates()

def descargar_reparadoras():
    # Reparadoras: tráfico moderado, pero seguro y amable
    return _download_sequential(ENDPOINTS["reparadoras"], body=[], max_pages=MAX_PAGES)

def _norm(s: str) -> str:
    import unicodedata as _ud
    return ''.join(c for c in _ud.normalize('NFKD', str(s)) if not _ud.combining(c)).lower().strip()

def filtrar_collections_cobrado(df: pd.DataFrame) -> pd.DataFrame:
    """Devuelve solo filas con Estado de cobro == Cobrado (case-insensitive)."""
    if df.empty:
        return df
    norm_cols = {col: _norm(col) for col in df.columns}
    cand = None
    for col, n in norm_cols.items():
        if "estado" in n and ("cobro" in n or "cobranza" in n or "collection" in n or "charge" in n):
            cand = col
            break
    if cand is None:
        for col in df.columns:
            if _norm(col) == "estado de cobro":
                cand = col
                break
    if cand is None:
        print("⚠️ No encontré columna 'Estado de cobro'; devuelvo Collections sin filtrar.")
        return df
    mask = df[cand].astype(str).str.lower().str.contains("cobrado")
    return df[mask].reset_index(drop=True)

def descargar_collections_filtrado():
    # Collections: extremo respeto → secuencial + pausas
    df = _download_sequential(ENDPOINTS["collections"], body=[], max_pages=MAX_PAGES)
    return filtrar_collections_cobrado(df)

# =======================
# Ejecutar todo
# =======================
get_token_cached(force=True)

c_facturaciones = descargar_facturaciones_tres_tipos()
reparadoras_df  = descargar_reparadoras()
collections_df  = descargar_collections_filtrado()  # solo 'Cobrado/COBRADO'

print(f"Facturaciones (3 tipos): {len(c_facturaciones)} filas | {len(c_facturaciones.columns)} cols")
print(f"Reparadoras           : {len(reparadoras_df)} filas | {len(reparadoras_df.columns)} cols")
print(f"Collections (Cobrado) : {len(collections_df)} filas | {len(collections_df.columns)} cols")

display(c_facturaciones.head(3))
display(reparadoras_df.head(3))
display(collections_df.head(3))

[Facturaciones/LIQUIDACION_COLOMBIA] filas: 87048
[Facturaciones/MENSUALIDAD_COLOMBIA] filas: 889903
[Facturaciones/INSCRIPCION_COLOMBIA] filas: 98091
Facturaciones (3 tipos): 1075042 filas | 38 cols
Reparadoras           : 0 filas | 0 cols
Collections (Cobrado) : 809179 filas | 55 cols

,Id,Empresa Emisora,Credito,Status facturacion,Tipo de comision,Status reparadora,Referencia,Monto,Fecha de facturacion,Fecha de envio de cobro,...,Prefijo Resolucion,CUFE,Descripcion,Referencia credito,Tiene Nota Credito Electronica,Fecha de Nota Credito Electronica,Status NC Sistema Contable,Subido NC a Sistema Contable por,Fecha NC subida a sistema contable,Tipo de Documento Electronico
0,1186301,RESUELVE_TU_DEUDA_COLOMBIA_SAS,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,NaN,3208712958,294118.0,4/10/2023,2/1/2024,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
1,1186303,RESUELVE_TU_DEUDA_COLOMBIA_SAS,false,COBRADO,LIQUIDACION_COLOMBIA,NaN,3182588339,100000.0,3/10/2023,23/10/2023,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
2,1186306,RESUELVE_TU_DEUDA_COLOMBIA_SAS,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,NaN,3505172416,111566.0,3/10/2023,4/12/2023,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo

Empty DataFrame
Columns: []
Index: []

,Id,Monto,Estado de cobro,Fecha de cobro,Banco receptor,Folio del cobro,Folio de Nota Credito,Id Factura Relacionada,Tiene Nota Credito Electronica,Fecha de Nota Credito Electronica,...,Prefijo Resolucion,CUFE,Descripcion,Referencia credito,Tiene Nota Credito Electronica.1,Fecha de Nota Credito Electronica.1,Status NC Sistema Contable.1,Subido NC a Sistema Contable por.1,Fecha NC subida a sistema contable.1,Tipo de Documento Electronico
0,1,11890.0,COBRADO,15/8/2023,BANCOLOMBIA,NaN,NaN,993984,No,Sin Status,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
1,2,23136.0,COBRADO,15/8/2023,BANCOLOMBIA,NaN,NaN,966290,No,Sin Status,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
2,3,12191.0,COBRADO,15/8/2023,BANCOLOMBIA,NaN,NaN,978079,No,Sin Status,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo

In [3]:
c_facturaciones

,Id,Empresa Emisora,Credito,Status facturacion,Tipo de comision,Status reparadora,Referencia,Monto,Fecha de facturacion,Fecha de envio de cobro,...,Prefijo Resolucion,CUFE,Descripcion,Referencia credito,Tiene Nota Credito Electronica,Fecha de Nota Credito Electronica,Status NC Sistema Contable,Subido NC a Sistema Contable por,Fecha NC subida a sistema contable,Tipo de Documento Electronico
0,1186301,RESUELVE_TU_DEUDA_COLOMBIA_SAS,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,NaN,3208712958,294118.0,4/10/2023,2/1/2024,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
1,1186303,RESUELVE_TU_DEUDA_COLOMBIA_SAS,false,COBRADO,LIQUIDACION_COLOMBIA,NaN,3182588339,100000.0,3/10/2023,23/10/2023,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
2,1186306,RESUELVE_TU_DEUDA_COLOMBIA_SAS,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,NaN,3505172416,111566.0,3/10/2023,4/12/2023,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
3,1186311,RESUELVE_TU_DEUDA_COLOMBIA_SAS,true,COBRADO,LIQUIDACION_COLOMBIA,NaN,3233270136,853382.5499999999,4/10/2023,Sin fecha,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
4,1186314,RESUELVE_TU_DEUDA_COLOMBIA_SAS,false,COBRADO,LIQUIDACION_COLOMBIA,NaN,3223109455,10162.5,4/10/2023,10/10/2023,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075037,3462754,GO_BRAVO_COLOMBIA_SAS,false,POR_COBRAR,INSCRIPCION_COLOMBIA,ACTIVO,3202671836,337606.0,7/4/2026,Sin fecha,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
1075038,3462755,GO_BRAVO_COLOMBIA_SAS,false,COBRO_PARCIAL,INSCRIPCION_COLOMBIA,ACTIVO,3123604311,1294412.0,7/4/2026,8/4/2026,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
1075039,3462756,GO_BRAVO_COLOMBIA_SAS,false,COBRO_PARCIAL,INSCRIPCION_COLOMBIA,ACTIVO,3146102176,341484.0,7/4/2026,8/4/2026,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
1075040,3462757,GO_BRAVO_COLOMBIA_SAS,false,COBRO_PARCIAL,INSCRIPCION_COLOMBIA,ACTIVO,3244300029,1032018.0,7/4/2026,8/4/2026,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
1075041,3462890,GO_BRAVO_COLOMBIA_SAS,false,COBRO_PARCIAL_EN_TRAMITE,INSCRIPCION_COLOMBIA,ACTIVO,3006158930,1204769.0,9/4/2026,9/4/2026,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo

Por cobrar

In [4]:
def filtrar_facturaciones_por_cobrar_liquidacion(df):
    if df.empty:
        return df

    # Normalizar nombres de columnas
    cols_norm = {col: col.strip().lower() for col in df.columns}

    col_status = None
    col_tipo = None

    # Buscar columnas dinámicamente
    for col, norm in cols_norm.items():
        if "status" in norm and "fact" in norm:
            col_status = col
        if "tipo" in norm and "comision" in norm:
            col_tipo = col

    if not col_status or not col_tipo:
        print("⚠️ No se encontraron las columnas necesarias")
        return pd.DataFrame()

    # Filtrar
    df_filtrado = df[
        df[col_status].astype(str).str.upper().str.strip().eq("POR_COBRAR") &
        df[col_tipo].astype(str).str.upper().str.strip().eq("LIQUIDACION_COLOMBIA")
    ].copy()

    return df_filtrado

In [5]:
c_facturaciones_X_COBRAR = filtrar_facturaciones_por_cobrar_liquidacion(c_facturaciones)

print("Filas POR_COBRAR + LIQUIDACION:", len(c_facturaciones_X_COBRAR))
display(c_facturaciones_X_COBRAR.head(3))

Filas POR_COBRAR + LIQUIDACION: 2102

,Id,Empresa Emisora,Credito,Status facturacion,Tipo de comision,Status reparadora,Referencia,Monto,Fecha de facturacion,Fecha de envio de cobro,...,Prefijo Resolucion,CUFE,Descripcion,Referencia credito,Tiene Nota Credito Electronica,Fecha de Nota Credito Electronica,Status NC Sistema Contable,Subido NC a Sistema Contable por,Fecha NC subida a sistema contable,Tipo de Documento Electronico
52422,2350110,RESUELVE_TU_DEUDA_COLOMBIA_SAS,false,POR_COBRAR,LIQUIDACION_COLOMBIA,BAJA_SOLICITADA,3184670854,181311.0,14/8/2024,Sin fecha,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
53398,2362070,RESUELVE_TU_DEUDA_COLOMBIA_SAS,false,POR_COBRAR,LIQUIDACION_COLOMBIA,ACTIVO,3213490728,372348.9076,29/8/2024,Sin fecha,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
57610,2490929,RESUELVE_TU_DEUDA_COLOMBIA_SAS,false,POR_COBRAR,LIQUIDACION_COLOMBIA,ACTIVO,3214995888,1260504.0,31/10/2024,Sin fecha,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo

#COBRADO

In [6]:
def filtrar_facturaciones_cobro_liquidacion(df):
    if df.empty:
        return df

    # Normalizar nombres de columnas
    cols_norm = {col: col.strip().lower() for col in df.columns}

    col_status = None
    col_tipo = None

    # Buscar columnas dinámicamente
    for col, norm in cols_norm.items():
        if "status" in norm and "fact" in norm:
            col_status = col
        if "tipo" in norm and "comision" in norm:
            col_tipo = col

    if not col_status or not col_tipo:
        print("⚠️ No se encontraron las columnas necesarias")
        return pd.DataFrame()

    # Valores válidos de status
    estados_validos = ["COBRADO", "COBRO_PARCIAL_COBRADO"]

    # Filtrar
    df_filtrado = df[
        df[col_status].astype(str).str.upper().str.strip().isin(estados_validos) &
        df[col_tipo].astype(str).str.upper().str.strip().eq("LIQUIDACION_COLOMBIA")
    ].copy()

    return df_filtrado

In [7]:
c_facturaciones_COBRADO = filtrar_facturaciones_cobro_liquidacion(c_facturaciones)

print("Filas POR_COBRAR + LIQUIDACION:", len(c_facturaciones_COBRADO))
display(c_facturaciones_COBRADO.head(3))

Filas POR_COBRAR + LIQUIDACION: 79952

,Id,Empresa Emisora,Credito,Status facturacion,Tipo de comision,Status reparadora,Referencia,Monto,Fecha de facturacion,Fecha de envio de cobro,...,Prefijo Resolucion,CUFE,Descripcion,Referencia credito,Tiene Nota Credito Electronica,Fecha de Nota Credito Electronica,Status NC Sistema Contable,Subido NC a Sistema Contable por,Fecha NC subida a sistema contable,Tipo de Documento Electronico
0,1186301,RESUELVE_TU_DEUDA_COLOMBIA_SAS,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,NaN,3208712958,294118.0,4/10/2023,2/1/2024,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
1,1186303,RESUELVE_TU_DEUDA_COLOMBIA_SAS,false,COBRADO,LIQUIDACION_COLOMBIA,NaN,3182588339,100000.0,3/10/2023,23/10/2023,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo
2,1186306,RESUELVE_TU_DEUDA_COLOMBIA_SAS,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,NaN,3505172416,111566.0,3/10/2023,4/12/2023,...,Sin Prefijo Resolucion,Sin Cufe,Sin Descripcion,Sin ref credito,No,Sin Status,NO_CARGADO,Sin data,Sin fecha,Sin tipo

In [8]:
# ========= Imports =========
import io, os, requests, pandas as pd
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
from IPython.display import display

# ========= Secrets (Colab o ENV) =========
def _get_secret(name: str):
    # 1) Colab
    try:
        from google.colab import userdata as _ud
        val = _ud.get(name)
        if val:
            return val
    except Exception:
        pass
    # 2) GitHub/local
    return os.environ.get(name)

USER_API   = _get_secret("USER_API")
SECRET_API = _get_secret("SECRET_API")
if not USER_API or not SECRET_API:
    raise ValueError("Falta USER_API o SECRET_API. En Colab: agrégalo en 'Secretos'. "
                     "En GitHub/local: define variables/Secrets de entorno.")

# ========= Constantes =========
BASE_URL  = "https://mutatio-api.gobravo.dev"
RESOURCE  = "/accounting/repairs/download"   # <-- reparadoras

# ========= Sesión con reintentos =========
def make_session():
    s = requests.Session()
    retry = Retry(
        total=3, connect=2, read=2, backoff_factor=1.2,
        status_forcelist=[502,503,504], allowed_methods={"POST"},
        raise_on_status=False
    )
    s.mount("https://", HTTPAdapter(max_retries=retry))
    s.mount("http://",  HTTPAdapter(max_retries=retry))
    return s

session = make_session()

# ========= Auth =========
def get_token(user: str, secret: str) -> str:
    r = session.post(f"{BASE_URL}/auth/generate-token",
                     json={"user": user, "secret": secret},
                     headers={"Content-Type":"application/json","Accept":"application/json"},
                     timeout=(10,45))
    r.raise_for_status()
    tok = r.json().get("token")
    if not tok:
        raise RuntimeError("Auth OK pero no vino 'token'.")
    return tok

# ========= Util: leer CSV con ; o , =========
def _leer_csv_flexible(resp) -> pd.DataFrame:
    resp.raise_for_status()
    txt = resp.text or ""
    if not txt.strip():
        return pd.DataFrame()
    first = txt.splitlines()[0]
    sep = ';' if first.count(';') >= first.count(',') else ','
    return pd.read_csv(io.StringIO(txt), sep=sep, dtype=str)

# ========= Descarga (una página) con auto-refresh de token =========
def descargar_pagina_repairs(user: str, secret: str, page: int, filtros=None) -> pd.DataFrame:
    if filtros is None:
        filtros = []  # este endpoint funciona sin body
    url = f"{BASE_URL}{RESOURCE}"

    def _do(tok):
        return session.post(
            url,
            headers={
                "Authorization": f"Bearer {tok}",
                "Accept": "text/csv, text/plain",
                "Content-Type": "application/json",
            },
            params={"pageToDownload": str(page)},
            json=filtros,
            timeout=(12,90)
        )

    token = get_token(user, secret)
    r = _do(token)
    if r.status_code == 401:
        token = get_token(user, secret)
        r = _do(token)

    if r.status_code >= 400:
        raise RuntimeError(f"Error {r.status_code} en page={page}. Resumen: {r.text[:300]}")

    return _leer_csv_flexible(r)

# ========= Descarga total (paginando) =========
def descargar_todo_repairs(user: str, secret: str, max_pages: int = 1000, filtros=None) -> pd.DataFrame:
    frames = []
    # 0-based
    for page in range(max_pages):
        df = descargar_pagina_repairs(user, secret, page=page, filtros=filtros)
        if df.empty:
            if page == 0:
                # fallback 1-based
                frames1 = []
                for p1 in range(1, max_pages+1):
                    df1 = descargar_pagina_repairs(user, secret, page=p1, filtros=filtros)
                    if df1.empty:
                        break
                    frames1.append(df1)
                    if p1 % 25 == 0:
                        print(f"[1-based] páginas leídas: {p1}")
                return pd.concat(frames1, ignore_index=True) if frames1 else pd.DataFrame()
            break
        frames.append(df)
        if page % 25 == 0 and page > 0:
            print(f"[0-based] páginas leídas: {page+1}")

    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()

# ========= Ejecutar =========
reparadoras_df = descargar_todo_repairs(USER_API, SECRET_API, max_pages=1200)

print(f"Filas totales: {len(reparadoras_df)} | Columnas: {len(reparadoras_df.columns)}")
display(reparadoras_df.head())
print(reparadoras_df.columns.tolist())

Filas totales: 60133 | Columnas: 28

,Id,Referencia,Berex Id,Nombre Completo,Numero de Documento,Correo Electronico,Status,Fecha de Inicio,Tipo,Deuda Resuelve,...,Fecha de baja,Tipo de Pricing,Fecha de Reactivación,Porcentaje Liquidacion,Comision Inicial,Comision Mensual,Fecha de creacion,Fecha de actualizacion,Creado por,Actualizado por
0,277408,52251370,629652,MARIA MERCEDES MARTINEZ GARZON,52251370,czmmmartinez@gmail.com,ACTIVO,30/3/2026,13,3.993675E7,...,NaN,Tradicional,NaN,0.15,1248450.0,210187.75,8/4/2026 13:50:53,8/4/2026 13:50:53,felipe.contreras,felipe.contreras
1,276913,3123016506,3,Arely Josefina Delgado Vasquez,52821117,jodelvas24@gmail.com,ACTIVO,7/4/2026,17,1.59327E7,...,NaN,Tradicional,NaN,0.1152,773654.0,90167.5,7/4/2026 11:58:19,7/4/2026 12:52:57,felipe.contreras,felipe.contreras
2,276910,3244300029,626099,JUAN JOSE GUZMAN PIZANO,1000556970,guzmanpizanojuanjose@gmail.com,ACTIVO,29/3/2026,13,3.33465E7,...,NaN,Tradicional,NaN,0.15,1032018.0,177004.0,7/4/2026 11:17:44,10/4/2026 21:10:32,felipe.contreras,felipe.contreras
3,276909,3146102176,627088,FRANCISCO ADOLFO VASQUEZ VELASQUEZ,70126359,adolfo2026@gmail.com,ACTIVO,29/3/2026,13,7635100.0,...,NaN,Tradicional,NaN,0.15,341484.0,48679.5,7/4/2026 11:17:44,10/4/2026 21:14:38,felipe.contreras,felipe.contreras
4,276908,3123604311,625069,Geovanny andres Noy PatiÃ±o,74754792,andypat-72@hotmail.com,ACTIVO,29/3/2026,13,4.15725E7,...,NaN,Tradicional,NaN,0.15,1294412.0,218504.0,7/4/2026 11:17:44,10/4/2026 21:10:32,felipe.contreras,felipe.contreras

['Id', 'Referencia', 'Berex Id', 'Nombre Completo', 'Numero de Documento', 'Correo Electronico', 'Status', 'Fecha de Inicio', 'Tipo', 'Deuda Resuelve', 'Movimientos Mensual', 'Numero de Deudas', 'Termino de programa', 'Vehiculo de ahorro', 'Empresa', 'ARD', 'Fecha de graduación', 'Deuda inicial Fija', 'Fecha de baja', 'Tipo de Pricing', 'Fecha de Reactivación', 'Porcentaje Liquidacion', 'Comision Inicial', 'Comision Mensual', 'Fecha de creacion', 'Fecha de actualizacion', 'Creado por', 'Actualizado por']

In [9]:
import unicodedata
import pandas as pd
from IPython.display import display

def _norm(s: str) -> str:
    s = '' if s is None else str(s)
    # normaliza acentos y espacios
    s = unicodedata.normalize("NFKD", s)
    s = ''.join(c for c in s if not unicodedata.combining(c))
    return ' '.join(s.lower().strip().split())

def subset_by_names(df: pd.DataFrame, wanted: list[str]) -> pd.DataFrame:
    """Selecciona columnas con match insensible a acentos/mayúsculas y en el orden pedido."""
    if df is None or df.empty:
        return pd.DataFrame()
    # mapa normalizado -> nombre real
    norm_to_real = {}
    for c in df.columns:
        nc = _norm(c)
        # si hay duplicados normalizados, conservamos el primero
        if nc not in norm_to_real:
            norm_to_real[nc] = c
    out_cols = []
    missing  = []
    for w in wanted:
        nc = _norm(w)
        if nc in norm_to_real:
            out_cols.append(norm_to_real[nc])
        else:
            missing.append(w)
    if missing:
        print("⚠️ No encontré en el DataFrame:", missing)
    if not out_cols:
        return pd.DataFrame()
    return df.loc[:, out_cols]

# ------------------------------
# 1) reparadoras_df (con rename)
# ------------------------------
rep_wanted = [
    'Referencia',
    'Berex Id',
    'Status',
    'Fecha de Inicio',
    'Deuda Resuelve',
    'Movimientos Mensual',   # será renombrada a "Apartado Mensual"
    'Comision Inicial',
    'Comision Mensual',
    'Vehiculo de ahorro',
    'Fecha de graduación',
    'Deuda inicial Fija',
    'Fecha de baja',
    'Tipo de Pricing',
]

rep_sel = subset_by_names(reparadoras_df, rep_wanted).copy()

# renombrar "Movimientos Mensual" -> "Apartado Mensual" (resistente a acentos/mayúsculas)
for col in list(rep_sel.columns):
    if _norm(col) == _norm('Movimientos Mensual'):
        rep_sel.rename(columns={col: 'Apartado Mensual'}, inplace=True)
        break

print(f"reparadoras_df -> {rep_sel.shape[0]} filas x {rep_sel.shape[1]} cols")
display(rep_sel.head())

# -----------------------------------
# 2) c_facturaciones (solo columnas)
# -----------------------------------
fac_wanted = [
    'Id',
    'Credito',
    'Status facturacion',
    'Tipo de comision',
    'Referencia',
    'Monto',
    'Fecha de facturacion',
    'Fecha de cobro',
]
fac_sel = subset_by_names(c_facturaciones, fac_wanted).copy()
print(f"c_facturaciones -> {fac_sel.shape[0]} filas x {fac_sel.shape[1]} cols")
display(fac_sel.head())

# --------------------------------
# 3) collections_df (solo columnas)
# --------------------------------
col_wanted = [
    'Id',
    'Monto',
    'Estado de cobro',
    'Fecha de cobro',
    'Fecha de facturacion',
    'Status facturacion',
    'Tipo de comision',
    'Referencia',

]
col_sel = subset_by_names(collections_df, col_wanted).copy()
print(f"collections_df -> {col_sel.shape[0]} filas x {col_sel.shape[1]} cols")
display(col_sel.head())

# (Opcional) reasignar a las variables originales si quieres seguir trabajando con las versiones reducidas
# reparadoras_df  = rep_sel
# c_facturaciones = fac_sel
# collections_df  = col_sel

reparadoras_df -> 60133 filas x 13 cols

,Referencia,Berex Id,Status,Fecha de Inicio,Deuda Resuelve,Apartado Mensual,Comision Inicial,Comision Mensual,Vehiculo de ahorro,Fecha de graduación,Deuda inicial Fija,Fecha de baja,Tipo de Pricing
0,52251370,629652,ACTIVO,30/3/2026,3.993675E7,618973.06,1248450.0,210187.75,POWWI,NaN,3.993675E7,NaN,Tradicional
1,3123016506,3,ACTIVO,7/4/2026,1.59327E7,381575.0,773654.0,90167.5,COINK,NaN,1.59327E7,NaN,Tradicional
2,3244300029,626099,ACTIVO,29/3/2026,3.33465E7,510757.13,1032018.0,177004.0,COINK,NaN,3.33465E7,NaN,Tradicional
3,3146102176,627088,ACTIVO,29/3/2026,7635100.0,165489.82,341484.0,48679.5,POWWI,NaN,7635100.0,NaN,Tradicional
4,3123604311,625069,ACTIVO,29/3/2026,4.15725E7,641953.93,1294412.0,218504.0,COINK,NaN,4.15725E7,NaN,Tradicional

c_facturaciones -> 1075042 filas x 8 cols

,Id,Credito,Status facturacion,Tipo de comision,Referencia,Monto,Fecha de facturacion,Fecha de cobro
0,1186301,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,3208712958,294118.0,4/10/2023,3/1/2024
1,1186303,false,COBRADO,LIQUIDACION_COLOMBIA,3182588339,100000.0,3/10/2023,24/10/2023
2,1186306,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,3505172416,111566.0,3/10/2023,5/12/2023
3,1186311,true,COBRADO,LIQUIDACION_COLOMBIA,3233270136,853382.5499999999,4/10/2023,4/10/2023
4,1186314,false,COBRADO,LIQUIDACION_COLOMBIA,3223109455,10162.5,4/10/2023,11/10/2023

collections_df -> 809179 filas x 8 cols

,Id,Monto,Estado de cobro,Fecha de cobro,Fecha de facturacion,Status facturacion,Tipo de comision,Referencia
0,1,11890.0,COBRADO,15/8/2023,24/7/2023,COBRO_PARCIAL_COBRADO,INTERESES,6007350
1,2,23136.0,COBRADO,15/8/2023,11/7/2023,COBRO_PARCIAL_COBRADO,INTERESES,6006933
2,3,12191.0,COBRADO,15/8/2023,17/7/2023,COBRO_PARCIAL_COBRADO,INTERESES,6003875
3,4,11671.0,COBRADO,15/8/2023,17/7/2023,COBRO_PARCIAL_COBRADO,INTERESES,6002993R
4,5,31133.0,COBRADO,15/8/2023,11/7/2023,COBRO_PARCIAL_COBRADO,INTERESES,6006986

In [10]:
def filter_eq(df: pd.DataFrame, col_like: str, value: str = "COBRADO") -> pd.DataFrame:
    if df is None or df.empty:
        return pd.DataFrame(columns=[])
    target = None
    for c in df.columns:
        if _norm(c) == _norm(col_like):
            target = c
            break
    if target is None:
        print(f"⚠️ No encontré la columna '{col_like}'.")
        return pd.DataFrame(columns=df.columns)
    mask = df[target].astype(str).str.upper().str.strip().eq(value.upper())
    return df.loc[mask].reset_index(drop=True)

# Filtrar según lo que pediste:
fac_sel = filter_eq(fac_sel, "Status facturacion", "COBRADO")
col_sel = filter_eq(col_sel, "Estado de cobro", "COBRADO")

print(f"fac_sel (Status facturacion=COBRADO): {fac_sel.shape}")
print(f"col_sel (Estado de cobro=COBRADO): {col_sel.shape}")
display(fac_sel.head())
display(col_sel.head())

fac_sel (Status facturacion=COBRADO): (743806, 8)
col_sel (Estado de cobro=COBRADO): (809179, 8)

,Id,Credito,Status facturacion,Tipo de comision,Referencia,Monto,Fecha de facturacion,Fecha de cobro
0,1186303,false,COBRADO,LIQUIDACION_COLOMBIA,3182588339,100000.0,3/10/2023,24/10/2023
1,1186311,true,COBRADO,LIQUIDACION_COLOMBIA,3233270136,853382.5499999999,4/10/2023,4/10/2023
2,1186314,false,COBRADO,LIQUIDACION_COLOMBIA,3223109455,10162.5,4/10/2023,11/10/2023
3,1186316,false,COBRADO,LIQUIDACION_COLOMBIA,3142688054,2506.0499999999997,4/10/2023,6/10/2023
4,1186318,false,COBRADO,LIQUIDACION_COLOMBIA,3214595216,218440.0,4/10/2023,6/10/2023

,Id,Monto,Estado de cobro,Fecha de cobro,Fecha de facturacion,Status facturacion,Tipo de comision,Referencia
0,1,11890.0,COBRADO,15/8/2023,24/7/2023,COBRO_PARCIAL_COBRADO,INTERESES,6007350
1,2,23136.0,COBRADO,15/8/2023,11/7/2023,COBRO_PARCIAL_COBRADO,INTERESES,6006933
2,3,12191.0,COBRADO,15/8/2023,17/7/2023,COBRO_PARCIAL_COBRADO,INTERESES,6003875
3,4,11671.0,COBRADO,15/8/2023,17/7/2023,COBRO_PARCIAL_COBRADO,INTERESES,6002993R
4,5,31133.0,COBRADO,15/8/2023,11/7/2023,COBRO_PARCIAL_COBRADO,INTERESES,6006986

In [11]:
import pandas as pd

# Supongamos que ya tienes tu DataFrame col_sel cargado
# Filtrar las filas
col_sel_filtrado = col_sel[col_sel['Tipo de comision'].isin([
    'LIQUIDACION_COLOMBIA',
    'MENSUALIDAD_COLOMBIA',
    'INSCRIPCION_COLOMBIA'
])]

# Si quieres reemplazar el DataFrame original
col_sel = col_sel_filtrado

In [12]:
col_sel

,Id,Monto,Estado de cobro,Fecha de cobro,Fecha de facturacion,Status facturacion,Tipo de comision,Referencia
76353,83511,77149.0,COBRADO,27/9/2023,1/10/2023,COBRO_PARCIAL_COBRADO,MENSUALIDAD_COLOMBIA,3203035694
76354,83512,25675.0,COBRADO,27/9/2023,1/10/2023,COBRO_PARCIAL_COBRADO,MENSUALIDAD_COLOMBIA,3152249590
76355,83513,10464.0,COBRADO,27/9/2023,1/10/2023,COBRO_PARCIAL_COBRADO,MENSUALIDAD_COLOMBIA,3154444468
76356,83514,25527.0,COBRADO,27/9/2023,1/10/2023,COBRO_PARCIAL_INCOBRABLE,MENSUALIDAD_COLOMBIA,3125466749
76357,83515,27526.0,COBRADO,27/9/2023,1/10/2023,COBRO_PARCIAL_INCOBRABLE,MENSUALIDAD_COLOMBIA,3167088085
...,...,...,...,...,...,...,...,...
809174,885302,315963.0,COBRADO,9/4/2026,16/3/2026,COBRO_PARCIAL_EN_TRAMITE,INSCRIPCION_COLOMBIA,3207646800
809175,885303,627741.0,COBRADO,9/4/2026,19/3/2026,COBRO_PARCIAL_EN_TRAMITE,INSCRIPCION_COLOMBIA,3205228752
809176,885304,1236.0,COBRADO,9/4/2026,7/4/2026,COBRO_PARCIAL,INSCRIPCION_COLOMBIA,3144743259
809177,885305,137696.0,COBRADO,9/4/2026,18/3/2026,COBRO_PARCIAL_EN_TRAMITE,LIQUIDACION_COLOMBIA,3123776159
809178,885306,1832.0,COBRADO,9/4/2026,5/3/2026,COBRO_PARCIAL_COBRADO,MENSUALIDAD_COLOMBIA,3154551182

In [13]:
import pandas as pd
import unicodedata

def _norm(s: str) -> str:
    s = '' if s is None else str(s)
    s = unicodedata.normalize("NFKD", s)
    s = ''.join(c for c in s if not unicodedata.combining(c))
    return ' '.join(s.lower().strip().split())

def align_to_template(df: pd.DataFrame, template_cols: list[str], defaults: dict | None = None) -> pd.DataFrame:
    """Devuelve un DF con EXACTAMENTE las columnas de template_cols.
       Si falta alguna, la crea con defaults[col] o NaN."""
    defaults = defaults or {}
    norm_map = {_norm(c): c for c in df.columns}
    cols = {}
    for t in template_cols:
        nt = _norm(t)
        if nt in norm_map:
            cols[t] = df[norm_map[nt]]
        else:
            cols[t] = pd.Series([defaults.get(t, pd.NA)] * len(df), index=df.index, dtype="object")
    return pd.DataFrame(cols, index=df.index)

# 1) Plantilla = columnas de fac_sel (en tu screenshot son 8 columnas)
template = fac_sel.columns.tolist()

# 2) Valor por defecto para 'Credito' en col_sel (respetando el tipo de fac_sel)
cred_default = 'false' if str(fac_sel['Credito'].dtype) == 'object' else False
defaults_col_sel = {'Credito': cred_default}

# 3) Alinear col_sel a la plantilla (esto también crea 'Fecha de facturacion' si no existe)
col_sel_aligned = align_to_template(col_sel, template, defaults=defaults_col_sel)

# 4) Concatenar
unificado = pd.concat([fac_sel, col_sel_aligned], ignore_index=True)

print(f"fac_sel: {fac_sel.shape}  |  col_sel alineado: {col_sel_aligned.shape}")
print(f"unificado: {unificado.shape}")
display(unificado.head(10))

fac_sel: (743806, 8)  |  col_sel alineado: (455690, 8)
unificado: (1199496, 8)

,Id,Credito,Status facturacion,Tipo de comision,Referencia,Monto,Fecha de facturacion,Fecha de cobro
0,1186303,false,COBRADO,LIQUIDACION_COLOMBIA,3182588339,100000.0,3/10/2023,24/10/2023
1,1186311,true,COBRADO,LIQUIDACION_COLOMBIA,3233270136,853382.5499999999,4/10/2023,4/10/2023
2,1186314,false,COBRADO,LIQUIDACION_COLOMBIA,3223109455,10162.5,4/10/2023,11/10/2023
3,1186316,false,COBRADO,LIQUIDACION_COLOMBIA,3142688054,2506.0499999999997,4/10/2023,6/10/2023
4,1186318,false,COBRADO,LIQUIDACION_COLOMBIA,3214595216,218440.0,4/10/2023,6/10/2023
5,1186321,false,COBRADO,LIQUIDACION_COLOMBIA,3115705677,290452.5,4/10/2023,6/10/2023
6,1186322,false,COBRADO,LIQUIDACION_COLOMBIA,3223109455,38951.1,4/10/2023,11/10/2023
7,1186323,false,COBRADO,LIQUIDACION_COLOMBIA,3137009218,4804.8,4/10/2023,6/10/2023
8,1186324,false,COBRADO,LIQUIDACION_COLOMBIA,3168124099,49280.0,4/10/2023,10/10/2023
9,1186326,false,COBRADO,LIQUIDACION_COLOMBIA,3003971213,570380.0,4/10/2023,6/10/2023

In [14]:
unificado

,Id,Credito,Status facturacion,Tipo de comision,Referencia,Monto,Fecha de facturacion,Fecha de cobro
0,1186303,false,COBRADO,LIQUIDACION_COLOMBIA,3182588339,100000.0,3/10/2023,24/10/2023
1,1186311,true,COBRADO,LIQUIDACION_COLOMBIA,3233270136,853382.5499999999,4/10/2023,4/10/2023
2,1186314,false,COBRADO,LIQUIDACION_COLOMBIA,3223109455,10162.5,4/10/2023,11/10/2023
3,1186316,false,COBRADO,LIQUIDACION_COLOMBIA,3142688054,2506.0499999999997,4/10/2023,6/10/2023
4,1186318,false,COBRADO,LIQUIDACION_COLOMBIA,3214595216,218440.0,4/10/2023,6/10/2023
...,...,...,...,...,...,...,...,...
1199491,885302,false,COBRO_PARCIAL_EN_TRAMITE,INSCRIPCION_COLOMBIA,3207646800,315963.0,16/3/2026,9/4/2026
1199492,885303,false,COBRO_PARCIAL_EN_TRAMITE,INSCRIPCION_COLOMBIA,3205228752,627741.0,19/3/2026,9/4/2026
1199493,885304,false,COBRO_PARCIAL,INSCRIPCION_COLOMBIA,3144743259,1236.0,7/4/2026,9/4/2026
1199494,885305,false,COBRO_PARCIAL_EN_TRAMITE,LIQUIDACION_COLOMBIA,3123776159,137696.0,18/3/2026,9/4/2026
1199495,885306,false,COBRO_PARCIAL_COBRADO,MENSUALIDAD_COLOMBIA,3154551182,1832.0,5/3/2026,9/4/2026

In [15]:
import pandas as pd
import re

def _to_number_safe(x):
    s = str(x).strip()
    if not s:
        return pd.NA

    # Limpia moneda/espacios y convierte (1.234,56) -> -1.234,56
    s = s.replace("$", "").replace(" ", "")
    s = re.sub(r'^\((.*)\)$', r'-\1', s)

    # Encuentra el último separador
    last_dot = s.rfind('.')
    last_com = s.rfind(',')

    if last_dot == -1 and last_com == -1:
        return pd.to_numeric(s, errors="coerce")

    # El separador decimal es el que aparece más a la derecha
    if last_dot > last_com:
        dec = '.'
        thousands = ','
    else:
        dec = ','
        thousands = '.'

    # Elimina separador de miles
    s = s.replace(thousands, '')

    # Normaliza decimal a punto
    if dec == ',':
        s = s.replace(',', '.')

    return pd.to_numeric(s, errors="coerce")


# ----- 1) Partimos del DF unificado -----
df = unificado.copy()

for c in ["Id"]:
    if c in df.columns:
        df.drop(columns=c, inplace=True)

df["Credito"] = df["Credito"].astype(str).str.lower().str.strip()
df["Monto_num"] = df["Monto"].map(_to_number_safe).fillna(0)

# Parseo de fechas
df["Fecha de cobro"] = pd.to_datetime(df["Fecha de cobro"], dayfirst=True, errors="coerce")
df["Fecha de cobro"] = df["Fecha de cobro"].dt.to_period("M").dt.to_timestamp("M")

df["Fecha de facturacion"] = pd.to_datetime(df["Fecha de facturacion"], dayfirst=True, errors="coerce")
# (opcional) si quieres también a fin de mes:
# df["Fecha de facturacion"] = df["Fecha de facturacion"].dt.to_period("M").dt.to_timestamp("M")

# Claves originales (no incluimos 'Fecha de facturacion' para no cambiar la granularidad)
keys = ["Referencia", "Credito", "Status facturacion", "Tipo de comision", "Fecha de cobro"]

# Agregamos Monto y “pegamos” Fecha de facturacion (mínima no nula del grupo)
resultado = (
    df.groupby(keys, dropna=False, as_index=False)
      .agg(
          Monto=("Monto_num", "sum"),
          **{"Fecha de facturacion": ("Fecha de facturacion", "min")}
      )
      .sort_values(["Referencia", "Fecha de cobro"])
      .reset_index(drop=True)
)

# Orden opcional
resultado = resultado.sort_values(["Referencia", "Fecha de cobro"]).reset_index(drop=True)

print(f"Resultado: {resultado.shape}")
display(resultado.head(10))

Resultado: (843914, 7)

,Referencia,Credito,Status facturacion,Tipo de comision,Fecha de cobro,Monto,Fecha de facturacion
0,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-06-30,602031.000000,2025-06-26
1,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-07-31,627346.000000,2025-06-26
2,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,2025-08-31,227237.000000,2025-08-05
3,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-08-31,3852.000000,2025-06-26
4,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,2025-09-30,227237.000000,2025-09-03
5,1000018033,false,COBRO_PARCIAL_INCOBRABLE,MENSUALIDAD_COLOMBIA,2025-10-31,54606.000000,2025-10-06
6,1000046281,false,COBRO_PARCIAL_INCOBRABLE,INSCRIPCION_COLOMBIA,2024-05-31,392457.000000,2024-05-03
7,1000120635,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2024-02-29,251033.000000,2024-02-13
8,1000120635,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2024-04-30,249418.016954,2024-02-13
9,1000120635,false,COBRADO,MENSUALIDAD_COLOMBIA,2024-05-31,140546.000000,2024-04-03

In [16]:
resultado

,Referencia,Credito,Status facturacion,Tipo de comision,Fecha de cobro,Monto,Fecha de facturacion
0,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-06-30,602031.0,2025-06-26
1,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-07-31,627346.0,2025-06-26
2,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,2025-08-31,227237.0,2025-08-05
3,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-08-31,3852.0,2025-06-26
4,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,2025-09-30,227237.0,2025-09-03
...,...,...,...,...,...,...,...
843909,99990,true,COBRADO,LIQUIDACION_COLOMBIA,2021-12-31,1210878.0,2021-12-23
843910,99990,true,COBRADO,MENSUALIDAD_COLOMBIA,2021-12-31,1575770.0,2021-12-23
843911,99990,true,COBRADO,LIQUIDACION_COLOMBIA,2022-07-31,112390.0,2022-07-30
843912,99990,true,COBRADO,LIQUIDACION_COLOMBIA,2022-10-31,692027.0,2022-10-24
843913,Por Cobrar,false,COBRADO,MENSUALIDAD_COLOMBIA,2021-01-31,54798.0,2021-01-06

In [17]:
import pandas as pd

# Asegúrate de que la clave de unión tenga el mismo tipo en ambos DataFrames
resultado['Referencia'] = resultado['Referencia'].astype(str)
rep_sel['Referencia']   = rep_sel['Referencia'].astype(str)

# Hacemos un merge left: se quedan las filas de resultado y se añade la columna 'Fecha de Inicio'
resultado = resultado.merge(
    rep_sel[['Referencia', 'Fecha de Inicio']],
    on='Referencia',
    how='left'
)

In [18]:
import pandas as pd
import numpy as np

# =========================
# 0) Normalización y utilidades
# =========================
def _norm_ref_base(s: pd.Series) -> pd.Series:
    """Referencia base: quita espacios, '.0' final y sufijos '-n'."""
    s = s.astype(str).str.strip()
    s = s.str.replace(r'\.0$', '', regex=True)    # 12345.0 -> 12345
    s = s.str.replace(r'-\d+$', '', regex=True)   # quita -1, -2, ...
    return s

def _is_empty(x: pd.Series) -> pd.Series:
    return x.isna() | (x.astype(str).str.strip() == '')

# =========================
# 1) Copias y claves base
# =========================
res = resultado.copy()
src = rep_sel.copy()

# Normalizar clave
res['__ref_base__'] = _norm_ref_base(res['Referencia'])
src['__ref_base__'] = _norm_ref_base(src['Referencia'])

# Fechas
res['Fecha de cobro']  = pd.to_datetime(res['Fecha de cobro'],  dayfirst=True, errors='coerce')
res['Fecha de Inicio'] = pd.to_datetime(res['Fecha de Inicio'], dayfirst=True, errors='coerce')
src['Fecha de Inicio'] = pd.to_datetime(src['Fecha de Inicio'], dayfirst=True, errors='coerce')

# =========================
# 2) Columnas a rellenar (mismo nombre en rep_sel y resultado)
# =========================
cols_objetivo = [
    'Fecha de Inicio',
    'Apartado Mensual',
    'Comision Inicial',
    'Comision Mensual',
    'Vehiculo de ahorro',
    'Deuda inicial Fija'
]

# Asegurar que existan en 'res'
for c in cols_objetivo:
    if c not in res.columns:
        res[c] = pd.NA

# =========================
# 3) Separar referencias únicas vs. repetidas en rep_sel
# =========================
dup_mask = src.duplicated('__ref_base__', keep=False)
src_unique = src.loc[~dup_mask].set_index('__ref_base__')
src_dups   = src.loc[dup_mask].copy()

# =========================
# 4) Relleno para referencias ÚNICAS (merge directo por map)
# =========================
for dcol in cols_objetivo:
    if dcol not in src_unique.columns:
        continue
    was_empty = _is_empty(res[dcol])
    res.loc[was_empty, dcol] = res.loc[was_empty, '__ref_base__'].map(src_unique[dcol])

# =========================
# 5) Reglas para referencias REPETIDAS
#    - "old": fila con Fecha de Inicio más antigua
#    - "new": fila con Fecha de Inicio más reciente
#    - En resultado:
#        si Fecha de cobro < FechaInicio_new → usar valores "old"
#        si Fecha de cobro ≥ FechaInicio_new O es NaT → usar valores "new"
#    - Solo rellenamos donde esté vacío
# =========================
if not src_dups.empty:
    # ordenar por fecha
    src_dups = src_dups.sort_values(['__ref_base__', 'Fecha de Inicio'])
    rules = []

    for base, g in src_dups.groupby('__ref_base__', sort=False):
        g = g.dropna(subset=['Fecha de Inicio'])
        if g.empty:
            continue
        row_old = g.iloc[0]   # más antigua
        row_new = g.iloc[-1]  # más reciente
        item = {
            '__ref_base__': base,
            'threshold': row_new['Fecha de Inicio'],  # fecha que separa old/new
        }
        for dcol in cols_objetivo:
            item[f'old:{dcol}'] = row_old.get(dcol, pd.NA)
            item[f'new:{dcol}'] = row_new.get(dcol, pd.NA)
        rules.append(item)

    if rules:
        rules_df = pd.DataFrame(rules).set_index('__ref_base__')

        # Aplicar por referencia
        groups = res.groupby('__ref_base__').groups
        for base, idx_list in groups.items():
            if base not in rules_df.index:
                continue  # esta ref no es repetida en rep_sel
            thr = rules_df.at[base, 'threshold']

            idx = pd.Index(idx_list)
            rows = res.loc[idx]

            # Máscaras por Fecha de cobro
            mask_new = (rows['Fecha de cobro'].notna() & (rows['Fecha de cobro'] >= thr)) | rows['Fecha de cobro'].isna()
            mask_old = rows['Fecha de cobro'].notna() & (rows['Fecha de cobro'] <  thr)

            # Rellenar SOLO vacíos con valores new/old
            for dcol in cols_objetivo:
                # NEW
                was_empty_new = _is_empty(rows.loc[mask_new, dcol])
                if was_empty_new.any():
                    res.loc[idx[mask_new][was_empty_new], dcol] = rules_df.at[base, f'new:{dcol}']
                # OLD
                was_empty_old = _is_empty(rows.loc[mask_old, dcol])
                if was_empty_old.any():
                    res.loc[idx[mask_old][was_empty_old], dcol] = rules_df.at[base, f'old:{dcol}']

# =========================
# 6) Salida final
# =========================
resultado_actualizado = res.drop(columns='__ref_base__').reset_index(drop=True)

# (Opcional) verificar que no cambió el número de filas ni el orden principal
assert len(resultado_actualizado) == len(resultado), "El proceso cambió el número de filas."

print("Relleno completado. Filas:", len(resultado_actualizado))

Relleno completado. Filas: 843914

In [19]:
# Total de referencias únicas en todo el DataFrame
total_referencias = resultado['Referencia'].nunique()

# Filtrar filas con Fecha de Inicio nula
sin_fecha = resultado[resultado['Fecha de Inicio'].isna()]

# Referencias únicas sin Fecha de Inicio
referencias_sin_fecha = sin_fecha['Referencia'].unique()
cantidad_sin_fecha = len(referencias_sin_fecha)

print("Total de referencias únicas en resultado:", total_referencias)
print("Cantidad de referencias únicas sin Fecha de Inicio:", cantidad_sin_fecha)
print("Listado de referencias sin Fecha de Inicio:")
print(referencias_sin_fecha)

Total de referencias únicas en resultado: 121235
Cantidad de referencias únicas sin Fecha de Inicio: 61994
Listado de referencias sin Fecha de Inicio:
['100017' '100076' '100086' ... '99961' '99990' 'Por Cobrar']

In [20]:
import os, json, pandas as pd, gspread

# ========= 1) Obtener el secreto =========
def _get_secret(name: str):
    # Intenta primero en Colab
    try:
        from google.colab import userdata as _ud
        val = _ud.get(name)
        if val:
            return val
    except Exception:
        pass
    # Luego en entorno normal (GitHub / local)
    return os.environ.get(name)

creds_json = _get_secret("MI_JSON")
if not creds_json:
    raise RuntimeError(
        "No encontré el secreto 'MI_JSON'. "
        "En Colab, agrégalo en 'Secretos'. "
        "En GitHub/local, define la variable de entorno MI_JSON con el JSON del Service Account."
    )

creds_dict = json.loads(creds_json)

# ========= 2) Autorizar gspread =========
scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]
gc = gspread.service_account_from_dict(creds_dict, scopes=scopes)

# ========= 3) Abrir la hoja por ID y gid =========
sheet_id = "1JB8m0xVAJYhP2e57DcIe-MujFEXIbyRO2x76C30-9Pk"
gid      = 655613670  # pestaña específica

ws = gc.open_by_key(sheet_id).get_worksheet_by_id(gid)

# ========= 4) Traer todos los valores y recortar a primeras 23 columnas =========
valores = ws.get_all_values()
df = pd.DataFrame(valores).iloc[:, :23]   # solo columnas 0–22

# ========= 5) Mostrar muestra y shape =========
print(df.head())
print(f"Filas: {df.shape[0]}  |  Columnas: {df.shape[1]}")

         0                1                              2   \
0  ID Berex  # de Referencia             Correo electronico
1    565565       1067969495         luis.mestrac@gmail.com
2    568776       3023181377      miguelpaipa2735@gmail.com
3    570328       1073681400          eliza18cs@hotmail.com
4    571153       3022640512  rafaelhernandez2527@gmail.com

                  3           4        5             6                7   \
0  Tipo de Documento      Cédula  Celular  Deuda Cierre  SUMA(N3:N17932)
1                 CC  1067969495            130.981.450        130981450
2                 CC    80132159             16.109.100         16109100
3                 CC  1073681400              9.705.150          9705150
4                 CC  1007680232             37.398.113         37398113

         8                9   ...       13        14      15  \
0  Apartado  Fecha de Inicio  ...  C Powwi  Vehículo  Status
1   1539412         3/8/2025  ...    10504   SKANDIA  Activo
2    329334         2/8/2025  ...    10504     POWWI  Activo
3    288694         3/8/2025  ...    10504   SKANDIA  Activo
4    590113         3/8/2025  ...    10504     COINK  Activo

                    16             17                     18  \
0  Fecha de Graduación  Fecha de Baja  Fecha de Reactivacíón
1
2
3
4

                               19                  20                21     22
0                         Empresa   Mensualidad Total   Tipo de Cliente      x
1  RESUELVE TU DEUDA COLOMBIA SAS             534.430                15  2.025
2  RESUELVE TU DEUDA COLOMBIA SAS              91.050                13  2.025
3  RESUELVE TU DEUDA COLOMBIA SAS              59.030                13  2.025
4  RESUELVE TU DEUDA COLOMBIA SAS             197.495                13  2.025

[5 rows x 23 columns]
Filas: 109801  |  Columnas: 23

In [21]:
# Usar la primera fila como encabezados y eliminarla del cuerpo
df.columns = df.iloc[0]           # asigna la fila 0 como nombres de columnas
df = df.drop(index=0).reset_index(drop=True)  # quita la fila 0 y rein

In [22]:
import pandas as pd
import numpy as np

# =========================
# 0) Normalización y utilidades
# =========================
def _norm_ref_base(s: pd.Series) -> pd.Series:
    s = s.astype(str).str.strip()
    s = s.str.replace(r'\.0$', '', regex=True)    # 12345.0 -> 12345
    s = s.str.replace(r'-\d+$', '', regex=True)   # quita -1, -2, ...
    return s

def _is_empty(x: pd.Series) -> pd.Series:
    return x.isna() | (x.astype(str).str.strip() == '')

# =========================
# 1) Copias y claves base
# =========================
res = resultado_actualizado.copy()
src = df.copy()

res['__ref_base__'] = _norm_ref_base(res['Referencia'])
src['__ref_base__'] = _norm_ref_base(src['# de Referencia'])

# Asegurar fechas
res['Fecha de cobro']  = pd.to_datetime(res['Fecha de cobro'],  dayfirst=True, errors='coerce')
res['Fecha de Inicio'] = pd.to_datetime(res['Fecha de Inicio'], dayfirst=True, errors='coerce')
src['Fecha de Inicio'] = pd.to_datetime(src['Fecha de Inicio'], dayfirst=True, errors='coerce')

# Columnas origen (en df) y destino (en resultado_actualizado)
col_mensualidad = ' Mensualidad Total' if ' Mensualidad Total' in src.columns else 'Mensualidad Total'
pairs = [
    ('Fecha de Inicio',    'Fecha de Inicio'),
    ('Apartado Mensual',   'Apartado'),
    ('Comision Mensual',   col_mensualidad),
    ('Vehiculo de ahorro', 'Vehículo'),
    ('Deuda inicial Fija', 'Deuda Cierre'),
]

# Asegurar que columnas destino existan en res
for dcol, _ in pairs:
    if dcol not in res.columns:
        res[dcol] = pd.NA

# =========================
# 2) Separar referencias únicas vs repetidas en df
# =========================
dup_mask = src.duplicated('__ref_base__', keep=False)
src_unique = src.loc[~dup_mask].set_index('__ref_base__')
src_dups   = src.loc[dup_mask].copy()

# =========================
# 3) Relleno para referencias ÚNICAS (merge directo por map)
# =========================
for dcol, scol in pairs:
    if scol not in src_unique.columns:
        continue
    was_empty = _is_empty(res[dcol])
    res.loc[was_empty, dcol] = res.loc[was_empty, '__ref_base__'].map(src_unique[scol])

# =========================
# 4) Reglas para referencias REPETIDAS:
#    - "old": fila con Fecha de Inicio más antigua
#    - "new": fila con Fecha de Inicio más reciente
# =========================
if not src_dups.empty:
    # ordenar por fecha
    src_dups = src_dups.sort_values(['__ref_base__', 'Fecha de Inicio'])
    rules = []

    for base, g in src_dups.groupby('__ref_base__', sort=False):
        g = g.dropna(subset=['Fecha de Inicio'])
        if g.empty:
            continue
        row_old = g.iloc[0]
        row_new = g.iloc[-1]
        item = {
            '__ref_base__': base,
            'threshold': row_new['Fecha de Inicio'],  # fecha que separa old/new
        }
        # guardar valores old/new para cada destino
        for dcol, scol in pairs:
            item[f'old:{dcol}'] = row_old.get(scol, pd.NA)
            item[f'new:{dcol}'] = row_new.get(scol, pd.NA)
        rules.append(item)

    if rules:
        rules_df = pd.DataFrame(rules).set_index('__ref_base__')

        # aplicar por referencia
        for base, sub_idx in res.groupby('__ref_base__').groups.items():
            if base not in rules_df.index:
                continue  # esta ref no es repetida en df
            thr = rules_df.at[base, 'threshold']

            # filas de esta ref en res
            idx = pd.Index(sub_idx)
            rows = res.loc[idx]

            # submáscaras por fecha de cobro
            mask_new = (rows['Fecha de cobro'].notna() & (rows['Fecha de cobro'] >= thr)) | rows['Fecha de cobro'].isna()
            mask_old = rows['Fecha de cobro'].notna() & (rows['Fecha de cobro'] <  thr)

            # rellenar SOLO vacíos con valores new/old
            for dcol, _ in pairs:
                # NEW
                was_empty_new = _is_empty(rows.loc[mask_new, dcol])
                if was_empty_new.any():
                    res.loc[idx[mask_new][was_empty_new], dcol] = rules_df.at[base, f'new:{dcol}']
                # OLD
                was_empty_old = _is_empty(rows.loc[mask_old, dcol])
                if was_empty_old.any():
                    res.loc[idx[mask_old][was_empty_old], dcol] = rules_df.at[base, f'old:{dcol}']

# =========================
# 5) Salida final
# =========================
resultado_actualizado = res.drop(columns='__ref_base__').reset_index(drop=True)
print("Relleno completado. Filas:", len(resultado_actualizado))

Relleno completado. Filas: 843914

In [23]:
import pandas as pd

# 1️⃣ Filtrar filas: mantener solo las referencias que sean enteramente numéricas
#    isdigit() devuelve True solo si la cadena son dígitos del 0-9
resultado_actualizado = resultado_actualizado[resultado_actualizado['Referencia'].astype(str).str.isdigit()].copy()

# 2️⃣ Eliminar la columna 'Comision Inicial' si existe
if 'Comision Inicial' in resultado_actualizado.columns:
    resultado_actualizado.drop(columns='Comision Inicial', inplace=True)

# Verificación
print("Filas restantes:", resultado_actualizado.shape[0])
print("Columnas actuales:", list(resultado_actualizado.columns))

Filas restantes: 842978
Columnas actuales: ['Referencia', 'Credito', 'Status facturacion', 'Tipo de comision', 'Fecha de cobro', 'Monto', 'Fecha de facturacion', 'Fecha de Inicio', 'Apartado Mensual', 'Comision Mensual', 'Vehiculo de ahorro', 'Deuda inicial Fija']

In [24]:
import pandas as pd
import numpy as np

def to_number_mixed_dot(series: pd.Series) -> pd.Series:
    # Forzamos string dtype robusto
    s = series.astype("string").str.strip()

    # Negativos con paréntesis
    s = s.str.replace(r'^\((.*)\)$', r'-\1', regex=True)

    # Notación científica -> directo
    m_sci = s.str.contains(r'^[+-]?\d*\.?\d+(e|E)[+-]?\d+$', na=False)
    out = pd.Series(np.nan, index=s.index, dtype="float64")
    if m_sci.any():
        out.loc[m_sci] = pd.to_numeric(s[m_sci], errors="coerce")

    # Resto: limpiamos todo lo que no sea dígito, punto o signo; quitamos comas (miles)
    t = s[~m_sci].copy()
    t = t.str.replace(r'[^0-9\.\-]', '', regex=True)   # quita símbolos, espacios, etc.
    t = t.str.replace(',', '', regex=False)            # (por si había)

    # Contar puntos
    dot_count = t.str.count(r'\.')

    # >1 punto => todos son miles (quitar todos los puntos)
    idx_multi = dot_count > 1
    if idx_multi.any():
        out.loc[idx_multi.index[idx_multi]] = pd.to_numeric(
            t[idx_multi].str.replace('.', '', regex=False),
            errors='coerce'
        )

    # 1 punto => decidir por nº de dígitos antes del punto
    idx_one = dot_count == 1
    if idx_one.any():
        one = t[idx_one]
        # parte antes del punto sin signo
        before = one.str.split('.', n=1).str[0].str.replace('-', '', regex=False)
        m_dec = before.str.len().astype("Int64") >= 4  # ≥4 dígitos antes => decimal
        if m_dec.any():
            out.loc[one.index[m_dec]] = pd.to_numeric(one[m_dec], errors='coerce')
        if (~m_dec).any():
            out.loc[one.index[~m_dec]] = pd.to_numeric(
                one[~m_dec].str.replace('.', '', regex=False),
                errors='coerce'
            )

    # 0 puntos => número directo
    idx_zero = dot_count == 0
    if idx_zero.any():
        out.loc[t.index[idx_zero]] = pd.to_numeric(t[idx_zero], errors='coerce')

    return out

# Aplica a tus columnas
cols_a_convertir = ['Apartado Mensual', 'Comision Mensual', 'Deuda inicial Fija']
for c in cols_a_convertir:
    if c in resultado_actualizado.columns:
        resultado_actualizado[c] = to_number_mixed_dot(resultado_actualizado[c])

# Verificación rápida
print(resultado_actualizado[cols_a_convertir].dtypes)
print(resultado_actualizado[cols_a_convertir].head(10))

/tmp/ipykernel_35719/705226084.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  m_sci = s.str.contains(r'^[+-]?\d*\.?\d+(e|E)[+-]?\d+$', na=False)
/tmp/ipykernel_35719/705226084.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  m_sci = s.str.contains(r'^[+-]?\d*\.?\d+(e|E)[+-]?\d+$', na=False)
/tmp/ipykernel_35719/705226084.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  m_sci = s.str.contains(r'^[+-]?\d*\.?\d+(e|E)[+-]?\d+$', na=False)

Apartado Mensual      float64
Comision Mensual      float64
Deuda inicial Fija    float64
dtype: object
   Apartado Mensual  Comision Mensual  Deuda inicial Fija
0         611362.66         227237.00          43346600.0
1         611362.66         227237.00          43346600.0
2         611362.66         227237.00          43346600.0
3         611362.66         227237.00          43346600.0
4         611362.66         227237.00          43346600.0
5         611362.66         227237.00          43346600.0
6         389316.26          67611.23          11421445.0
7         246716.02          70272.50          11953700.0
8         246716.02          70272.50          11953700.0
9         246716.02          70272.50          11953700.0

In [25]:
# Total de referencias únicas en todo el DataFrame
total_referencias = resultado_actualizado['Referencia'].nunique()

# Filtrar filas con Fecha de Inicio nula
sin_fecha = resultado_actualizado[resultado_actualizado['Fecha de Inicio'].isna()]

# Referencias únicas sin Fecha de Inicio
referencias_sin_fecha = sin_fecha['Referencia'].unique()
cantidad_sin_fecha = len(referencias_sin_fecha)

print("Total de referencias únicas en resultado:", total_referencias)
print("Cantidad de referencias únicas sin Fecha de Inicio:", cantidad_sin_fecha)
print("Listado de referencias sin Fecha de Inicio:")
print(referencias_sin_fecha)

Total de referencias únicas en resultado: 121093
Cantidad de referencias únicas sin Fecha de Inicio: 16837
Listado de referencias sin Fecha de Inicio:
['117857' '3000004' '3000006' ... '3174152116' '46827' '52310468']

In [26]:
import pandas as pd
import re

# Aseguramos que sea string
ref_series = df['# de Referencia'].astype(str)

# 1️⃣ Patrón: al menos un dígito y al menos un carácter que NO sea dígito
mask = ref_series.str.contains(r'\d') & ref_series.str.contains(r'\D')

df_con_caracteres = df[mask].copy()

print(df_con_caracteres.head())
print("Total de referencias con números + otros caracteres:", df_con_caracteres.shape[0])

0     ID Berex # de Referencia              Correo electronico  \
13930   491756    3106441511-1       LLERENAPADILLAG@GMAIL.COM
15027   500231    3222169837-1    UYABANANDRES130910@GMAIL.COM
15725   486992    3005732101-1    LINDA.DUARTE1995@OUTLOOK.COM
16723   493041    3132075879-1  VALENTINASANCHEZ1107@GMAIL.COM
16993   492082      79369661-1           ANDRES0106V@YAHOO.COM

0     Tipo de Documento      Cédula     Celular Deuda Cierre SUMA(N3:N17932)  \
13930                CC    45371576  3106441511    7.345.800         7345800
15027                CC  1057548267  3222169837   20.189.500        20189500
15725                CC  1065819988  3005732101   13.502.500        13502500
16723                CC  1073714622  3132075879    7.981.050         7981050
16993                CC    79369661  3142071231   14.635.348        14635348

0     Apartado Fecha de Inicio  ... C Powwi Vehículo    Status  \
13930   179317       2/10/2024  ...   10504    COINK  Baja 2xC
15027   404634      30/10/2024  ...   10504    POWWI  Baja 2xC
15725   328766       16/9/2024  ...   10504    COINK  Baja 2xC
16723   165801       30/9/2024  ...   10504    COINK  Baja 2xC
16993   288562       30/9/2024  ...   10504  SKANDIA  Baja 2xC

0     Fecha de Graduación Fecha de Baja Fecha de Reactivacíón  \
13930                         31/1/2025
15027                         31/1/2025
15725                        31/12/2024
16723                        31/12/2024
16993                        31/12/2024

0                             Empresa  Mensualidad Total  Tipo de Cliente  \
13930  RESUELVE TU DEUDA COLOMBIA SAS             47.233               13
15027  RESUELVE TU DEUDA COLOMBIA SAS            111.452               13
15725  RESUELVE TU DEUDA COLOMBIA SAS             78.017               13
16723  RESUELVE TU DEUDA COLOMBIA SAS             50.409               13
16993  RESUELVE TU DEUDA COLOMBIA SAS             83.681               13

0          x
13930  2.024
15027  2.024
15725  2.024
16723  2.024
16993  2.024

[5 rows x 23 columns]
Total de referencias con números + otros caracteres: 1214

In [27]:
# Total de referencias únicas en todo el DataFrame
total_referencias = resultado_actualizado['Referencia'].nunique()

# Filtrar filas con Fecha de Inicio nula
sin_fecha = resultado_actualizado[resultado_actualizado['Fecha de Inicio'].isna()]

# Referencias únicas sin Fecha de Inicio
referencias_sin_fecha = sin_fecha['Referencia'].unique()
cantidad_sin_fecha = len(referencias_sin_fecha)

print("Total de referencias únicas en resultado:", total_referencias)
print("Cantidad de referencias únicas sin Fecha de Inicio:", cantidad_sin_fecha)
print("Listado de referencias sin Fecha de Inicio:")
print(referencias_sin_fecha)

Total de referencias únicas en resultado: 121093
Cantidad de referencias únicas sin Fecha de Inicio: 16837
Listado de referencias sin Fecha de Inicio:
['117857' '3000004' '3000006' ... '3174152116' '46827' '52310468']

In [28]:
# Asegúrate de que 'Fecha de Inicio' sea de tipo datetime
resultado_actualizado['Fecha de Inicio'] = pd.to_datetime(resultado_actualizado['Fecha de Inicio'], errors='coerce')

# Crear la nueva columna 'Mes_Año' con el formato "MM-YYYY"
resultado_actualizado['Mes_Año'] = resultado_actualizado['Fecha de Inicio'].dt.strftime('%m-%Y')

In [29]:
import numpy as np
import pandas as pd

# Asegúrate de que ambas columnas sean datetime
resultado_actualizado['Fecha de Inicio'] = pd.to_datetime(resultado_actualizado['Fecha de Inicio'], errors='coerce')
resultado_actualizado['Fecha de cobro'] = pd.to_datetime(resultado_actualizado['Fecha de cobro'], errors='coerce')

# Calcular diferencia en meses entre Fecha de Inicio y Fecha de cobro
# (año de cobro - año de inicio)*12 + (mes de cobro - mes de inicio)
resultado_actualizado['Mes_Cobro'] = (
    (resultado_actualizado['Fecha de cobro'].dt.year - resultado_actualizado['Fecha de Inicio'].dt.year) * 12 +
    (resultado_actualizado['Fecha de cobro'].dt.month - resultado_actualizado['Fecha de Inicio'].dt.month)
)

# Si Fecha de Inicio o Fecha de cobro son nulos, poner NaN
resultado_actualizado['Mes_Cobro'] = np.where(
    resultado_actualizado['Fecha de Inicio'].notna() & resultado_actualizado['Fecha de cobro'].notna(),
    resultado_actualizado['Mes_Cobro'],
    np.nan
)

In [30]:
# Filtrar manteniendo solo los Mes_Cobro no nulos y >= 0
resultado_actualizado = resultado_actualizado[
    resultado_actualizado['Mes_Cobro'].notna() & (resultado_actualizado['Mes_Cobro'] >= 0)
].reset_index(drop=True)

In [31]:
resultado_actualizado

,Referencia,Credito,Status facturacion,Tipo de comision,Fecha de cobro,Monto,Fecha de facturacion,Fecha de Inicio,Apartado Mensual,Comision Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro
0,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-06-30,602031.0,2025-06-26,2025-06-16,611362.66,227237.0,SKANDIA,43346600.0,06-2025,0.0
1,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-07-31,627346.0,2025-06-26,2025-06-16,611362.66,227237.0,SKANDIA,43346600.0,06-2025,1.0
2,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,2025-08-31,227237.0,2025-08-05,2025-06-16,611362.66,227237.0,SKANDIA,43346600.0,06-2025,2.0
3,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-08-31,3852.0,2025-06-26,2025-06-16,611362.66,227237.0,SKANDIA,43346600.0,06-2025,2.0
4,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,2025-09-30,227237.0,2025-09-03,2025-06-16,611362.66,227237.0,SKANDIA,43346600.0,06-2025,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822447,99990,false,COBRADO,MENSUALIDAD_COLOMBIA,2021-12-31,157577.0,2021-12-05,2021-06-16,519374.00,157577.0,A&V,29414564.0,06-2021,6.0
822448,99990,true,COBRADO,LIQUIDACION_COLOMBIA,2021-12-31,1210878.0,2021-12-23,2021-06-16,519374.00,157577.0,A&V,29414564.0,06-2021,6.0
822449,99990,true,COBRADO,MENSUALIDAD_COLOMBIA,2021-12-31,1575770.0,2021-12-23,2021-06-16,519374.00,157577.0,A&V,29414564.0,06-2021,6.0
822450,99990,true,COBRADO,LIQUIDACION_COLOMBIA,2022-07-31,112390.0,2022-07-30,2021-06-16,519374.00,157577.0,A&V,29414564.0,06-2021,13.0
822451,99990,true,COBRADO,LIQUIDACION_COLOMBIA,2022-10-31,692027.0,2022-10-24,2021-06-16,519374.00,157577.0,A&V,29414564.0,06-2021,16.0

#Arreglo

In [32]:
rep_sel = rep_sel[["Referencia", "Apartado Mensual", "Deuda Resuelve", "Deuda inicial Fija"]]

In [33]:
df = df[["# de Referencia", "Apartado", "Deuda Cierre"]]

In [34]:
# Elimina puntos y convierte a float
df["Deuda Cierre"] = (
    df["Deuda Cierre"]
      .astype(str)           # asegúrate de que sea string
      .str.replace('.', '', regex=False)  # quita separadores de miles
      .str.replace(',', '.', regex=False) # por si acaso hay comas decimales
      .astype(float)
)

In [35]:
# 1️⃣ Primero, asegúrate de que las columnas clave tengan el mismo tipo
df['# de Referencia'] = df['# de Referencia'].astype(str)
resultado_actualizado['Referencia'] = resultado_actualizado['Referencia'].astype(str)

# 2️⃣ Crea un diccionario de referencia→Deuda Cierre para hacer el mapeo rápido
mapa_cierre = df.set_index('# de Referencia')['Deuda Cierre']

# 3️⃣ Reemplaza solo donde Deuda inicial Fija < 5,000,000
mask = resultado_actualizado['Deuda inicial Fija'] < 5_000_000
resultado_actualizado.loc[mask, 'Deuda inicial Fija'] = (
    resultado_actualizado.loc[mask, 'Referencia'].map(mapa_cierre)
)

# 4️⃣ (opcional) verifica
print(resultado_actualizado['Deuda inicial Fija'].head())

0    43346600.0
1    43346600.0
2    43346600.0
3    43346600.0
4    43346600.0
Name: Deuda inicial Fija, dtype: float64

In [36]:
df["Deuda Cierre"] = pd.to_numeric(df["Deuda Cierre"], errors="coerce")
resultado_actualizado["Deuda inicial Fija"] = pd.to_numeric(
    resultado_actualizado["Deuda inicial Fija"], errors="coerce"
)

# Unimos por referencia
merged = resultado_actualizado.merge(
    df[["# de Referencia", "Deuda Cierre"]],
    left_on="Referencia",
    right_on="# de Referencia",
    how="left",
    suffixes=("", "_df")
)

# Creamos máscara donde la diferencia sea mayor a 50,000
mask = (merged["Deuda Cierre"].notna() &
        (merged["Deuda Cierre"] - merged["Deuda inicial Fija"]).abs() > 50000)

# Reemplazamos en resultado_actualizado solo para esas referencias
resultado_actualizado.loc[mask, "Deuda inicial Fija"] = merged.loc[mask, "Deuda Cierre"]

In [37]:
columnas_eliminar = ['Comision Mensual']

resultado_actualizado = resultado_actualizado.drop(columns=columnas_eliminar)

In [38]:
resultado_actualizado

,Referencia,Credito,Status facturacion,Tipo de comision,Fecha de cobro,Monto,Fecha de facturacion,Fecha de Inicio,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro
0,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-06-30,602031.0,2025-06-26,2025-06-16,611362.66,SKANDIA,43346600.0,06-2025,0.0
1,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-07-31,627346.0,2025-06-26,2025-06-16,611362.66,SKANDIA,43346600.0,06-2025,1.0
2,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,2025-08-31,227237.0,2025-08-05,2025-06-16,611362.66,SKANDIA,43346600.0,06-2025,2.0
3,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-08-31,3852.0,2025-06-26,2025-06-16,611362.66,SKANDIA,43346600.0,06-2025,2.0
4,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,2025-09-30,227237.0,2025-09-03,2025-06-16,611362.66,SKANDIA,43346600.0,06-2025,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
822447,99990,false,COBRADO,MENSUALIDAD_COLOMBIA,2021-12-31,157577.0,2021-12-05,2021-06-16,519374.00,A&V,29414564.0,06-2021,6.0
822448,99990,true,COBRADO,LIQUIDACION_COLOMBIA,2021-12-31,1210878.0,2021-12-23,2021-06-16,519374.00,A&V,29414564.0,06-2021,6.0
822449,99990,true,COBRADO,MENSUALIDAD_COLOMBIA,2021-12-31,1575770.0,2021-12-23,2021-06-16,519374.00,A&V,29414564.0,06-2021,6.0
822450,99990,true,COBRADO,LIQUIDACION_COLOMBIA,2022-07-31,112390.0,2022-07-30,2021-06-16,519374.00,A&V,29414564.0,06-2021,13.0
822451,99990,true,COBRADO,LIQUIDACION_COLOMBIA,2022-10-31,692027.0,2022-10-24,2021-06-16,519374.00,A&V,29414564.0,06-2021,16.0

In [39]:
resultado_actualizado.loc[
    resultado_actualizado['Referencia'] == '3223168906',
    'Apartado Mensual'
] = resultado_actualizado.loc[
    resultado_actualizado['Referencia'] == '3223168906',
    'Apartado Mensual'
] / 100

#Dealer

In [40]:
import os, json, base64, pandas as pd, gspread
from google.oauth2.service_account import Credentials

# ========= 1) Cargar secreto MI_JSON (Colab o entorno normal) =========
def _get_secret(name: str):
    try:
        from google.colab import userdata as _ud
        val = _ud.get(name)
        if val:
            return val
    except Exception:
        pass
    return os.environ.get(name)

raw_json = _get_secret("MI_JSON")
if not raw_json:
    raise RuntimeError(
        "No se encontró el secreto MI_JSON. "
        "En Colab, agrégalo en 'Secretos'. "
        "En GitHub/local, define la variable de entorno MI_JSON con el JSON del Service Account."
    )

# Puede venir en texto plano o Base64
try:
    sa_info = json.loads(raw_json)
except json.JSONDecodeError:
    sa_info = json.loads(base64.b64decode(raw_json).decode("utf-8"))

# ========= 2) Autorizar gspread =========
creds = Credentials.from_service_account_info(
    sa_info,
    scopes=[
        "https://www.googleapis.com/auth/spreadsheets.readonly",
        "https://www.googleapis.com/auth/drive.readonly",
    ],
)
client = gspread.authorize(creds)

# ========= 3) Abrir la hoja de cálculo y pestaña específica =========
spreadsheet_id = "1v7Bg9ss5ZTAIA5J4DJ8THmSMHs5ILrUeLgBZkE3NCMs"
worksheet_gid  = 678352849  # GID de la pestaña
ws = client.open_by_key(spreadsheet_id).get_worksheet_by_id(worksheet_gid)

# ========= 4) Convertir a DataFrame =========
toco_dealer = pd.DataFrame(ws.get_all_records())

print("Filas:", toco_dealer.shape[0], "| Columnas:", toco_dealer.shape[1])
print(toco_dealer.head())

Filas: 60579 | Columnas: 7
  bank_reference      cm       am        dbt       vh      status  \
0     1022326170  227157   677057   45095800  skandia      active
1     3225135389   96342   406453   17613700     ding      active
2     3052262962  705139  1868744  118510700    powwi      active
3     3203213452           205442    6072000           deprecated
4     3023625900   66068   233008   11253600     ding      active

  fecha_de_inicio
0      2025-05-27
1      2024-09-10
2      2020-08-10
3
4      2025-03-31

In [41]:
# Seleccionar y renombrar columnas
toco_dealer = toco_dealer[['am', 'dbt', 'bank_reference']].rename(
    columns={
        'am': 'Apartado Mensual',
        'dbt': 'Deuda inicial Fija',
        'bank_reference': 'Referencia'
    }
)

# Verificar resultado
print(toco_dealer.shape)

(60579, 3)

In [42]:
# Apartado Mensual
toco_dealer['Apartado Mensual'] = (
    toco_dealer['Apartado Mensual']
    .astype(str)
    .str.replace(r'[^\d.]', '', regex=True)
    .replace('', pd.NA)                   # Reemplaza cadenas vacías por NA
    .pipe(pd.to_numeric, errors='coerce') # Convierte a float y deja NaN donde no pueda
)

# Deuda inicial Fija
toco_dealer['Deuda inicial Fija'] = (
    toco_dealer['Deuda inicial Fija']
    .astype(str)
    .str.replace(r'[^\d.]', '', regex=True)
    .replace('', pd.NA)
    .pipe(pd.to_numeric, errors='coerce')
)

# Comprobar tipos y algunos valores
print(toco_dealer.dtypes)

Apartado Mensual        int64
Deuda inicial Fija    float64
Referencia             object
dtype: object

In [43]:
# Asegurarnos de que las columnas sean numéricas
resultado_actualizado['Apartado Mensual']   = pd.to_numeric(resultado_actualizado['Apartado Mensual'], errors='coerce')
resultado_actualizado['Deuda inicial Fija'] = pd.to_numeric(resultado_actualizado['Deuda inicial Fija'], errors='coerce')

# Calcular AM/DB (con protección ante divisiones por 0 o NaN)
resultado_actualizado['AM/DB'] = (
    resultado_actualizado['Apartado Mensual'] /
    resultado_actualizado['Deuda inicial Fija']
)

In [44]:
resultado_actualizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 822452 entries, 0 to 822451
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Referencia            822452 non-null  object
 1   Credito               822452 non-null  object
 2   Status facturacion    822452 non-null  object
 3   Tipo de comision      822452 non-null  object
 4   Fecha de cobro        822452 non-null  datetime64[ns]
 5   Monto                 822452 non-null  float64
 6   Fecha de facturacion  822452 non-null  datetime64[ns]
 7   Fecha de Inicio       822452 non-null  datetime64[ns]
 8   Apartado Mensual      822452 non-null  float64
 9   Vehiculo de ahorro    822452 non-null  object
 10  Deuda inicial Fija    822450 non-null  float64
 11  Mes_Año               822452 non-null  object
 12  Mes_Cobro             822452 non-null  float64
 13  AM/DB                 822450 non-null  float64
dtypes: datetime64[ns](3), float64(5), object(6)
memory usage: 87.8+ MB

In [45]:
import numpy as np

# 1) Asegurar tipos para la clave
resultado_actualizado['Referencia'] = resultado_actualizado['Referencia'].astype(str)
toco_dealer['Referencia']           = toco_dealer['Referencia'].astype(str)

# 2) Máscara de filas a considerar
mask = (
    (resultado_actualizado['AM/DB'] > 0.045) |
    (resultado_actualizado['AM/DB'] < 0.0099)
)

# 3) Mapas desde toco_dealer
map_apartado = dict(zip(toco_dealer['Referencia'], toco_dealer['Apartado Mensual']))
map_deuda    = dict(zip(toco_dealer['Referencia'], toco_dealer['Deuda inicial Fija']))

# 4) Series mapeadas (pueden venir con NaN si no existe la referencia)
mapped_apartado = resultado_actualizado['Referencia'].map(map_apartado)
mapped_deuda    = resultado_actualizado['Referencia'].map(map_deuda)

# 5) Reemplazar solo si: (mask) y (hay valor mapeado no nulo)
resultado_actualizado['Apartado Mensual'] = np.where(
    mask & mapped_apartado.notna(),
    mapped_apartado,
    resultado_actualizado['Apartado Mensual']
)

resultado_actualizado['Deuda inicial Fija'] = np.where(
    mask & mapped_deuda.notna(),
    mapped_deuda,
    resultado_actualizado['Deuda inicial Fija']
)

In [46]:
# Lista de años permitidos
anios_validos = [str(a) for a in range(2021, 2031)]

# Filtrar resultado_actualizado
resultado_actualizado = resultado_actualizado[
    resultado_actualizado['Mes_Año'].str[-4:].isin(anios_validos)
].copy()

In [47]:
import numpy as np

# Calcular cuartiles e IQR
Q1 = resultado_actualizado['AM/DB'].quantile(0.25)
Q3 = resultado_actualizado['AM/DB'].quantile(0.75)
IQR = Q3 - Q1

# Límites para definir atípicos
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Crear la columna: 1 si es atípico, 0 si no
resultado_actualizado['AM/DB_outlier'] = np.where(
    (resultado_actualizado['AM/DB'] < lower_bound) |
    (resultado_actualizado['AM/DB'] > upper_bound),
    1,   # Es atípico
    0    # No es atípico
)

In [48]:
import numpy as np
import pandas as pd

# Definir los límites en fracción (no en %)
bins = [ -np.inf, 0.015, 0.0199, 0.025, np.inf ]
labels = [
    "< 1.5%",
    "1.5% – 1.99%",
    "2% – 2.5%",
    "> 2.5%"
]

# Crear la columna de rango
resultado_actualizado['Rango_AM_DB'] = pd.cut(
    resultado_actualizado['AM/DB'],
    bins=bins,
    labels=labels,
    right=True,   # incluye el límite superior
    include_lowest=True
)

In [49]:
import numpy as np
import pandas as pd

# Límites en pesos (ajusta si tu columna ya está en millones)
bins_deuda   = [-np.inf, 35_000_000, 60_000_000, 100_000_000, np.inf]
labels_deuda = [
    "< 35 M",
    "35 – 60 M",
    "60 – 100 M",
    "> 100 M"
]

# Crear la nueva columna de rango
resultado_actualizado["Rango_de_deuda"] = pd.cut(
    resultado_actualizado["Deuda inicial Fija"],
    bins=bins_deuda,
    labels=labels_deuda,
    right=True,
    include_lowest=True
)

In [50]:
# Asegurarnos de que las columnas sean numéricas
resultado_actualizado['Apartado Mensual']   = pd.to_numeric(resultado_actualizado['Apartado Mensual'], errors='coerce')
resultado_actualizado['Deuda inicial Fija'] = pd.to_numeric(resultado_actualizado['Deuda inicial Fija'], errors='coerce')

# Calcular AM/DB (con protección ante divisiones por 0 o NaN)
resultado_actualizado['AM/DB'] = (
    resultado_actualizado['Apartado Mensual'] /
    resultado_actualizado['Deuda inicial Fija']
)

In [51]:
resultado_actualizado

,Referencia,Credito,Status facturacion,Tipo de comision,Fecha de cobro,Monto,Fecha de facturacion,Fecha de Inicio,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro,AM/DB,AM/DB_outlier,Rango_AM_DB,Rango_de_deuda
0,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-06-30,602031.0,2025-06-26,2025-06-16,611362.66,SKANDIA,43346600.0,06-2025,0.0,0.014104,0,< 1.5%,35 – 60 M
1,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-07-31,627346.0,2025-06-26,2025-06-16,611362.66,SKANDIA,43346600.0,06-2025,1.0,0.014104,0,< 1.5%,35 – 60 M
2,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,2025-08-31,227237.0,2025-08-05,2025-06-16,611362.66,SKANDIA,43346600.0,06-2025,2.0,0.014104,0,< 1.5%,35 – 60 M
3,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,2025-08-31,3852.0,2025-06-26,2025-06-16,611362.66,SKANDIA,43346600.0,06-2025,2.0,0.014104,0,< 1.5%,35 – 60 M
4,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,2025-09-30,227237.0,2025-09-03,2025-06-16,611362.66,SKANDIA,43346600.0,06-2025,3.0,0.014104,0,< 1.5%,35 – 60 M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822447,99990,false,COBRADO,MENSUALIDAD_COLOMBIA,2021-12-31,157577.0,2021-12-05,2021-06-16,519374.00,A&V,29414564.0,06-2021,6.0,0.017657,0,1.5% – 1.99%,< 35 M
822448,99990,true,COBRADO,LIQUIDACION_COLOMBIA,2021-12-31,1210878.0,2021-12-23,2021-06-16,519374.00,A&V,29414564.0,06-2021,6.0,0.017657,0,1.5% – 1.99%,< 35 M
822449,99990,true,COBRADO,MENSUALIDAD_COLOMBIA,2021-12-31,1575770.0,2021-12-23,2021-06-16,519374.00,A&V,29414564.0,06-2021,6.0,0.017657,0,1.5% – 1.99%,< 35 M
822450,99990,true,COBRADO,LIQUIDACION_COLOMBIA,2022-07-31,112390.0,2022-07-30,2021-06-16,519374.00,A&V,29414564.0,06-2021,13.0,0.017657,0,1.5% – 1.99%,< 35 M
822451,99990,true,COBRADO,LIQUIDACION_COLOMBIA,2022-10-31,692027.0,2022-10-24,2021-06-16,519374.00,A&V,29414564.0,06-2021,16.0,0.017657,0,1.5% – 1.99%,< 35 M

In [52]:
import pandas as pd

df = resultado_actualizado.copy()

# 0) Quitar AM/DB si existe
for c in df.columns:
    if c.strip().lower().replace(" ", "") in {"am/db", "amdb"}:
        df = df.drop(columns=[c])
        break

# 1) Detectar nombre real de la columna Mes_Año / Mes_Ano
mes_anio_col = None
for cand in ["Mes_Año", "Mes_Ano", "Mes_AÑO", "Mes_AÑO", "Mes_Ano "]:
    if cand in df.columns:
        mes_anio_col = cand
        break
if mes_anio_col is None:
    raise KeyError("No encontré la columna 'Mes_Año' / 'Mes_Ano' en el DataFrame.")

# 2) Llaves de agrupación
keys = ["Credito", "Tipo de comision", "Vehiculo de ahorro", mes_anio_col, "Mes_Cobro"]

# 3) Verificación mínima de columnas requeridas
for k in keys + ["Referencia", "Monto"]:
    if k not in df.columns:
        raise KeyError(f"Falta la columna requerida: {k}")

# 4) Agregación final: sum(Monto) y conteo de referencias únicas
df_final = (
    df.groupby(keys, dropna=False)
      .agg(
          Monto=("Monto", "sum"),
          Referencias_unicas=("Referencia", pd.Series.nunique),
      )
      .reset_index()
)

# (Opcional) reordenar columnas
df_final = df_final[keys + ["Referencias_unicas", "Monto"]]

print("Filas originales:", len(df))
print("Filas consolidadas:", len(df_final))
df_final.head()

Filas originales: 735247
Filas consolidadas: 14821

,Credito,Tipo de comision,Vehiculo de ahorro,Mes_Año,Mes_Cobro,Referencias_unicas,Monto
0,false,INSCRIPCION_COLOMBIA,A&V,01-2021,0.0,626,263814136.0
1,false,INSCRIPCION_COLOMBIA,A&V,01-2021,1.0,999,248805465.0
2,false,INSCRIPCION_COLOMBIA,A&V,01-2021,2.0,535,3819623.0
3,false,INSCRIPCION_COLOMBIA,A&V,01-2021,3.0,63,440980.0
4,false,INSCRIPCION_COLOMBIA,A&V,01-2021,4.0,17,85820.0

In [53]:
df_final

,Credito,Tipo de comision,Vehiculo de ahorro,Mes_Año,Mes_Cobro,Referencias_unicas,Monto
0,false,INSCRIPCION_COLOMBIA,A&V,01-2021,0.0,626,263814136.0
1,false,INSCRIPCION_COLOMBIA,A&V,01-2021,1.0,999,248805465.0
2,false,INSCRIPCION_COLOMBIA,A&V,01-2021,2.0,535,3819623.0
3,false,INSCRIPCION_COLOMBIA,A&V,01-2021,3.0,63,440980.0
4,false,INSCRIPCION_COLOMBIA,A&V,01-2021,4.0,17,85820.0
...,...,...,...,...,...,...,...
14816,true,MENSUALIDAD_COLOMBIA,powwi,05-2022,7.0,3,3667968.0
14817,true,MENSUALIDAD_COLOMBIA,powwi,05-2022,8.0,1,520536.0
14818,true,MENSUALIDAD_COLOMBIA,powwi,05-2022,13.0,1,639864.0
14819,true,MENSUALIDAD_COLOMBIA,powwi,06-2022,7.0,1,818595.0
14820,true,MENSUALIDAD_COLOMBIA,powwi,07-2022,9.0,1,1920618.0

In [54]:
# Columnas que queremos conservar
cols = [
    "Referencia",
    "Mes_Año",
    "Apartado Mensual",
    "Deuda inicial Fija",
    "AM/DB",
    "Rango_AM_DB",
    "Rango_de_deuda"
]

# Crear el nuevo DataFrame solo con esas columnas
subset_df = resultado_actualizado[cols].copy()

# Verificamos
print("Filas:", len(subset_df))

Filas: 735247

In [55]:
# Elimina filas duplicadas conservando la primera aparición
subset_df = subset_df.drop_duplicates().reset_index(drop=True)

In [56]:
# 1️⃣ Ver si hay referencias duplicadas (True/False)
hay_repetidas = subset_df['Referencia'].duplicated().any()
print("¿Hay referencias repetidas?:", hay_repetidas)

# 2️⃣ Contar cuántas referencias están repetidas
num_repetidas = subset_df['Referencia'].duplicated().sum()
print("Cantidad de referencias repetidas:", num_repetidas)

# 3️⃣ Ver exactamente cuáles se repiten (con su número de apariciones)
repetidas = (
    subset_df['Referencia']
    .value_counts()
    .loc[lambda x: x > 1]
)
print("Referencias que se repiten y cuántas veces:\n", repetidas)

¿Hay referencias repetidas?: True
Cantidad de referencias repetidas: 86
Referencias que se repiten y cuántas veces:
 Referencia
3185794248    2
3164589419    2
3014611750    2
3508766881    2
3168908141    2
             ..
3104138087    2
3142560493    2
3058163159    2
3168346824    2
3162854008    2
Name: count, Length: 86, dtype: int64

In [57]:
import pandas as pd
import re

# Copia de trabajo
tmp = subset_df.copy()

# Detectar la columna Mes_Año (acepta variantes comunes)
mes_candidates = [c for c in tmp.columns
                  if re.sub(r'[\s_]', '', c).lower() in {'mesaño','mesano'}]
if not mes_candidates:
    raise KeyError("No encontré la columna 'Mes_Año' / 'Mes_Ano'.")
MES_COL = mes_candidates[0]

# Asegurar tipos numéricos (por si vienen como texto con símbolos)
tmp['Apartado Mensual']   = pd.to_numeric(tmp['Apartado Mensual'], errors='coerce')
tmp['Deuda inicial Fija'] = pd.to_numeric(tmp['Deuda inicial Fija'], errors='coerce')

# Agrupar por Mes_Año:
# - sumar Apartado Mensual y Deuda inicial Fija
# - contar referencias únicas
resumen_mes = (
    tmp.groupby(MES_COL, dropna=False)
       .agg({
           'Apartado Mensual': 'sum',
           'Deuda inicial Fija': 'sum',
           'Referencia': pd.Series.nunique
       })
       .rename(columns={'Referencia': 'Referencias_unicas'})
       .reset_index()
)

# Orden opcional de columnas
resumen_mes = resumen_mes[[MES_COL, 'Referencias_unicas', 'Apartado Mensual', 'Deuda inicial Fija']]

resumen_mes.head()

   Mes_Año  Referencias_unicas  Apartado Mensual  Deuda inicial Fija
0  01-2021                1481      7.299968e+08        3.957323e+10
1  01-2022                1379      6.963389e+08        4.070490e+10
2  01-2023                2257      1.253803e+09        7.816693e+10
3  01-2024                1612      9.140737e+08        5.689286e+10
4  01-2025                1641      9.269089e+08        5.391285e+10

In [58]:
resumen_mes

    Mes_Año  Referencias_unicas  Apartado Mensual  Deuda inicial Fija
0   01-2021                1481      7.299968e+08        3.957323e+10
1   01-2022                1379      6.963389e+08        4.070490e+10
2   01-2023                2257      1.253803e+09        7.816693e+10
3   01-2024                1612      9.140737e+08        5.689286e+10
4   01-2025                1641      9.269089e+08        5.391285e+10
..      ...                 ...               ...                 ...
59  12-2021                1005      4.562571e+08        2.561048e+10
60  12-2022                1711      8.665948e+08        5.158227e+10
61  12-2023                 987      5.297835e+08        3.223207e+10
62  12-2024                1147      6.549565e+08        3.897045e+10
63  12-2025                 670      4.195379e+08        2.635223e+10

[64 rows x 4 columns]

In [59]:
subset_df

,Referencia,Mes_Año,Apartado Mensual,Deuda inicial Fija,AM/DB,Rango_AM_DB,Rango_de_deuda
0,1000018033,06-2025,611362.66,43346600.0,0.014104,< 1.5%,35 – 60 M
1,1000046281,04-2024,389316.26,11421445.0,0.034086,> 2.5%,< 35 M
2,1000120635,02-2024,246716.02,11953700.0,0.020639,2% – 2.5%,< 35 M
3,1000136703,06-2024,272569.17,12278900.0,0.022198,2% – 2.5%,< 35 M
4,1000137024,10-2024,498600.59,25457250.0,0.019586,1.5% – 1.99%,< 35 M
...,...,...,...,...,...,...,...
91849,99942,06-2021,529899.00,31496350.0,0.016824,1.5% – 1.99%,< 35 M
91850,99944,06-2021,436679.00,22096800.0,0.019762,1.5% – 1.99%,< 35 M
91851,99961,06-2021,383931.00,17062100.0,0.022502,2% – 2.5%,< 35 M
91852,99969,06-2021,611331.56,37778650.0,0.016182,1.5% – 1.99%,35 – 60 M
91853,99990,06-2021,519374.00,29414564.0,0.017657,1.5% – 1.99%,< 35 M

In [60]:
# Asegura que Monto sea numérico y la fecha en datetime
resultado_actualizado["Monto"] = pd.to_numeric(resultado_actualizado["Monto"], errors="coerce")
resultado_actualizado["Fecha de cobro"] = pd.to_datetime(resultado_actualizado["Fecha de cobro"], dayfirst=True, errors="coerce")

# Filtra por año 2025 y tipo de comisión
filtro = (
    (resultado_actualizado["Fecha de cobro"].dt.year == 2025) &
    (resultado_actualizado["Tipo de comision"] == "LIQUIDACION_COLOMBIA")
)

# Suma de Monto
total_monto_2025 = resultado_actualizado.loc[filtro, "Monto"].sum()
print(total_monto_2025)

12942222173.565105

In [61]:
Columnas_eliminar = ['Fecha de cobro', 'Fecha de Inicio']
resultado_actualizado = resultado_actualizado.drop(columns=Columnas_eliminar)

In [62]:
resultado_actualizado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro,AM/DB,AM/DB_outlier,Rango_AM_DB,Rango_de_deuda
0,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,602031.0,2025-06-26,611362.66,SKANDIA,43346600.0,06-2025,0.0,0.014104,0,< 1.5%,35 – 60 M
1,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,627346.0,2025-06-26,611362.66,SKANDIA,43346600.0,06-2025,1.0,0.014104,0,< 1.5%,35 – 60 M
2,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,227237.0,2025-08-05,611362.66,SKANDIA,43346600.0,06-2025,2.0,0.014104,0,< 1.5%,35 – 60 M
3,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,3852.0,2025-06-26,611362.66,SKANDIA,43346600.0,06-2025,2.0,0.014104,0,< 1.5%,35 – 60 M
4,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,227237.0,2025-09-03,611362.66,SKANDIA,43346600.0,06-2025,3.0,0.014104,0,< 1.5%,35 – 60 M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822447,99990,false,COBRADO,MENSUALIDAD_COLOMBIA,157577.0,2021-12-05,519374.00,A&V,29414564.0,06-2021,6.0,0.017657,0,1.5% – 1.99%,< 35 M
822448,99990,true,COBRADO,LIQUIDACION_COLOMBIA,1210878.0,2021-12-23,519374.00,A&V,29414564.0,06-2021,6.0,0.017657,0,1.5% – 1.99%,< 35 M
822449,99990,true,COBRADO,MENSUALIDAD_COLOMBIA,1575770.0,2021-12-23,519374.00,A&V,29414564.0,06-2021,6.0,0.017657,0,1.5% – 1.99%,< 35 M
822450,99990,true,COBRADO,LIQUIDACION_COLOMBIA,112390.0,2022-07-30,519374.00,A&V,29414564.0,06-2021,13.0,0.017657,0,1.5% – 1.99%,< 35 M
822451,99990,true,COBRADO,LIQUIDACION_COLOMBIA,692027.0,2022-10-24,519374.00,A&V,29414564.0,06-2021,16.0,0.017657,0,1.5% – 1.99%,< 35 M

#Traemos berex

In [63]:
import pandas as pd
import re

# =========================
# Config
# =========================
SPREADSHEET_ID = "13Vf32LzRI2V95dIUqfevzm-ZmsDR3d17UTre_7XJ-UU"
GID_ESTRUCTURADO = 0
GID_TRADICIONAL  = 285942728
FECHA_COLS_EXACTAS = ["payment_date", "Originado"]


# =========================
# Utilidades
# =========================
def load_sheet_csv(spreadsheet_id: str, gid: int) -> pd.DataFrame:
    """Lee una hoja pública de Google Sheets exportándola como CSV."""
    url = f"https://docs.google.com/spreadsheets/d/{spreadsheet_id}/export?format=csv&gid={gid}"
    df = pd.read_csv(url, dtype=str)
    df.columns = [c.strip() for c in df.columns]
    return df


def get_ref_col(df: pd.DataFrame) -> str:
    """Detecta el nombre de la columna 'reference'."""
    candidatos = ['reference', 'Referencia', 'REFERENCIA', 'Reference', 'referencia']
    for c in candidatos:
        if c in df.columns:
            return c
    for c in df.columns:
        if 'refer' in c.lower():
            return c
    raise KeyError("No se encontró la columna de referencia en el DataFrame.")


def normaliza_ref(s: str) -> str:
    """
    Normaliza referencias para comparación:
    - '42871.0' o '00042871.000' -> '42871'
    - '00042871' -> '42871'
    - quita separadores y pone mayúsculas para alfanuméricos.
    """
    if pd.isna(s):
        return None

    raw = str(s).strip()
    up  = raw.upper()

    try:

        fv = float(raw.replace(",", ""))
        if fv.is_integer():
            return str(int(fv))
    except Exception:
        pass

    if raw.isdigit():
        try:
            return str(int(raw))
        except Exception:
            return raw.lstrip("0") or "0"

    t = re.sub(r"[^0-9A-Z]", "", up)
    if t.isdigit():
        try:
            t = str(int(t))
        except Exception:
            pass
    return t or None


def to_datetime_ddmmyyyy(series: pd.Series) -> pd.Series:
    """Convierte una serie a datetime asumiendo formato día/mes/año."""
    return pd.to_datetime(series.astype(str).str.strip(), dayfirst=True, errors="coerce")


# =========================
# Cargar datos
# =========================
df_estructurado = load_sheet_csv(SPREADSHEET_ID, GID_ESTRUCTURADO)
df_tradicional  = load_sheet_csv(SPREADSHEET_ID, GID_TRADICIONAL)

ref_est  = get_ref_col(df_estructurado)
ref_trad = get_ref_col(df_tradicional)

df_estructurado[ref_est] = df_estructurado[ref_est].apply(normaliza_ref)
df_tradicional[ref_trad] = df_tradicional[ref_trad].apply(normaliza_ref)

# =========================
# Diagnóstico ANTES del filtrado
# =========================
refs_validas = set(df_estructurado[ref_est].dropna().unique())
trad_refs   = set(df_tradicional[ref_trad].dropna().unique())
inter = refs_validas & trad_refs

print(f"Refs únicas Estructurado: {len(refs_validas)}")
print(f"Refs únicas Tradicional : {len(trad_refs)}")
print(f"Intersección            : {len(inter)}")

no_match = list(trad_refs - refs_validas)[:10]
if no_match:
    print("Ejemplos Tradicional NO presentes en Estructurado:", no_match)

# =========================
# Conversión de fechas (dd/mm/YYYY) en ambos dataframes
# =========================
for col in FECHA_COLS_EXACTAS:
    if col in df_estructurado.columns:
        df_estructurado[col] = to_datetime_ddmmyyyy(df_estructurado[col])
    if col in df_tradicional.columns:
        df_tradicional[col] = to_datetime_ddmmyyyy(df_tradicional[col])

# =========================
# Marcar origen
# =========================
df_estructurado['Estructurado'] = 1
df_tradicional['Estructurado']  = 0

# =========================
# Filtrado Tradicional (regla de negocio):
# - Mantener TODO lo de Estructurado (gid=0).
# - De Tradicional (gid=285942728), conservar solo filas cuya reference está en Estructurado.
# =========================
df_trad_filtrado = df_tradicional[df_tradicional[ref_trad].isin(refs_validas)].copy()

# =========================
# Alinear nombre de columna de referencia y concatenar
# =========================
if ref_trad != ref_est:
    df_trad_filtrado.rename(columns={ref_trad: ref_est}, inplace=True)

berex_estruct = pd.concat([df_estructurado, df_trad_filtrado], ignore_index=True)

# =========================
# Chequeos finales
# =========================
eliminadas = len(df_tradicional) - len(df_trad_filtrado)
print(f"Filas eliminadas de 'Tradicional con Estructurado': {eliminadas}")
print("Filas finales berex_estruct:", len(berex_estruct))
print("Referencias únicas finales:", berex_estruct[ref_est].nunique())
print("Columnas convertidas a fecha:", [c for c in FECHA_COLS_EXACTAS if c in berex_estruct.columns])

Refs únicas Estructurado: 8776
Refs únicas Tradicional : 3089
Intersección            : 3087
Ejemplos Tradicional NO presentes en Estructurado: ['52144289', '28787344']
Filas eliminadas de 'Tradicional con Estructurado': 10
Filas finales berex_estruct: 66600
Referencias únicas finales: 8776
Columnas convertidas a fecha: ['payment_date', 'Originado']

In [64]:
berex_estruct

,reference,id,amount,bank,debt_id,destination,payment_date,payment_number,requester,Originado,Unnamed: 10,Estructurado
0,3183831101,3295,350824,Alkosto,544721,commission,2021-01-12,2,Natalia Valentina Castro Jimenez,2021-01-12,318383110144208,1
1,3183831101,3294,500000,Alkosto,544721,bank,2021-01-12,1,Natalia Valentina Castro Jimenez,2021-01-12,318383110144208,1
2,3183831101,3296,436000,Alkosto,544721,bank,2021-02-19,3,Natalia Valentina Castro Jimenez,2021-01-12,318383110144208,1
3,3183831101,3297,436000,Alkosto,544721,bank,2021-03-19,4,Natalia Valentina Castro Jimenez,2021-01-12,318383110144208,1
4,3504389669,3941,131198,Alkosto,510212,commission,2021-01-30,2,No Asignado,2021-01-30,350438966944226,1
...,...,...,...,...,...,...,...,...,...,...,...,...
66595,3016008038,NaN,86272,Banco de Bogota,1809482,commission,2026-02-27,NaN,Angie Lizeth Cubides Neira,2026-02-27,NaN,0
66596,3184455376,NaN,1122,Sistecredito,1688617,commission,2026-02-27,NaN,Dayana Isabel Ojito Ortiz,2026-02-27,NaN,0
66597,3184455376,NaN,1372,Sistecredito,1688618,commission,2026-02-27,NaN,Dayana Isabel Ojito Ortiz,2026-02-27,NaN,0
66598,3112460819,NaN,15000000,Bancolombia,1671350,bank,2026-03-02,NaN,Vivian Caterin Rodriguez Verano,2026-03-02,NaN,0
66599,3112460819,NaN,1680672,Bancolombia,1671350,commission,2026-03-02,NaN,Vivian Caterin Rodriguez Verano,2026-03-02,NaN,0

In [65]:
referencia_buscada = '3017388628'

resultado = berex_estruct[berex_estruct['reference'] == referencia_buscada]

resultado

,reference,id,amount,bank,debt_id,destination,payment_date,payment_number,requester,Originado,Unnamed: 10,Estructurado
50799,3017388628,"270,630",270000,BBVA,1552649,commission,2025-12-05,3,Hector Elian Lacera Vega,2025-10-31,301738862845961,1
50800,3017388628,"270,631",270000,BBVA,1552649,commission,2026-01-05,4,Hector Elian Lacera Vega,2025-10-31,301738862845961,1
50801,3017388628,"270,632",270000,BBVA,1552649,commission,2026-02-05,5,Hector Elian Lacera Vega,2025-10-31,301738862845961,1
50802,3017388628,"270,633",270000,BBVA,1552649,commission,2026-03-05,6,Hector Elian Lacera Vega,2025-10-31,301738862845961,1
50803,3017388628,"270,634",270000,BBVA,1552649,commission,2026-04-05,7,Hector Elian Lacera Vega,2025-10-31,301738862845961,1
50822,3017388628,"270,629",374042,BBVA,1552649,commission,2025-10-31,2,Hector Elian Lacera Vega,2025-10-31,301738862845961,1
50909,3017388628,"270,628",2480000,BBVA,1552649,bank,2025-10-31,1,Hector Elian Lacera Vega,2025-10-31,301738862845961,1

In [66]:
referencia_buscada = '3508191585'

resultado = resultado_actualizado[resultado_actualizado['Referencia'] == referencia_buscada]

resultado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro,AM/DB,AM/DB_outlier,Rango_AM_DB,Rango_de_deuda
758877,3508191585,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,428363.0,2025-05-29,422543.09,DING,16529250.0,05-2025,0.0,0.025563,0,> 2.5%,< 35 M
758878,3508191585,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,1713.0,2025-05-29,422543.09,DING,16529250.0,05-2025,1.0,0.025563,0,> 2.5%,< 35 M
758879,3508191585,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,425514.0,2025-05-29,422543.09,DING,16529250.0,05-2025,2.0,0.025563,0,> 2.5%,< 35 M
758880,3508191585,false,COBRO_PARCIAL_COBRADO,MENSUALIDAD_COLOMBIA,93150.0,2025-07-03,422543.09,DING,16529250.0,05-2025,2.0,0.025563,0,> 2.5%,< 35 M
758881,3508191585,false,COBRADO,MENSUALIDAD_COLOMBIA,93150.0,2025-08-05,422543.09,DING,16529250.0,05-2025,3.0,0.025563,0,> 2.5%,< 35 M
758882,3508191585,false,COBRADO,LIQUIDACION_COLOMBIA,18360.0,2025-09-25,422543.09,DING,16529250.0,05-2025,4.0,0.025563,0,> 2.5%,< 35 M
758883,3508191585,false,COBRADO,MENSUALIDAD_COLOMBIA,93150.0,2025-09-03,422543.09,DING,16529250.0,05-2025,4.0,0.025563,0,> 2.5%,< 35 M
758884,3508191585,false,COBRADO,MENSUALIDAD_COLOMBIA,93150.0,2025-10-06,422543.09,DING,16529250.0,05-2025,5.0,0.025563,0,> 2.5%,< 35 M
758885,3508191585,false,COBRADO,MENSUALIDAD_COLOMBIA,93150.0,2025-11-07,422543.09,DING,16529250.0,05-2025,6.0,0.025563,0,> 2.5%,< 35 M
758886,3508191585,false,COBRO_PARCIAL,MENSUALIDAD_COLOMBIA,65264.0,2025-12-01,422543.09,DING,16529250.0,05-2025,6.0,0.025563,0,> 2.5%,< 35 M

In [67]:
berex_estruct.info()
resultado_actualizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66600 entries, 0 to 66599
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reference       66600 non-null  object
 1   id              54525 non-null  object
 2   amount          66554 non-null  object
 3   bank            66600 non-null  object
 4   debt_id         66600 non-null  object
 5   destination     66600 non-null  object
 6   payment_date    66600 non-null  datetime64[ns]
 7   payment_number  66540 non-null  object
 8   requester       66600 non-null  object
 9   Originado       66600 non-null  datetime64[ns]
 10  Unnamed: 10     54588 non-null  object
 11  Estructurado    66600 non-null  int64
dtypes: datetime64[ns](2), int64(1), object(9)
memory usage: 6.1+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 735247 entries, 0 to 822451
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Referencia            735247 non-null  object
 1   Credito               735247 non-null  object
 2   Status facturacion    735247 non-null  object
 3   Tipo de comision      735247 non-null  object
 4   Monto                 735247 non-null  float64
 5   Fecha de facturacion  735247 non-null  datetime64[ns]
 6   Apartado Mensual      735247 non-null  float64
 7   Vehiculo de ahorro    735247 non-null  object
 8   Deuda inicial Fija    735245 non-null  float64
 9   Mes_Año               735247 non-null  object
 10  Mes_Cobro             735247 non-null  float64
 11  AM/DB                 735245 non-null  float64
 12  AM/DB_outlier         735247 non-null  int64
 13  Rango_AM_DB           735245 non-null  category
 14  Rango_de_deuda        735245 non-null  category
dtypes: category(2), datetime64[ns](1), float64(5), int64(1), object(6)
memory usage: 79.9+ MB

In [68]:
# 1) Obtener las referencias únicas de berex_estruct (columna 'reference')
refs_berex = (
    berex_estruct['reference']
    .dropna()                # por si hay NaN
    .astype(str)             # homogeneizar tipo
    .str.strip()             # quitar espacios
    .unique()
)

# (opcional) si quieres mejor rendimiento para el filtro:
refs_berex_set = set(refs_berex)

# 2) Filtrar resultado_actualizado dejando solo filas cuya 'Referencia' esté en las únicas de berex
resultado_filtrado = resultado_actualizado[
    resultado_actualizado['Referencia'].astype(str).str.strip().isin(refs_berex_set)
].copy()

# 3) (opcional) verificación rápida
print(f"Refs únicas en berex_estruct: {len(refs_berex_set):,}")
print(f"Filas resultantes en resultado_filtrado: {len(resultado_filtrado):,}")
print(resultado_filtrado['Referencia'].nunique(), "referencias únicas en el filtrado")

Refs únicas en berex_estruct: 8,776
Filas resultantes en resultado_filtrado: 146,224
8309 referencias únicas en el filtrado

In [69]:
resultado_filtrado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro,AM/DB,AM/DB_outlier,Rango_AM_DB,Rango_de_deuda
73,1000185400,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,523175.000000,2025-03-04,520791.11,SKANDIA,22718600.0,02-2025,1.0,0.022924,0,2% – 2.5%,< 35 M
74,1000185400,false,COBRADO,MENSUALIDAD_COLOMBIA,124097.000000,2025-04-04,520791.11,SKANDIA,22718600.0,02-2025,2.0,0.022924,0,2% – 2.5%,< 35 M
75,1000185400,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,528911.000000,2025-03-04,520791.11,SKANDIA,22718600.0,02-2025,2.0,0.022924,0,2% – 2.5%,< 35 M
76,1000185400,false,COBRADO,MENSUALIDAD_COLOMBIA,124097.000000,2025-05-06,520791.11,SKANDIA,22718600.0,02-2025,3.0,0.022924,0,2% – 2.5%,< 35 M
77,1000185400,false,COBRADO,LIQUIDACION_COLOMBIA,19405.915966,2025-06-20,520791.11,SKANDIA,22718600.0,02-2025,4.0,0.022924,0,2% – 2.5%,< 35 M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822306,9957452,false,COBRADO,MENSUALIDAD_COLOMBIA,74016.000000,2025-04-04,465252.24,SKANDIA,14306600.0,07-2023,21.0,0.032520,0,> 2.5%,< 35 M
822307,9957452,false,COBRADO,MENSUALIDAD_COLOMBIA,74016.000000,2025-05-06,465252.24,SKANDIA,14306600.0,07-2023,22.0,0.032520,0,> 2.5%,< 35 M
822308,9957452,false,COBRADO,MENSUALIDAD_COLOMBIA,10504.000000,2025-06-05,465252.24,SKANDIA,14306600.0,07-2023,23.0,0.032520,0,> 2.5%,< 35 M
822309,9957452,false,COBRADO,MENSUALIDAD_COLOMBIA,10504.000000,2025-07-03,465252.24,SKANDIA,14306600.0,07-2023,24.0,0.032520,0,> 2.5%,< 35 M
822310,9957452,false,COBRADO,MENSUALIDAD_COLOMBIA,10504.000000,2025-11-07,465252.24,SKANDIA,14306600.0,07-2023,28.0,0.032520,0,> 2.5%,< 35 M

In [70]:
referencia_buscada = '3017388628'

resultado = resultado_filtrado[resultado_filtrado['Referencia'] == referencia_buscada]

resultado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro,AM/DB,AM/DB_outlier,Rango_AM_DB,Rango_de_deuda
124407,3017388628,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,345204.000000,2024-07-03,340014.7,POWWI,12138500.0,06-2024,1.0,0.028011,0,> 2.5%,< 35 M
124408,3017388628,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,345329.000000,2024-07-03,340014.7,POWWI,12138500.0,06-2024,2.0,0.028011,0,> 2.5%,< 35 M
124409,3017388628,false,COBRO_PARCIAL_COBRADO,MENSUALIDAD_COLOMBIA,8289.000000,2024-08-06,340014.7,POWWI,12138500.0,06-2024,2.0,0.028011,0,> 2.5%,< 35 M
124410,3017388628,false,COBRADO,MENSUALIDAD_COLOMBIA,71197.000000,2024-09-05,340014.7,POWWI,12138500.0,06-2024,3.0,0.028011,0,> 2.5%,< 35 M
124411,3017388628,false,COBRO_PARCIAL_COBRADO,MENSUALIDAD_COLOMBIA,62908.000000,2024-08-06,340014.7,POWWI,12138500.0,06-2024,3.0,0.028011,0,> 2.5%,< 35 M
124412,3017388628,false,COBRADO,MENSUALIDAD_COLOMBIA,71197.000000,2024-10-04,340014.7,POWWI,12138500.0,06-2024,4.0,0.028011,0,> 2.5%,< 35 M
124413,3017388628,false,COBRADO,MENSUALIDAD_COLOMBIA,71197.000000,2024-11-06,340014.7,POWWI,12138500.0,06-2024,5.0,0.028011,0,> 2.5%,< 35 M
124414,3017388628,false,COBRO_PARCIAL_COBRADO,MENSUALIDAD_COLOMBIA,71197.000000,2024-12-04,340014.7,POWWI,12138500.0,06-2024,6.0,0.028011,0,> 2.5%,< 35 M
124415,3017388628,false,COBRADO,MENSUALIDAD_COLOMBIA,59058.000000,2025-01-08,340014.7,POWWI,12138500.0,06-2024,7.0,0.028011,0,> 2.5%,< 35 M
124416,3017388628,false,COBRADO,MENSUALIDAD_COLOMBIA,59058.000000,2025-02-06,340014.7,POWWI,12138500.0,06-2024,8.0,0.028011,0,> 2.5%,< 35 M
124417,3017388628,false,COBRADO,MENSUALIDAD_COLOMBIA,59058.000000,2025-03-06,340014.7,POWWI,12138500.0,06-2024,9.0,0.028011,0,> 2.5%,< 35 M
124418,3017388628,false,COBRADO,MENSUALIDAD_COLOMBIA,59058.000000,2025-04-04,340014.7,POWWI,12138500.0,06-2024,10.0,0.028011,0,> 2.5%,< 35 M
124419,3017388628,false,COBRADO,MENSUALIDAD_COLOMBIA,59058.000000,2025-05-06,340014.7,POWWI,12138500.0,06-2024,11.0,0.028011,0,> 2.5%,< 35 M
124420,3017388628,false,COBRADO,MENSUALIDAD_COLOMBIA,62129.000000,2025-06-05,340014.7,POWWI,12138500.0,06-2024,12.0,0.028011,0,> 2.5%,< 35 M
124421,3017388628,false,COBRADO,MENSUALIDAD_COLOMBIA,62129.000000,2025-07-03,340014.7,POWWI,12138500.0,06-2024,13.0,0.028011,0,> 2.5%,< 35 M
124422,3017388628,false,COBRADO,MENSUALIDAD_COLOMBIA,62129.000000,2025-08-05,340014.7,POWWI,12138500.0,06-2024,14.0,0.028011,0,> 2.5%,< 35 M
124423,3017388628,false,COBRADO,MENSUALIDAD_COLOMBIA,62129.000000,2025-09-03,340014.7,POWWI,12138500.0,06-2024,15.0,0.028011,0,> 2.5%,< 35 M
124424,3017388628,false,COBRADO,MENSUALIDAD_COLOMBIA,62129.000000,2025-10-06,340014.7,POWWI,12138500.0,06-2024,16.0,0.028011,0,> 2.5%,< 35 M
124425,3017388628,false,COBRADO,LIQUIDACION_COLOMBIA,314321.218487,2025-11-05,340014.7,POWWI,12138500.0,06-2024,17.0,0.028011,0,> 2.5%,< 35 M
124426,3017388628,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,42828.000000,2025-11-04,340014.7,POWWI,12138500.0,06-2024,17.0,0.028011,0,> 2.5%,< 35 M
124427,3017388628,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,226887.000000,2025-11-04,340014.7,POWWI,12138500.0,06-2024,19.0,0.028011,0,> 2.5%,< 35 M
124428,3017388628,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,226890.000000,2025-11-04,340014.7,POWWI,12138500.0,06-2024,20.0,0.028011,0,> 2.5%,< 35 M
124429,3017388628,false,COBRO_PARCIAL,LIQUIDACION_COLOMBIA,41918.000000,2025-11-04,340014.7,POWWI,12138500.0,06-2024,21.0,0.028011,0,> 2.5%,< 35 M
124430,3017388628,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,410959.000000,2025-11-04,340014.7,POWWI,12138500.0,06-2024,21.0,0.028011,0,> 2.5%,< 35 M
124431,3017388628,false,COBRO_PARCIAL,LIQUIDACION_COLOMBIA,903.000000,2025-11-04,340014.7,POWWI,12138500.0,06-2024,22.0,0.028011,0,> 2.5%,< 35 M

In [71]:
# Normalizamos la columna para evitar problemas de mayúsculas/espacios/NaN
tipo_norm = (
    resultado_filtrado['Tipo de comision']
    .fillna('')
    .astype(str)
    .str.strip()
    .str.upper()
)

# 1) Todo lo que diga LIQUIDACION_COLOMBIA
resultado_liquidacion = resultado_filtrado.loc[
    tipo_norm.eq('LIQUIDACION_COLOMBIA')
].copy()

# 2) Todo lo que diga MENSUALIDAD_COLOMBIA
resultado_mensualidad= resultado_filtrado.loc[
    tipo_norm.eq('MENSUALIDAD_COLOMBIA')
].copy()

# (Opcional) chequeos rápidos
print("LIQUIDACION_COLOMBIA:", len(resultado_liquidacion))
print("MENSUALIDAD_COLOMBIA:", len(resultado_mensualidad))

LIQUIDACION_COLOMBIA: 33040
MENSUALIDAD_COLOMBIA: 96862

In [72]:
import numpy as np
import pandas as pd

# 0) Copia de trabajo y filtro por destination == 'commission'
be = berex_estruct.copy()

dest_norm = be['destination'].fillna('').astype(str).str.strip().str.lower()
be = be.loc[dest_norm.eq('commission')].copy()

# 1) Nos quedamos con las columnas relevantes
cols = ['reference', 'Originado', 'requester', 'bank', 'amount']
be = be[cols].copy()

# 2) Normalización básica
be['reference'] = be['reference'].astype(str).str.strip()
be['requester'] = be['requester'].astype(str).str.strip()
be['bank'] = be['bank'].astype(str).str.strip()

# 3) Limpiar 'amount' (viene como object) -> numérico
#    Quita símbolos comunes, puntos de miles y deja el decimal
be['amount'] = (
    be['amount']
    .astype(str)
    .str.replace(r'[^\d,.\-]', '', regex=True)     # remueve símbolos no numéricos
    .str.replace(r'(?<=\d)\.(?=\d{3}(\D|$))', '', regex=True)  # quita puntos de miles
    .str.replace(',', '.', regex=False)            # coma -> punto decimal
)
be['amount_num'] = pd.to_numeric(be['amount'], errors='coerce')

# 4) (Opcional) Si una fila no tiene 'Originado', no se puede agrupar por fecha -> la descartamos
be = be[~be['Originado'].isna()].copy()

# 5) Función para tomar el "responsable" y "bank" por grupo:
#    - Primero el modo (valor más frecuente)
#    - Si hay empate o no hay modo claro, toma el primer no nulo en el orden original
def pick_label(s: pd.Series):
    s_nonnull = s.dropna()
    if s_nonnull.empty:
        return np.nan
    modes = s_nonnull.mode()
    if not modes.empty:
        return modes.iloc[0]
    return s_nonnull.iloc[0]

# 6) Agregación por (reference, Originado)
df_referencia_fecha = (
    be.groupby(['reference', 'Originado'], as_index=False)
      .agg(
          requester=('requester', pick_label),
          bank=('bank', pick_label),
          amount_promedio=('amount_num', 'mean'),
          amount_total    = ('amount_num', 'sum'),
          n_pagos=('reference', 'size')
      )
)

# 7) Orden opcional
df_referencia_fecha = df_referencia_fecha.sort_values(['reference', 'Originado']).reset_index(drop=True)

# 8) (Opcional) Redondeo del promedio
df_referencia_fecha['amount_promedio'] = df_referencia_fecha['amount_promedio'].round(2)
df_referencia_fecha['amount_total'] = df_referencia_fecha['amount_total'].round(2)

# Chequeo rápido
print(df_referencia_fecha.head())
print(f"Total filas (reference x Originado): {len(df_referencia_fecha):,}")

    reference  Originado                          requester        bank  \
0  1000185400 2025-06-19           Hector Elian Lacera Vega  Rapicredit
1  1000591190 2025-09-11          Steven Mateo Aroca Garzon   Falabella
2      100076 2022-12-23          David Steban Pineda Gallo  Davivienda
3      100076 2023-01-11                        No Asignado  Davivienda
4  1001082965 2024-11-18  Daniel Alejandro Umbarila Bolaños   Compensar

   amount_promedio  amount_total  n_pagos
0          53546.5      107093.0        2
1          76543.5      153087.0        2
2         208809.3      208809.3        1
3         243659.0      487318.0        2
4         410419.0      820838.0        2
Total filas (reference x Originado): 14,490

In [73]:
df_referencia_fecha

,reference,Originado,requester,bank,amount_promedio,amount_total,n_pagos
0,1000185400,2025-06-19,Hector Elian Lacera Vega,Rapicredit,53546.50,107093.00,2
1,1000591190,2025-09-11,Steven Mateo Aroca Garzon,Falabella,76543.50,153087.00,2
2,100076,2022-12-23,David Steban Pineda Gallo,Davivienda,208809.30,208809.30,1
3,100076,2023-01-11,No Asignado,Davivienda,243659.00,487318.00,2
4,1001082965,2024-11-18,Daniel Alejandro Umbarila Bolaños,Compensar,410419.00,820838.00,2
...,...,...,...,...,...,...,...
14485,98702966,2025-01-30,Jana Milena Lopez Buitrago,Bancolombia,1140268.44,18244295.00,16
14486,98709164,2025-08-29,Vivian Caterin Rodriguez Verano,Bancolombia,332080.50,1328322.00,4
14487,99534,2022-02-14,Maria Paula Balaguera Penagos,Scotiabank Colpatria,390861.45,390861.45,1
14488,99534,2022-08-10,Natalia Valentina Castro Jimenez,Colsubsidio,145242.33,435727.00,3
14489,9957452,2024-08-13,Juan Felipe Hurtado Mercado,Bancolombia,475122.50,950245.00,2

In [74]:
df_referencia_fecha["amount_total"] = df_referencia_fecha["amount_total"] / 1.19

In [75]:
be_pab = berex_estruct.copy()
dest_norm2 = be_pab['destination'].fillna('').astype(str).str.strip().str.lower()
be_pab = be_pab.loc[dest_norm2.eq('bank')].copy()

be_pab = be_pab[['reference', 'Originado', 'amount']].copy()
be_pab['reference'] = be_pab['reference'].astype(str).str.strip()

be_pab['amount'] = (
    be_pab['amount'].astype(str)
    .str.replace(r'[^\d,.\-]', '', regex=True)
    .str.replace(r'(?<=\d)\.(?=\d{3}(\D|$))', '', regex=True)
    .str.replace(',', '.', regex=False)
)
be_pab['amount_num'] = pd.to_numeric(be_pab['amount'], errors='coerce')
be_pab = be_pab[~be_pab['Originado'].isna()].copy()

df_pab = (
    be_pab.groupby(['reference', 'Originado'], as_index=False)
    .agg(
        PaB_total=('amount_num', 'sum'),
        n_pagos_PaB=('reference', 'size')
    )
)

df_pab['PaB_total'] = df_pab['PaB_total'].round(2)

# ========= Merge a df_referencia_fecha =========
df_referencia_fecha_pab = df_referencia_fecha.merge(
    df_pab, on=['reference', 'Originado'], how='left'
)

# Si no hay registros 'bank' para ese (reference, Originado) -> 0
df_referencia_fecha_pab['PaB_total'] = df_referencia_fecha_pab['PaB_total'].fillna(0).round(2)
df_referencia_fecha_pab['n_pagos_PaB'] = df_referencia_fecha_pab['n_pagos_PaB'].fillna(0).astype(int)

In [76]:
df_referencia_fecha_pab

,reference,Originado,requester,bank,amount_promedio,amount_total,n_pagos,PaB_total,n_pagos_PaB
0,1000185400,2025-06-19,Hector Elian Lacera Vega,Rapicredit,53546.50,8.999412e+04,2,552839.0,1
1,1000591190,2025-09-11,Steven Mateo Aroca Garzon,Falabella,76543.50,1.286445e+05,2,1930000.0,1
2,100076,2022-12-23,David Steban Pineda Gallo,Davivienda,208809.30,1.754700e+05,1,2942000.0,1
3,100076,2023-01-11,No Asignado,Davivienda,243659.00,4.095109e+05,2,10200000.0,1
4,1001082965,2024-11-18,Daniel Alejandro Umbarila Bolaños,Compensar,410419.00,6.897798e+05,2,1390000.0,1
...,...,...,...,...,...,...,...,...,...
14485,98702966,2025-01-30,Jana Milena Lopez Buitrago,Bancolombia,1140268.44,1.533134e+07,16,8954000.0,3
14486,98709164,2025-08-29,Vivian Caterin Rodriguez Verano,Bancolombia,332080.50,1.116237e+06,4,1800000.0,1
14487,99534,2022-02-14,Maria Paula Balaguera Penagos,Scotiabank Colpatria,390861.45,3.284550e+05,1,1800000.0,1
14488,99534,2022-08-10,Natalia Valentina Castro Jimenez,Colsubsidio,145242.33,3.661571e+05,3,2600000.0,1
14489,9957452,2024-08-13,Juan Felipe Hurtado Mercado,Bancolombia,475122.50,7.985252e+05,2,2800000.0,1

In [77]:
resultado_liquidacion

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro,AM/DB,AM/DB_outlier,Rango_AM_DB,Rango_de_deuda
77,1000185400,false,COBRADO,LIQUIDACION_COLOMBIA,19405.915966,2025-06-20,520791.11,SKANDIA,22718600.0,02-2025,4.0,0.022924,0,2% – 2.5%,< 35 M
79,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,15060.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,4.0,0.022924,0,2% – 2.5%,< 35 M
81,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,55528.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,5.0,0.022924,0,2% – 2.5%,< 35 M
148,1000591190,false,COBRADO,LIQUIDACION_COLOMBIA,342925.000000,2025-04-11,344986.00,SKANDIA,12465987.0,12-2024,4.0,0.027674,0,> 2.5%,< 35 M
154,1000591190,false,COBRADO,LIQUIDACION_COLOMBIA,128644.546218,2025-09-12,344986.00,SKANDIA,12465987.0,12-2024,9.0,0.027674,0,> 2.5%,< 35 M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822273,99534,false,COBRADO,LIQUIDACION_COLOMBIA,328455.000000,2022-02-14,287861.00,A&V,9030750.0,06-2021,8.0,0.031876,0,> 2.5%,< 35 M
822280,99534,false,COBRADO,LIQUIDACION_COLOMBIA,73231.000000,2022-08-10,287861.00,A&V,9030750.0,06-2021,14.0,0.031876,0,> 2.5%,< 35 M
822282,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146463.000000,2022-09-12,287861.00,A&V,9030750.0,06-2021,15.0,0.031876,0,> 2.5%,< 35 M
822284,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146464.000000,2022-09-28,287861.00,A&V,9030750.0,06-2021,16.0,0.031876,0,> 2.5%,< 35 M
822297,9957452,false,COBRADO,LIQUIDACION_COLOMBIA,798525.000000,2024-08-13,465252.24,SKANDIA,14306600.0,07-2023,13.0,0.032520,0,> 2.5%,< 35 M

In [78]:
import pandas as pd
import numpy as np

df = resultado_liquidacion.copy()

# 1) Aseguramos formatos
mes_ano_str = df['Mes_Año'].astype(str).str.strip()

# Si Mes_Cobro viene como 4.0, 5.0, etc. -> entero; NaN -> 0 (puedes cambiar este comportamiento si lo prefieres)
offset_meses = (
    pd.to_numeric(df['Mes_Cobro'], errors='coerce')
      .fillna(0)
      .astype(int)
)

# 2) Convertimos Mes_Año a periodo mensual y sumamos el offset en meses
base_period = pd.to_datetime(mes_ano_str, format='%m-%Y', errors='coerce').dt.to_period('M')

# 3) mes_exacto = primer día del mes (start of month) + offset de meses
df['mes_exacto'] = (base_period + offset_meses).dt.to_timestamp(how='start')

# (Opcional) si deseas asegurarte que sea exactamente día 1 sin hora
df['mes_exacto'] = df['mes_exacto'].dt.normalize()

# Chequeo rápido
print(df[['Mes_Año', 'Mes_Cobro', 'mes_exacto']].head())

     Mes_Año  Mes_Cobro mes_exacto
77   02-2025        4.0 2025-06-01
79   02-2025        4.0 2025-06-01
81   02-2025        5.0 2025-07-01
148  12-2024        4.0 2025-04-01
154  12-2024        9.0 2025-09-01

In [79]:
df

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro,AM/DB,AM/DB_outlier,Rango_AM_DB,Rango_de_deuda,mes_exacto
77,1000185400,false,COBRADO,LIQUIDACION_COLOMBIA,19405.915966,2025-06-20,520791.11,SKANDIA,22718600.0,02-2025,4.0,0.022924,0,2% – 2.5%,< 35 M,2025-06-01
79,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,15060.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,4.0,0.022924,0,2% – 2.5%,< 35 M,2025-06-01
81,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,55528.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,5.0,0.022924,0,2% – 2.5%,< 35 M,2025-07-01
148,1000591190,false,COBRADO,LIQUIDACION_COLOMBIA,342925.000000,2025-04-11,344986.00,SKANDIA,12465987.0,12-2024,4.0,0.027674,0,> 2.5%,< 35 M,2025-04-01
154,1000591190,false,COBRADO,LIQUIDACION_COLOMBIA,128644.546218,2025-09-12,344986.00,SKANDIA,12465987.0,12-2024,9.0,0.027674,0,> 2.5%,< 35 M,2025-09-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822273,99534,false,COBRADO,LIQUIDACION_COLOMBIA,328455.000000,2022-02-14,287861.00,A&V,9030750.0,06-2021,8.0,0.031876,0,> 2.5%,< 35 M,2022-02-01
822280,99534,false,COBRADO,LIQUIDACION_COLOMBIA,73231.000000,2022-08-10,287861.00,A&V,9030750.0,06-2021,14.0,0.031876,0,> 2.5%,< 35 M,2022-08-01
822282,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146463.000000,2022-09-12,287861.00,A&V,9030750.0,06-2021,15.0,0.031876,0,> 2.5%,< 35 M,2022-09-01
822284,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146464.000000,2022-09-28,287861.00,A&V,9030750.0,06-2021,16.0,0.031876,0,> 2.5%,< 35 M,2022-10-01
822297,9957452,false,COBRADO,LIQUIDACION_COLOMBIA,798525.000000,2024-08-13,465252.24,SKANDIA,14306600.0,07-2023,13.0,0.032520,0,> 2.5%,< 35 M,2024-08-01

In [80]:
import pandas as pd
import numpy as np

# 1) Normalizamos llaves para empatar referencias
df = df.copy()
df['__ref_norm'] = df['Referencia'].astype(str).str.strip()

tmp = df_referencia_fecha.copy()
tmp['__ref_norm'] = tmp['reference'].astype(str).str.strip()

# (Recomendado) Asegurar tipos de fecha
df['mes_exacto'] = pd.to_datetime(df['mes_exacto'], errors='coerce')
tmp['Originado']  = pd.to_datetime(tmp['Originado'], errors='coerce')

# 2) Para cada reference, tomar la fecha Originado más antigua
cutoff_por_ref = (
    tmp.loc[~tmp['Originado'].isna(), ['__ref_norm', 'Originado']]
       .groupby('__ref_norm', as_index=True)['Originado']
       .min()
)

# 3) Mapear fecha de corte a df
df['__fecha_corte'] = df['__ref_norm'].map(cutoff_por_ref)

# 4) Filtrar:
#   - Solo referencias que existen en df_referencia_fecha (tienen __fecha_corte no nula)
#   - Comparar por MES-AÑO: mes_exacto_M >= fecha_corte_M  (mismo mes se conserva)
mask_valid = df['__fecha_corte'].notna()

mes_period   = df['mes_exacto'].dt.to_period('M')
corte_period = pd.to_datetime(df['__fecha_corte']).dt.to_period('M')

mask_fecha = mes_period.notna() & corte_period.notna() & (mes_period >= corte_period)

df_filtrado = df.loc[mask_valid & mask_fecha].copy()

# 5) Limpieza columnas auxiliares
df_filtrado.drop(columns=['__ref_norm', '__fecha_corte'], inplace=True)

# (Opcional) Chequeo
print("Filas antes:", len(df))
print("Filas después:", len(df_filtrado))
print("Referencias únicas conservadas:", df_filtrado['Referencia'].nunique())

Filas antes: 33040
Filas después: 32769
Referencias únicas conservadas: 8220

#Merge

In [81]:
df_filtrado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro,AM/DB,AM/DB_outlier,Rango_AM_DB,Rango_de_deuda,mes_exacto
77,1000185400,false,COBRADO,LIQUIDACION_COLOMBIA,19405.915966,2025-06-20,520791.11,SKANDIA,22718600.0,02-2025,4.0,0.022924,0,2% – 2.5%,< 35 M,2025-06-01
79,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,15060.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,4.0,0.022924,0,2% – 2.5%,< 35 M,2025-06-01
81,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,55528.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,5.0,0.022924,0,2% – 2.5%,< 35 M,2025-07-01
154,1000591190,false,COBRADO,LIQUIDACION_COLOMBIA,128644.546218,2025-09-12,344986.00,SKANDIA,12465987.0,12-2024,9.0,0.027674,0,> 2.5%,< 35 M,2025-09-01
156,1000591190,true,COBRADO,LIQUIDACION_COLOMBIA,214365.000000,2025-09-30,344986.00,SKANDIA,12465987.0,12-2024,10.0,0.027674,0,> 2.5%,< 35 M,2025-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822273,99534,false,COBRADO,LIQUIDACION_COLOMBIA,328455.000000,2022-02-14,287861.00,A&V,9030750.0,06-2021,8.0,0.031876,0,> 2.5%,< 35 M,2022-02-01
822280,99534,false,COBRADO,LIQUIDACION_COLOMBIA,73231.000000,2022-08-10,287861.00,A&V,9030750.0,06-2021,14.0,0.031876,0,> 2.5%,< 35 M,2022-08-01
822282,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146463.000000,2022-09-12,287861.00,A&V,9030750.0,06-2021,15.0,0.031876,0,> 2.5%,< 35 M,2022-09-01
822284,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146464.000000,2022-09-28,287861.00,A&V,9030750.0,06-2021,16.0,0.031876,0,> 2.5%,< 35 M,2022-10-01
822297,9957452,false,COBRADO,LIQUIDACION_COLOMBIA,798525.000000,2024-08-13,465252.24,SKANDIA,14306600.0,07-2023,13.0,0.032520,0,> 2.5%,< 35 M,2024-08-01

In [82]:
df_referencia_fecha_pab

,reference,Originado,requester,bank,amount_promedio,amount_total,n_pagos,PaB_total,n_pagos_PaB
0,1000185400,2025-06-19,Hector Elian Lacera Vega,Rapicredit,53546.50,8.999412e+04,2,552839.0,1
1,1000591190,2025-09-11,Steven Mateo Aroca Garzon,Falabella,76543.50,1.286445e+05,2,1930000.0,1
2,100076,2022-12-23,David Steban Pineda Gallo,Davivienda,208809.30,1.754700e+05,1,2942000.0,1
3,100076,2023-01-11,No Asignado,Davivienda,243659.00,4.095109e+05,2,10200000.0,1
4,1001082965,2024-11-18,Daniel Alejandro Umbarila Bolaños,Compensar,410419.00,6.897798e+05,2,1390000.0,1
...,...,...,...,...,...,...,...,...,...
14485,98702966,2025-01-30,Jana Milena Lopez Buitrago,Bancolombia,1140268.44,1.533134e+07,16,8954000.0,3
14486,98709164,2025-08-29,Vivian Caterin Rodriguez Verano,Bancolombia,332080.50,1.116237e+06,4,1800000.0,1
14487,99534,2022-02-14,Maria Paula Balaguera Penagos,Scotiabank Colpatria,390861.45,3.284550e+05,1,1800000.0,1
14488,99534,2022-08-10,Natalia Valentina Castro Jimenez,Colsubsidio,145242.33,3.661571e+05,3,2600000.0,1
14489,9957452,2024-08-13,Juan Felipe Hurtado Mercado,Bancolombia,475122.50,7.985252e+05,2,2800000.0,1

In [83]:
df_filtrado.info()
df_referencia_fecha_pab.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32769 entries, 77 to 822297
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Referencia            32769 non-null  object
 1   Credito               32769 non-null  object
 2   Status facturacion    32769 non-null  object
 3   Tipo de comision      32769 non-null  object
 4   Monto                 32769 non-null  float64
 5   Fecha de facturacion  32769 non-null  datetime64[ns]
 6   Apartado Mensual      32769 non-null  float64
 7   Vehiculo de ahorro    32769 non-null  object
 8   Deuda inicial Fija    32769 non-null  float64
 9   Mes_Año               32769 non-null  object
 10  Mes_Cobro             32769 non-null  float64
 11  AM/DB                 32769 non-null  float64
 12  AM/DB_outlier         32769 non-null  int64
 13  Rango_AM_DB           32769 non-null  category
 14  Rango_de_deuda        32769 non-null  category
 15  mes_exacto            32769 non-null  datetime64[ns]
dtypes: category(2), datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 4.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14490 entries, 0 to 14489
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   reference        14490 non-null  object
 1   Originado        14490 non-null  datetime64[ns]
 2   requester        14490 non-null  object
 3   bank             14490 non-null  object
 4   amount_promedio  14479 non-null  float64
 5   amount_total     14490 non-null  float64
 6   n_pagos          14490 non-null  int64
 7   PaB_total        14490 non-null  float64
 8   n_pagos_PaB      14490 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(2), object(3)
memory usage: 1019.0+ KB

In [84]:
print("df_filtrado cols:", list(df_filtrado.columns))
print("df_referencia_fecha_pab cols:", list(df_referencia_fecha_pab.columns))

df_filtrado cols: ['Referencia', 'Credito', 'Status facturacion', 'Tipo de comision', 'Monto', 'Fecha de facturacion', 'Apartado Mensual', 'Vehiculo de ahorro', 'Deuda inicial Fija', 'Mes_Año', 'Mes_Cobro', 'AM/DB', 'AM/DB_outlier', 'Rango_AM_DB', 'Rango_de_deuda', 'mes_exacto']
df_referencia_fecha_pab cols: ['reference', 'Originado', 'requester', 'bank', 'amount_promedio', 'amount_total', 'n_pagos', 'PaB_total', 'n_pagos_PaB']

In [85]:
import pandas as pd
import numpy as np

def agregar_originado_por_mes_anio(
    df_filtrado: pd.DataFrame,
    df_referencia_fecha_pab: pd.DataFrame,
    *,
    # Nombres de columnas (ajústalos si difieren)
    col_ref_L: str = "Referencia",       # en df_filtrado
    col_mes_L: str = "mes_exacto",       # en df_filtrado
    col_ref_R: str = "reference",        # en df_referencia_fecha_pab
    col_origin_R: str = "Originado"      # en df_referencia_fecha_pab
) -> pd.DataFrame:
    """
    Agrega la columna 'Originado' a df_filtrado con estas reglas:
      - Si un reference tiene SOLO UNA fecha de Originado -> se copia a todas sus filas.
      - Si tiene VARIAS -> para cada mes_exacto se toma la última Originado cuyo MES/AÑO <= MES/AÑO de mes_exacto.
      - Si no hay Originado <= mes_exacto, queda NaT.

    La comparación se hace por MES/AÑO (primer día del mes), por lo que el "mismo mes" cuenta como válido.

    Parámetros:
      df_filtrado: DataFrame con columnas [col_ref_L, col_mes_L]
      df_referencia_fecha_pab: DataFrame con columnas [col_ref_R, col_origin_R]
      col_ref_L, col_mes_L, col_ref_R, col_origin_R: nombres de columnas.
    """
    # Copias de trabajo
    dfL = df_filtrado.copy()
    dfR = df_referencia_fecha_pab.copy()

    # Normaliza nombre de referencia en dfR para unir con dfL
    if col_ref_R != col_ref_L:
        dfR = dfR.rename(columns={col_ref_R: col_ref_L})

    # Asegurar tipos de fecha
    dfL[col_mes_L] = pd.to_datetime(dfL[col_mes_L], errors="coerce")
    dfR[col_origin_R] = pd.to_datetime(dfR[col_origin_R], errors="coerce")

    # Claves por MES/AÑO (primer día de mes) para que "mismo mes" cuente como válido
    dfL["_mes_floor"] = dfL[col_mes_L].dt.to_period("M").dt.to_timestamp()
    dfR["_originado_floor"] = dfR[col_origin_R].dt.to_period("M").dt.to_timestamp()

    # Filtrar dfR a filas válidas (Referencia y fecha válidas)
    dfR_valid = dfR.dropna(subset=[col_ref_L, "_originado_floor"]).copy()

    # Precalcular por referencia: arrays ORDENADOS de fechas originadas y sus valores
    ref_to_origin_keys = {}
    ref_to_origin_vals = {}

    for ref, sub in dfR_valid.groupby(col_ref_L, sort=False):
        sub_sorted = sub.sort_values("_originado_floor")
        ref_to_origin_keys[ref] = sub_sorted["_originado_floor"].to_numpy(dtype="datetime64[ns]")
        ref_to_origin_vals[ref] = sub_sorted[col_origin_R].to_numpy(dtype="datetime64[ns]")

    # Resolver para cada referencia del dfL (sin merge_asof)
    def resolver_para_referencia(grp: pd.DataFrame) -> pd.Series:
        ref = grp.name
        idx = grp.index

        # Si esta referencia no tiene originados en dfR -> todo NaT
        if ref not in ref_to_origin_keys:
            return pd.Series(pd.NaT, index=idx, dtype="datetime64[ns]")

        keys = ref_to_origin_keys[ref]
        vals = ref_to_origin_vals[ref]

        # Si solo hay una fecha -> copiarla completa
        if len(keys) == 1:
            unica = pd.to_datetime(vals[0])
            return pd.Series(unica, index=idx)

        # Múltiples fechas: usar searchsorted con la clave de mes/año
        left_keys = grp["_mes_floor"].to_numpy(dtype="datetime64[ns]")
        out = np.full(shape=len(grp), fill_value=np.datetime64("NaT"), dtype="datetime64[ns]")

        # Para filas con fecha válida:
        mask_ok = ~pd.isna(grp["_mes_floor"])
        if mask_ok.any():
            # Posición del último originado_floor <= _mes_floor
            pos = np.searchsorted(keys, left_keys[mask_ok], side="right") - 1
            good = pos >= 0
            tmp = np.full(mask_ok.sum(), np.datetime64("NaT"), dtype="datetime64[ns]")
            tmp[good] = vals[pos[good]]
            out[mask_ok.to_numpy()] = tmp

        return pd.Series(pd.to_datetime(out), index=idx)

    # Aplicar por referencia y reinsertar en dfL preservando el orden
    resultado_series = (
        dfL.groupby(col_ref_L, sort=False, group_keys=False)
           .apply(resolver_para_referencia)  # no incluye la columna de grupo en grp
           .reindex(dfL.index)
    )

    # Agregar la columna 'Originado' calculada
    dfL["Originado"] = resultado_series.values

    # Limpiar columnas auxiliares
    dfL.drop(columns=["_mes_floor"], inplace=True, errors="ignore")

    return dfL

    # 2) Si ya tienes ambos DataFrames en memoria, simplemente:
df_resultado = agregar_originado_por_mes_anio(df_filtrado, df_referencia_fecha_pab)

/tmp/ipykernel_35719/879417336.py:91: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(resolver_para_referencia)  # no incluye la columna de grupo en grp

In [86]:
if 'Fecha_originacion' in df_resultado.columns:
    df_resultado.drop(columns=['Fecha_originacion'], inplace=True)

In [87]:
df_resultado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro,AM/DB,AM/DB_outlier,Rango_AM_DB,Rango_de_deuda,mes_exacto,Originado
77,1000185400,false,COBRADO,LIQUIDACION_COLOMBIA,19405.915966,2025-06-20,520791.11,SKANDIA,22718600.0,02-2025,4.0,0.022924,0,2% – 2.5%,< 35 M,2025-06-01,2025-06-19
79,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,15060.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,4.0,0.022924,0,2% – 2.5%,< 35 M,2025-06-01,2025-06-19
81,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,55528.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,5.0,0.022924,0,2% – 2.5%,< 35 M,2025-07-01,2025-06-19
154,1000591190,false,COBRADO,LIQUIDACION_COLOMBIA,128644.546218,2025-09-12,344986.00,SKANDIA,12465987.0,12-2024,9.0,0.027674,0,> 2.5%,< 35 M,2025-09-01,2025-09-11
156,1000591190,true,COBRADO,LIQUIDACION_COLOMBIA,214365.000000,2025-09-30,344986.00,SKANDIA,12465987.0,12-2024,10.0,0.027674,0,> 2.5%,< 35 M,2025-10-01,2025-09-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822273,99534,false,COBRADO,LIQUIDACION_COLOMBIA,328455.000000,2022-02-14,287861.00,A&V,9030750.0,06-2021,8.0,0.031876,0,> 2.5%,< 35 M,2022-02-01,2022-02-14
822280,99534,false,COBRADO,LIQUIDACION_COLOMBIA,73231.000000,2022-08-10,287861.00,A&V,9030750.0,06-2021,14.0,0.031876,0,> 2.5%,< 35 M,2022-08-01,2022-08-10
822282,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146463.000000,2022-09-12,287861.00,A&V,9030750.0,06-2021,15.0,0.031876,0,> 2.5%,< 35 M,2022-09-01,2022-08-10
822284,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146464.000000,2022-09-28,287861.00,A&V,9030750.0,06-2021,16.0,0.031876,0,> 2.5%,< 35 M,2022-10-01,2022-08-10
822297,9957452,false,COBRADO,LIQUIDACION_COLOMBIA,798525.000000,2024-08-13,465252.24,SKANDIA,14306600.0,07-2023,13.0,0.032520,0,> 2.5%,< 35 M,2024-08-01,2024-08-13

In [88]:
import pandas as pd
import numpy as np

# =========================
# 1) Normalizar tipos y llaves
# =========================
df_resultado['Originado'] = pd.to_datetime(df_resultado['Originado'], errors='coerce')
df_referencia_fecha_pab['Originado'] = pd.to_datetime(df_referencia_fecha_pab['Originado'], errors='coerce')

df_ref = df_referencia_fecha_pab.copy()
df_ref = df_ref.rename(columns={'reference': 'Referencia'})

# Forzamos numéricos para las columnas a sumar
cols_sum = ['amount_total', 'n_pagos', 'PaB_total', 'n_pagos_PaB']
for c in cols_sum:
    df_ref[c] = pd.to_numeric(df_ref[c], errors='coerce')

# =========================
# 2) Construir clave mensual (mes-año) y consolidar
# =========================
# Clave mensual en ambos dataframes
df_ref['YM'] = df_ref['Originado'].dt.to_period('M')
df_resultado['YM'] = df_resultado['Originado'].dt.to_period('M')

# a) Sumas por Referencia + mes
sums = (
    df_ref.groupby(['Referencia', 'YM'], as_index=False)[cols_sum]
          .sum(min_count=1)             # respeta NaN si todo es NaN
)

# b) Fila del día mayor por Referencia + mes (para requester, bank, amount_promedio y Originado)
#    Ordenamos por fecha asc y nos quedamos con la última (máxima)
cols_take_from_last = ['requester', 'bank', 'amount_promedio', 'Originado']
last_rows = (
    df_ref.sort_values('Originado')
          .groupby(['Referencia', 'YM'], as_index=False)
          .tail(1)[['Referencia', 'YM'] + cols_take_from_last]
)

# c) Consolidado mensual
df_ref_month = sums.merge(last_rows, on=['Referencia', 'YM'], how='left')

# =========================
# 3) Merge contra df_resultado por Referencia + mes-año
# =========================
df_resultado = df_resultado.merge(
    df_ref_month,
    on=['Referencia', 'YM'],
    how='left'
)

# =========================
# 4) Limpieza final (opcional)
# =========================
# Si no quieres dejar la clave auxiliar
df_resultado.drop(columns=['YM'], inplace=True)

print("✅ Columnas agregadas por mes: sumadas y con campos del día mayor. Merge completado.")

✅ Columnas agregadas por mes: sumadas y con campos del día mayor. Merge completado.

In [89]:
df_resultado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,...,mes_exacto,Originado_x,amount_total,n_pagos,PaB_total,n_pagos_PaB,requester,bank,amount_promedio,Originado_y
0,1000185400,false,COBRADO,LIQUIDACION_COLOMBIA,19405.915966,2025-06-20,520791.11,SKANDIA,22718600.0,02-2025,...,2025-06-01,2025-06-19,89994.117647,2,552839.0,1,Hector Elian Lacera Vega,Rapicredit,53546.50,2025-06-19
1,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,15060.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,...,2025-06-01,2025-06-19,89994.117647,2,552839.0,1,Hector Elian Lacera Vega,Rapicredit,53546.50,2025-06-19
2,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,55528.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,...,2025-07-01,2025-06-19,89994.117647,2,552839.0,1,Hector Elian Lacera Vega,Rapicredit,53546.50,2025-06-19
3,1000591190,false,COBRADO,LIQUIDACION_COLOMBIA,128644.546218,2025-09-12,344986.00,SKANDIA,12465987.0,12-2024,...,2025-09-01,2025-09-11,128644.537815,2,1930000.0,1,Steven Mateo Aroca Garzon,Falabella,76543.50,2025-09-11
4,1000591190,true,COBRADO,LIQUIDACION_COLOMBIA,214365.000000,2025-09-30,344986.00,SKANDIA,12465987.0,12-2024,...,2025-10-01,2025-09-11,128644.537815,2,1930000.0,1,Steven Mateo Aroca Garzon,Falabella,76543.50,2025-09-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32764,99534,false,COBRADO,LIQUIDACION_COLOMBIA,328455.000000,2022-02-14,287861.00,A&V,9030750.0,06-2021,...,2022-02-01,2022-02-14,328455.000000,1,1800000.0,1,Maria Paula Balaguera Penagos,Scotiabank Colpatria,390861.45,2022-02-14
32765,99534,false,COBRADO,LIQUIDACION_COLOMBIA,73231.000000,2022-08-10,287861.00,A&V,9030750.0,06-2021,...,2022-08-01,2022-08-10,366157.142857,3,2600000.0,1,Natalia Valentina Castro Jimenez,Colsubsidio,145242.33,2022-08-10
32766,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146463.000000,2022-09-12,287861.00,A&V,9030750.0,06-2021,...,2022-09-01,2022-08-10,366157.142857,3,2600000.0,1,Natalia Valentina Castro Jimenez,Colsubsidio,145242.33,2022-08-10
32767,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146464.000000,2022-09-28,287861.00,A&V,9030750.0,06-2021,...,2022-10-01,2022-08-10,366157.142857,3,2600000.0,1,Natalia Valentina Castro Jimenez,Colsubsidio,145242.33,2022-08-10
32768,9957452,false,COBRADO,LIQUIDACION_COLOMBIA,798525.000000,2024-08-13,465252.24,SKANDIA,14306600.0,07-2023,...,2024-08-01,2024-08-13,798525.210084,2,2800000.0,1,Juan Felipe Hurtado Mercado,Bancolombia,475122.50,2024-08-13

In [90]:
# Si ambas columnas existen:
if 'Originado_x' in df_resultado.columns and 'Originado_y' in df_resultado.columns:
    # Preferimos Originado_y (la del merge con día mayor)
    df_resultado['Originado'] = df_resultado['Originado_y'].combine_first(df_resultado['Originado_x'])
    df_resultado.drop(columns=['Originado_x', 'Originado_y'], inplace=True)

In [91]:
import pandas as pd
import numpy as np

# Aseguramos que las fechas estén bien formateadas
df_resultado['Originado'] = pd.to_datetime(df_resultado['Originado'], errors='coerce')
df_resultado['mes_exacto'] = pd.to_datetime(df_resultado['mes_exacto'], errors='coerce')

# 1️⃣ Crear la columna con mes y año de la fecha de originación
df_resultado['Mes_año_Originacion'] = df_resultado['Originado'].dt.to_period('M').astype(str)
# Ejemplo: "2023-07"

# 2️⃣ Calcular los meses transcurridos entre Originado y mes_exacto
#    (año_diff * 12 + mes_diff)
df_resultado['Meses_despues_Originacion'] = (
    (df_resultado['mes_exacto'].dt.year - df_resultado['Originado'].dt.year) * 12 +
    (df_resultado['mes_exacto'].dt.month - df_resultado['Originado'].dt.month)
)

# Si alguna fecha es NaT → dejar como NaN
df_resultado['Meses_despues_Originacion'] = df_resultado['Meses_despues_Originacion'].where(
    ~df_resultado['Meses_despues_Originacion'].isna(), np.nan
)

# ✅ Resultado final
print(df_resultado[['Referencia', 'Originado', 'mes_exacto', 'Mes_año_Originacion', 'Meses_despues_Originacion']].head(10))

   Referencia  Originado mes_exacto Mes_año_Originacion  \
0  1000185400 2025-06-19 2025-06-01             2025-06
1  1000185400 2025-06-19 2025-06-01             2025-06
2  1000185400 2025-06-19 2025-07-01             2025-06
3  1000591190 2025-09-11 2025-09-01             2025-09
4  1000591190 2025-09-11 2025-10-01             2025-09
5      100076 2022-12-23 2022-12-01             2022-12
6      100076 2023-01-11 2023-01-01             2023-01
7  1001082965 2024-11-18 2024-11-01             2024-11
8  1001082965 2024-12-23 2024-12-01             2024-12
9  1001082965 2025-01-31 2025-02-01             2025-01

   Meses_despues_Originacion
0                          0
1                          0
2                          1
3                          0
4                          1
5                          0
6                          0
7                          0
8                          0
9                          1

In [92]:
import pandas as pd
import numpy as np

# Aseguramos que las fechas estén bien formateadas
df_resultado['Fecha de facturacion'] = pd.to_datetime(df_resultado['Fecha de facturacion'], errors='coerce')
df_resultado['mes_exacto'] = pd.to_datetime(df_resultado['mes_exacto'], errors='coerce')

# 1️⃣ Crear la columna con mes y año de la fecha de originación
df_resultado['Mes_año_Originacion'] = df_resultado['Fecha de facturacion'].dt.to_period('M').astype(str)
# Ejemplo: "2023-07"

# 2️⃣ Calcular los meses transcurridos entre Originado y mes_exacto
#    (año_diff * 12 + mes_diff)
df_resultado['Meses_despues_facturacion'] = (
    (df_resultado['mes_exacto'].dt.year - df_resultado['Fecha de facturacion'].dt.year) * 12 +
    (df_resultado['mes_exacto'].dt.month - df_resultado['Fecha de facturacion'].dt.month)
)

# Si alguna fecha es NaT → dejar como NaN
df_resultado['Meses_despues_facturacion'] = df_resultado['Meses_despues_facturacion'].where(
    ~df_resultado['Meses_despues_facturacion'].isna(), np.nan
)

# ✅ Resultado final
print(df_resultado[['Referencia', 'Fecha de facturacion', 'mes_exacto', 'Mes_año_Originacion', 'Meses_despues_facturacion']].head(10))

   Referencia Fecha de facturacion mes_exacto Mes_año_Originacion  \
0  1000185400           2025-06-20 2025-06-01             2025-06
1  1000185400           2025-06-19 2025-06-01             2025-06
2  1000185400           2025-06-19 2025-07-01             2025-06
3  1000591190           2025-09-12 2025-09-01             2025-09
4  1000591190           2025-09-30 2025-10-01             2025-09
5      100076           2022-12-23 2022-12-01             2022-12
6      100076           2023-01-11 2023-01-01             2023-01
7  1001082965           2024-11-19 2024-11-01             2024-11
8  1001082965           2024-12-23 2024-12-01             2024-12
9  1001082965           2025-02-03 2025-02-01             2025-02

   Meses_despues_facturacion
0                          0
1                          0
2                          1
3                          0
4                          1
5                          0
6                          0
7                          0
8                          0
9                          0

In [93]:
berex_estruct['amount'] = pd.to_numeric(berex_estruct['amount'], errors='coerce')
berex_estruct.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66600 entries, 0 to 66599
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reference       66600 non-null  object
 1   id              54525 non-null  object
 2   amount          66554 non-null  float64
 3   bank            66600 non-null  object
 4   debt_id         66600 non-null  object
 5   destination     66600 non-null  object
 6   payment_date    66600 non-null  datetime64[ns]
 7   payment_number  66540 non-null  object
 8   requester       66600 non-null  object
 9   Originado       66600 non-null  datetime64[ns]
 10  Unnamed: 10     54588 non-null  object
 11  Estructurado    66600 non-null  int64
dtypes: datetime64[ns](2), float64(1), int64(1), object(8)
memory usage: 6.1+ MB

In [94]:
berex_estruct

,reference,id,amount,bank,debt_id,destination,payment_date,payment_number,requester,Originado,Unnamed: 10,Estructurado
0,3183831101,3295,350824.0,Alkosto,544721,commission,2021-01-12,2,Natalia Valentina Castro Jimenez,2021-01-12,318383110144208,1
1,3183831101,3294,500000.0,Alkosto,544721,bank,2021-01-12,1,Natalia Valentina Castro Jimenez,2021-01-12,318383110144208,1
2,3183831101,3296,436000.0,Alkosto,544721,bank,2021-02-19,3,Natalia Valentina Castro Jimenez,2021-01-12,318383110144208,1
3,3183831101,3297,436000.0,Alkosto,544721,bank,2021-03-19,4,Natalia Valentina Castro Jimenez,2021-01-12,318383110144208,1
4,3504389669,3941,131198.0,Alkosto,510212,commission,2021-01-30,2,No Asignado,2021-01-30,350438966944226,1
...,...,...,...,...,...,...,...,...,...,...,...,...
66595,3016008038,NaN,86272.0,Banco de Bogota,1809482,commission,2026-02-27,NaN,Angie Lizeth Cubides Neira,2026-02-27,NaN,0
66596,3184455376,NaN,1122.0,Sistecredito,1688617,commission,2026-02-27,NaN,Dayana Isabel Ojito Ortiz,2026-02-27,NaN,0
66597,3184455376,NaN,1372.0,Sistecredito,1688618,commission,2026-02-27,NaN,Dayana Isabel Ojito Ortiz,2026-02-27,NaN,0
66598,3112460819,NaN,15000000.0,Bancolombia,1671350,bank,2026-03-02,NaN,Vivian Caterin Rodriguez Verano,2026-03-02,NaN,0
66599,3112460819,NaN,1680672.0,Bancolombia,1671350,commission,2026-03-02,NaN,Vivian Caterin Rodriguez Verano,2026-03-02,NaN,0

In [95]:
referencia_buscada = '3017388628'

resultado = berex_estruct[berex_estruct['reference'] == referencia_buscada]

resultado

,reference,id,amount,bank,debt_id,destination,payment_date,payment_number,requester,Originado,Unnamed: 10,Estructurado
50799,3017388628,"270,630",270000.0,BBVA,1552649,commission,2025-12-05,3,Hector Elian Lacera Vega,2025-10-31,301738862845961,1
50800,3017388628,"270,631",270000.0,BBVA,1552649,commission,2026-01-05,4,Hector Elian Lacera Vega,2025-10-31,301738862845961,1
50801,3017388628,"270,632",270000.0,BBVA,1552649,commission,2026-02-05,5,Hector Elian Lacera Vega,2025-10-31,301738862845961,1
50802,3017388628,"270,633",270000.0,BBVA,1552649,commission,2026-03-05,6,Hector Elian Lacera Vega,2025-10-31,301738862845961,1
50803,3017388628,"270,634",270000.0,BBVA,1552649,commission,2026-04-05,7,Hector Elian Lacera Vega,2025-10-31,301738862845961,1
50822,3017388628,"270,629",374042.0,BBVA,1552649,commission,2025-10-31,2,Hector Elian Lacera Vega,2025-10-31,301738862845961,1
50909,3017388628,"270,628",2480000.0,BBVA,1552649,bank,2025-10-31,1,Hector Elian Lacera Vega,2025-10-31,301738862845961,1

In [96]:
referencia_buscada = '42809'

resultado = berex_estruct[berex_estruct['reference'] == referencia_buscada]

resultado

,reference,id,amount,bank,debt_id,destination,payment_date,payment_number,requester,Originado,Unnamed: 10,Estructurado
970,42809,14231,125000.0,Codensa,649850,commission,2021-09-10,2,Jordann Dario Barbosa Villanueva,2021-09-10,4280944449,1
971,42809,14232,193498.0,Codensa,649850,commission,2021-09-28,3,Jordann Dario Barbosa Villanueva,2021-09-10,4280944449,1
983,42809,14230,650000.0,Codensa,649850,bank,2021-09-10,1,Jordann Dario Barbosa Villanueva,2021-09-10,4280944449,1

In [97]:
import pandas as pd

# ==============================
# Parámetros configurables
# ==============================
DENOMINADOR_MESES = 30.4375  # promedio gregoriano de días por mes
DECIMALES_PRI_ULT = 2        # decimales para 'Pri-ult'

# ==============================
# Claves y columnas base
# ==============================
keys = ['reference', 'Originado', 'destination']
cols = ['reference', 'amount', 'payment_date', 'Originado', 'destination']

# ==============================
# Partimos de berex_estruct
# ==============================
df = berex_estruct[cols].copy()

# Tipos
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')
df['payment_date'] = pd.to_datetime(df['payment_date'], errors='coerce')

# =========================================
# A) COLAPSAR PAGOS DENTRO DEL MISMO MES
#    - Suma 'amount' por mes
#    - Conserva la payment_date más reciente de ese mes
# =========================================
df['_ym'] = df['payment_date'].dt.to_period('M')  # año-mes

df_mensual = (
    df.groupby(keys + ['_ym'], dropna=False)
      .agg(
          amount=('amount', 'sum'),              # suma de montos del mes
          payment_date=('payment_date', 'max')   # última fecha del mes
      )
      .reset_index()
)

# =========================================
# B) Calcular Pri-ult (en meses decimales) con min/max del grupo
#    *Ajuste: fecha_min = 1er día del mes; fecha_max = último día del mes*
#    *Se calcula sobre df_mensual, no sobre los registros diarios*
# =========================================
agg = (
    df_mensual.groupby(keys, dropna=False)['payment_date']
              .agg(fecha_min='min', fecha_max='max')
)

# Primer día del mes del primer pago (00:00:00)
fecha_min_floor = agg['fecha_min'].dt.to_period('M').dt.start_time

# Último día del mes del último pago (fin del día)
fecha_max_eom = agg['fecha_max'].dt.to_period('M').dt.end_time

# Diferencia exacta en días
dias = (fecha_max_eom - fecha_min_floor).dt.days

# Convertir a meses decimales
pri_ult = dias / DENOMINADOR_MESES

# Manejo de nulos y formato final
pri_ult = pri_ult.where(agg['fecha_min'].notna() & agg['fecha_max'].notna())
pri_ult = pri_ult.round(DECIMALES_PRI_ULT).astype('float')  # decimal con redondeo
pri_ult.name = 'Pri-ult'

# Unir Pri-ult al DF mensual
df_mensual = df_mensual.merge(pri_ult, left_on=keys, right_index=True, how='left')

# =========================================
# C) Ordenar y quedarnos con la payment_date más antigua por grupo
#    (ya no hay duplicados por mes, así que esto elige el mes más antiguo)
# =========================================
df_mensual_sorted = df_mensual.sort_values(keys + ['payment_date'], ascending=True)

df_unico_antiguo = (
    df_mensual_sorted
      .drop_duplicates(subset=keys, keep='first')  # toma el mes más antiguo por grupo
      .reset_index(drop=True)
)

# Limpieza opcional
df_unico_antiguo = df_unico_antiguo.drop(columns=['_ym'])

In [98]:
referencia_buscada = '3017388628'

resultado = df_unico_antiguo[df_unico_antiguo['reference'] == referencia_buscada]

resultado

       reference  Originado destination     amount payment_date  Pri-ult
4473  3017388628 2025-10-31        bank  2480000.0   2025-10-31     0.99
4474  3017388628 2025-10-31  commission   374042.0   2025-10-31     6.93

In [99]:
referencia_buscada = '42809'

resultado = df_unico_antiguo[df_unico_antiguo['reference'] == referencia_buscada]

resultado

      reference  Originado destination    amount payment_date  Pri-ult
27630     42809 2021-09-10        bank  650000.0   2021-09-10     0.95
27631     42809 2021-09-10  commission  318498.0   2021-09-28     0.95

In [100]:
df_unico_antiguo

        reference  Originado destination      amount payment_date  Pri-ult
0      1000185400 2025-06-19        bank   552839.00   2025-06-19     0.95
1      1000185400 2025-06-19  commission    23093.00   2025-06-19     1.97
2      1000591190 2025-09-11        bank  1930000.00   2025-09-11     0.95
3      1000591190 2025-09-11  commission    76000.00   2025-09-11     1.97
4          100076 2022-12-23        bank  2942000.00   2022-12-23     0.99
...           ...        ...         ...         ...          ...      ...
29014       99534 2022-02-14  commission   390861.45   2022-02-14     0.89
29015       99534 2022-08-10        bank  2600000.00   2022-08-10     0.99
29016       99534 2022-08-10  commission   261436.00   2022-08-10     1.97
29017     9957452 2024-08-13        bank  2800000.00   2024-08-13     0.99
29018     9957452 2024-08-13  commission   737000.00   2024-08-13     1.97

[29019 rows x 6 columns]

#LLAMAMOS MENSUALIDADES DE DF_MORA_ESTADOS

In [101]:
import os, json, gspread
from google.oauth2.service_account import Credentials

# --- Obtener MI_JSON del entorno o de Colab ---
mi_json_str = os.environ.get("MI_JSON")

if mi_json_str is None:
    try:
        from google.colab import userdata
        mi_json_str = userdata.get("MI_JSON")
    except Exception:
        raise RuntimeError("No se encontró MI_JSON en entorno ni en Colab.")

# --- Si el secreto está en texto plano JSON ---
creds_dict = json.loads(mi_json_str)

# --- Si lo guardaste codificado en base64 (recomendado) ---
# import base64
# creds_dict = json.loads(base64.b64decode(mi_json_str).decode("utf-8"))

scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

creds = Credentials.from_service_account_info(creds_dict, scopes=scope)
client = gspread.authorize(creds)
# === 3️⃣ Abrir el archivo y buscar la hoja por su GID ===
sheet_id = "1jcPPhtF2YK3Kr7P_A0Mgh2OqhOfnVWB2to3UPoSH5tE"
sheet = client.open_by_key(sheet_id)

# Buscar la hoja con el gid que mencionaste
target_gid = "702333742"

worksheet = None
for ws in sheet.worksheets():
    if str(ws.id) == target_gid:
        worksheet = ws
        break

if worksheet is None:
    raise ValueError(f"No se encontró una hoja con gid={target_gid}")

# === 4️⃣ Cargar los datos a un DataFrame ===
data = worksheet.get_all_records()
df_mensualidades = pd.DataFrame(data)

# === 5️⃣ Mostrar una vista previa ===
print(f"✅ Hoja '{worksheet.title}' cargada correctamente desde Google Sheets.")
print(f"Filas: {df_mensualidades.shape[0]}, Columnas: {df_mensualidades.shape[1]}")
df_mensualidades.head()

✅ Hoja 'Mensualidades' cargada correctamente desde Google Sheets.
Filas: 209067, Columnas: 8

,Referencia,Fecha de corte,Fecha de facturacion,X_COBRAR,C_Parcial,X_COBRAR_ACUMULADO,DIAS_EN_MORA,Status_Mora
0,1000185400,2026-01-31 0:00:00,2026-01-07 0:00:00,101378.0,0,101378.0,24,Mora 1
1,1000185400,2026-02-28 0:00:00,2026-02-05 0:00:00,106549.0,0,207927.0,52,Mora 30
2,1000185400,2026-03-31 0:00:00,2026-03-05 0:00:00,106549.0,0,314476.0,83,Mora 60
3,1000185400,2026-04-10 0:00:00,,0.0,,314476.0,93,Mora 90
4,1001082965,2025-02-28 0:00:00,2025-02-06 0:00:00,599181.0,0,599181.0,22,Mora 1

In [102]:
# Convertir 'Referencia' a tipo object (string)
df_mensualidades['Referencia'] = df_mensualidades['Referencia'].astype(str)

# Convertir las fechas a datetime (maneja errores automáticamente)
df_mensualidades['Fecha de corte'] = pd.to_datetime(
    df_mensualidades['Fecha de corte'], errors='coerce', dayfirst=True
)
df_mensualidades['Fecha de facturacion'] = pd.to_datetime(
    df_mensualidades['Fecha de facturacion'], errors='coerce', dayfirst=True
)

# Verificar tipos finales
df_mensualidades.dtypes

/tmp/ipykernel_35719/2878630590.py:5: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_mensualidades['Fecha de corte'] = pd.to_datetime(

Referencia                      object
Fecha de corte          datetime64[ns]
Fecha de facturacion    datetime64[ns]
X_COBRAR                       float64
C_Parcial                       object
X_COBRAR_ACUMULADO             float64
DIAS_EN_MORA                     int64
Status_Mora                     object
dtype: object

In [103]:
df_mensualidades

,Referencia,Fecha de corte,Fecha de facturacion,X_COBRAR,C_Parcial,X_COBRAR_ACUMULADO,DIAS_EN_MORA,Status_Mora
0,1000185400,2026-01-31,2026-07-01,101378.0,0,101378.0,24,Mora 1
1,1000185400,2026-02-28,2026-05-02,106549.0,0,207927.0,52,Mora 30
2,1000185400,2026-03-31,2026-05-03,106549.0,0,314476.0,83,Mora 60
3,1000185400,2026-04-10,NaT,0.0,,314476.0,93,Mora 90
4,1001082965,2025-02-28,2025-06-02,599181.0,0,599181.0,22,Mora 1
...,...,...,...,...,...,...,...,...
209062,9957452,2025-12-31,2025-04-12,10504.0,0,10504.0,27,Mora 1
209063,9957452,2026-01-31,2026-07-01,10504.0,0,21008.0,58,Mora 30
209064,9957452,2026-02-28,2026-05-02,10504.0,0,31512.0,86,Mora 60
209065,9957452,2026-03-31,2026-05-03,10504.0,0,42016.0,117,Mora 90
209066,9957452,2026-04-10,NaT,0.0,,42016.0,127,Mora 120

In [104]:
df_resultado.info()
df_mensualidades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32769 entries, 0 to 32768
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Referencia                 32769 non-null  object
 1   Credito                    32769 non-null  object
 2   Status facturacion         32769 non-null  object
 3   Tipo de comision           32769 non-null  object
 4   Monto                      32769 non-null  float64
 5   Fecha de facturacion       32769 non-null  datetime64[ns]
 6   Apartado Mensual           32769 non-null  float64
 7   Vehiculo de ahorro         32769 non-null  object
 8   Deuda inicial Fija         32769 non-null  float64
 9   Mes_Año                    32769 non-null  object
 10  Mes_Cobro                  32769 non-null  float64
 11  AM/DB                      32769 non-null  float64
 12  AM/DB_outlier              32769 non-null  int64
 13  Rango_AM_DB                32769 non-null  category
 14  Rango_de_deuda             32769 non-null  category
 15  mes_exacto                 32769 non-null  datetime64[ns]
 16  amount_total               32769 non-null  float64
 17  n_pagos                    32769 non-null  int64
 18  PaB_total                  32769 non-null  float64
 19  n_pagos_PaB                32769 non-null  int64
 20  requester                  32769 non-null  object
 21  bank                       32769 non-null  object
 22  amount_promedio            32766 non-null  float64
 23  Originado                  32769 non-null  datetime64[ns]
 24  Mes_año_Originacion        32769 non-null  object
 25  Meses_despues_Originacion  32769 non-null  int32
 26  Meses_despues_facturacion  32769 non-null  int32
dtypes: category(2), datetime64[ns](3), float64(8), int32(2), int64(3), object(9)
memory usage: 6.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209067 entries, 0 to 209066
Data columns (total 8 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Referencia            209067 non-null  object
 1   Fecha de corte        209067 non-null  datetime64[ns]
 2   Fecha de facturacion  27085 non-null   datetime64[ns]
 3   X_COBRAR              209067 non-null  float64
 4   C_Parcial             209067 non-null  object
 5   X_COBRAR_ACUMULADO    209067 non-null  float64
 6   DIAS_EN_MORA          209067 non-null  int64
 7   Status_Mora           209067 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(1), object(3)
memory usage: 12.8+ MB

In [105]:
import pandas as pd
import numpy as np

# Copias de trabajo
dfu = df_unico_antiguo.copy()
dfm = df_mensualidades.copy()

# Tipos consistentes
dfu['reference'] = dfu['reference'].astype(str)
dfm['Referencia'] = dfm['Referencia'].astype(str)

dfu['Originado'] = pd.to_datetime(dfu['Originado'], errors='coerce')
dfu['Pri-ult'] = pd.to_numeric(dfu['Pri-ult'], errors='coerce')  # permite NaN
dfm['Fecha de facturacion'] = pd.to_datetime(dfm['Fecha de facturacion'], errors='coerce')

# === 0) Pri-ult máximo por (reference, Originado), con ceil ===
priult_max = (
    dfu.groupby(['reference', 'Originado'], dropna=False)['Pri-ult']
       .max()                          # toma el mayor Pri-ult del grupo
       .reset_index(name='Pri_ult_max')
)
priult_max['Pri_ult_max'] = np.ceil(priult_max['Pri_ult_max'])

# === 1) Calcular fecha_fin_max usando ese Pri_ult_max (sin eliminar filas originales) ===
def calc_fecha_fin_max(row):
    originado = row['Originado']
    p = row['Pri_ult_max']
    if pd.isna(originado) or pd.isna(p):
        return pd.NaT
    return (originado + pd.DateOffset(months=int(p))) + pd.offsets.MonthEnd(0)

priult_max['fecha_fin_max'] = priult_max.apply(calc_fecha_fin_max, axis=1)

# === 2) Merge para traer facturas y filtrar por rango [Originado, fecha_fin_max] ===
tmp = priult_max.merge(
    dfm[['Referencia', 'Fecha de facturacion', 'X_COBRAR']],
    left_on='reference', right_on='Referencia', how='left'
)

mask = (
    tmp['Fecha de facturacion'].notna() &
    tmp['Originado'].notna() &
    tmp['fecha_fin_max'].notna() &
    (tmp['Fecha de facturacion'] >= tmp['Originado']) &
    (tmp['Fecha de facturacion'] <= tmp['fecha_fin_max'])
)
tmp_ok = tmp.loc[mask].copy()

# === 3) Sumar X_COBRAR dentro del rango por (reference, Originado) ===
suma_por_rango = (
    tmp_ok.groupby(['reference', 'Originado'], dropna=False)['X_COBRAR']
          .sum()
          .reset_index()
          .rename(columns={'X_COBRAR': 'Monto_Mensualidades'})
)

# === 4) Unir la suma al dfu ORIGINAL (sin eliminar sus filas) ===
dfu = dfu.merge(suma_por_rango, on=['reference', 'Originado'], how='left')

# Si no hay Originado o no hubo Pri-ult válido en el grupo, dejar NaN
falta_info = dfu['Originado'].isna() | dfu.groupby(['reference','Originado'])['Pri-ult'].transform('max').isna()
dfu.loc[falta_info, 'Monto_Mensualidades'] = np.nan

# === 5) Resultado final (no tocamos filas de dfu, solo agregamos la columna) ===
df_unico_antiguo = dfu  # ya incluye 'Monto_Mensualidades'

In [106]:
df_unico_antiguo

,reference,Originado,destination,amount,payment_date,Pri-ult,Monto_Mensualidades
0,1000185400,2025-06-19,bank,552839.00,2025-06-19,0.95,NaN
1,1000185400,2025-06-19,commission,23093.00,2025-06-19,1.97,NaN
2,1000591190,2025-09-11,bank,1930000.00,2025-09-11,0.95,NaN
3,1000591190,2025-09-11,commission,76000.00,2025-09-11,1.97,NaN
4,100076,2022-12-23,bank,2942000.00,2022-12-23,0.99,NaN
...,...,...,...,...,...,...,...
29014,99534,2022-02-14,commission,390861.45,2022-02-14,0.89,NaN
29015,99534,2022-08-10,bank,2600000.00,2022-08-10,0.99,NaN
29016,99534,2022-08-10,commission,261436.00,2022-08-10,1.97,NaN
29017,9957452,2024-08-13,bank,2800000.00,2024-08-13,0.99,NaN
29018,9957452,2024-08-13,commission,737000.00,2024-08-13,1.97,NaN

In [107]:
referencia_buscada = '3002426421'

resultado = df_unico_antiguo[df_unico_antiguo['reference'] == referencia_buscada]

resultado

,reference,Originado,destination,amount,payment_date,Pri-ult,Monto_Mensualidades
1345,3002426421,2024-04-27,bank,2610000.0,2024-04-27,0.95,10504.0
1346,3002426421,2024-04-27,commission,97139.7,2024-04-27,0.95,10504.0
1347,3002426421,2024-06-11,bank,2204000.0,2024-06-26,0.95,10504.0
1348,3002426421,2024-06-11,commission,500000.0,2024-06-11,3.98,10504.0

In [108]:
df_unico_antiguo.loc[df_unico_antiguo["destination"] == "commission", "amount"] = (
    pd.to_numeric(df_unico_antiguo.loc[df_unico_antiguo["destination"] == "commission", "amount"], errors="coerce") / 1.19
)

In [109]:
# Renombrar la columna 'bank' a 'BANCO' en df_resultado
if 'bank' in df_resultado.columns:
    df_resultado.rename(columns={'bank': 'BANCO'}, inplace=True)

In [110]:
import numpy as np
import pandas as pd

# =========================================
# 1) Insumos desde df_unico_antiguo (llave: ['reference','Originado'])
# =========================================
dfu = df_unico_antiguo.copy()

# Normalizaciones mínimas de columnas de valor (NO tocamos la llave)
dfu['destination'] = dfu['destination'].astype(str).str.strip().str.lower()
for c in ['amount', 'Pri-ult', 'Monto_Mensualidades']:
    dfu[c] = pd.to_numeric(dfu[c], errors='coerce')

# --- Pivot: amounts por destino (index = llave exacta) ---
pivot_amt = (
    dfu.pivot_table(
        index=['reference', 'Originado'],
        columns='destination',
        values='amount',
        aggfunc='first'
    )
    .reset_index()
    .rename(columns={'bank': 'bank_monto', 'commission': 'commission_monto'})
)

# Asegurar columnas numéricas aunque no existan
for col in ['bank_monto', 'commission_monto']:
    if col not in pivot_amt.columns:
        pivot_amt[col] = 0.0
pivot_amt[['bank_monto', 'commission_monto']] = pivot_amt[['bank_monto', 'commission_monto']].fillna(0.0)

# --- ÚNICO Pri-ult por llave: usar el MAYOR ---
priult_final = (
    dfu.groupby(['reference', 'Originado'], dropna=False)['Pri-ult']
       .max()
       .reset_index()
       .rename(columns={'Pri-ult': 'Pri_ult_final'})
)

# --- ÚNICO Monto_Mensualidades por llave: usar el MAYOR ---
mens_final = (
    dfu.groupby(['reference', 'Originado'], dropna=False)['Monto_Mensualidades']
       .max()
       .reset_index()
)

# --- Ensamblar insumos por llave (1 fila por llave) ---
insumos = (
    pivot_amt
    .merge(priult_final, on=['reference', 'Originado'], how='left', validate='one_to_one')
    .merge(mens_final,   on=['reference', 'Originado'], how='left', validate='one_to_one')
    [['reference', 'Originado', 'bank_monto', 'commission_monto', 'Pri_ult_final', 'Monto_Mensualidades']]
)

# Validación de unicidad en insumos
if insumos.duplicated(['reference', 'Originado']).any():
    dups = insumos[insumos.duplicated(['reference','Originado'], keep=False)].sort_values(['reference','Originado'])
    raise ValueError(
        "La tabla 'insumos' no es única por ['reference','Originado'].\n"
        f"Ejemplos de duplicados:\n{dups.head(10)}"
    )

# =========================================
# 2) Merge con df_resultado (llave: ['Referencia','Originado'] ↔ ['reference','Originado'])
# =========================================
dfr = df_resultado.copy()

# Eliminar C/A y Pri-ult previos para evitar arrastres
for col in ['C/A', 'Pri-ult']:
    if col in dfr.columns:
        dfr.drop(columns=[col], inplace=True)

# Merge estrictamente por (Referencia|reference, Originado)
dfr = dfr.merge(
    insumos,
    left_on=['Referencia', 'Originado'],
    right_on=['reference', 'Originado'],
    how='left',
    validate='many_to_one'
)

# Usar una sola columna Pri-ult para el cálculo
dfr.rename(columns={'Pri_ult_final': 'Pri-ult'}, inplace=True)

# Limpiar auxiliares
if 'reference' in dfr.columns:
    dfr.drop(columns=['reference'], inplace=True)

# =========================================
# 3) Asegurar columnas necesarias
# =========================================
necesarias = [
    'PaB_total', 'amount_total', 'Apartado Mensual',
    'Pri-ult', 'bank_monto', 'commission_monto', 'Monto_Mensualidades'
]
for col in necesarias:
    if col not in dfr.columns:
        dfr[col] = np.nan

# Conversión a numérico
for c in necesarias:
    dfr[c] = pd.to_numeric(dfr[c], errors='coerce')

# 🔒 AJUSTE SOLICITADO: Antes de cualquier cálculo, forzar Pri-ult <= 1 a 1
dfr['Pri-ult'] = np.where(dfr['Pri-ult'].notna() & (dfr['Pri-ult'] <= 1), 1, dfr['Pri-ult'])

# =========================================
# 4) Cálculo C/A
# =========================================
# Numerador = PaB_total + amount_total - bank_monto - commission_monto + (Monto_Mensualidades * 1.19)
numerador = (
    dfr['PaB_total'].fillna(0)
    + dfr['amount_total'].fillna(0)
    - dfr['bank_monto'].fillna(0)
    - dfr['commission_monto'].fillna(0)
    + dfr['Monto_Mensualidades'].fillna(0) * 1.19
)

# Pri-ult base (ya con ≤1 => 1): si es NaN permanece NaN
priult_base = dfr['Pri-ult'].to_numpy()

# SOLO EN EL CÁLCULO: restar 1 excepto si es exactamente 1
priult_ajustada = np.where(priult_base == 1, 1, priult_base - 1)

# Evitar divisiones inválidas
priult_ajustada = pd.to_numeric(priult_ajustada, errors='coerce')
intermedio = numerador / priult_ajustada

# C/A se calcula solo cuando hay Apartado Mensual válido
dfr['C/A'] = np.where(
    (dfr['Apartado Mensual'].notna()) & (dfr['Apartado Mensual'] != 0),
    intermedio / dfr['Apartado Mensual'],
    np.nan
)

# =========================================
# 5) Salida
# =========================================
df_resultado = dfr.copy()
print("✅ Listo. Columnas:", df_resultado.columns.tolist())
print("🔐 Pri-ult <= 1 se fuerza a 1 antes de todo; en el denominador se resta 1 salvo que sea 1.")

✅ Listo. Columnas: ['Referencia', 'Credito', 'Status facturacion', 'Tipo de comision', 'Monto', 'Fecha de facturacion', 'Apartado Mensual', 'Vehiculo de ahorro', 'Deuda inicial Fija', 'Mes_Año', 'Mes_Cobro', 'AM/DB', 'AM/DB_outlier', 'Rango_AM_DB', 'Rango_de_deuda', 'mes_exacto', 'amount_total', 'n_pagos', 'PaB_total', 'n_pagos_PaB', 'requester', 'BANCO', 'amount_promedio', 'Originado', 'Mes_año_Originacion', 'Meses_despues_Originacion', 'Meses_despues_facturacion', 'bank_monto', 'commission_monto', 'Pri-ult', 'Monto_Mensualidades', 'C/A']
🔐 Pri-ult <= 1 se fuerza a 1 antes de todo; en el denominador se resta 1 salvo que sea 1.

In [111]:
referencia_buscada = '3017388628'

resultado = df_unico_antiguo[df_unico_antiguo['reference'] == referencia_buscada]

resultado

,reference,Originado,destination,amount,payment_date,Pri-ult,Monto_Mensualidades
4473,3017388628,2025-10-31,bank,2.480000e+06,2025-10-31,0.99,NaN
4474,3017388628,2025-10-31,commission,3.143210e+05,2025-10-31,6.93,NaN

In [112]:
# Filtrar las referencias deseadas
filtro = df_resultado['Referencia'].isin(['79621572', '3233199692', '3214703121', '3002426421', '3508191585'])

# Seleccionar solo las columnas específicas
df_resultado_filtrado = dfr.loc[filtro, ['Referencia', 'Pri-ult', 'Monto_Mensualidades', 'C/A']]

# Mostrar el resultado
df_resultado_filtrado

       Referencia  Pri-ult  Monto_Mensualidades        C/A
1385   3002426421     1.00              10504.0   0.030847
1386   3002426421     3.98              10504.0   0.364786
1387   3002426421     3.98              10504.0   0.364786
1388   3002426421     3.98              10504.0   0.364786
28684  3214703121     2.00                  NaN  12.992014
30449  3233199692     3.91             205413.0   0.445793
30450  3233199692     3.91             205413.0   0.445793
30451  3233199692     3.91             205413.0   0.445793
30452  3233199692     3.91             205413.0   0.445793
31442  3508191585     2.96                  NaN   0.012022
32418    79621572     3.98                  NaN   0.214196
32419    79621572     3.98                  NaN   0.214196
32420    79621572     3.98                  NaN   0.214196

In [113]:
# Eliminar columnas no deseadas de df_resultado
df_resultado.drop(
    columns=['reference', 'bank_y', 'commission', 'bank'],
    inplace=True,
    errors='ignore'  # evita error si alguna no existe
)

In [114]:
df_resultado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,...,amount_promedio,Originado,Mes_año_Originacion,Meses_despues_Originacion,Meses_despues_facturacion,bank_monto,commission_monto,Pri-ult,Monto_Mensualidades,C/A
0,1000185400,false,COBRADO,LIQUIDACION_COLOMBIA,19405.915966,2025-06-20,520791.11,SKANDIA,22718600.0,02-2025,...,53546.50,2025-06-19,2025-06,0,0,552839.0,19405.882353,1.97,NaN,0.139732
1,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,15060.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,...,53546.50,2025-06-19,2025-06,0,0,552839.0,19405.882353,1.97,NaN,0.139732
2,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,55528.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,...,53546.50,2025-06-19,2025-06,1,1,552839.0,19405.882353,1.97,NaN,0.139732
3,1000591190,false,COBRADO,LIQUIDACION_COLOMBIA,128644.546218,2025-09-12,344986.00,SKANDIA,12465987.0,12-2024,...,76543.50,2025-09-11,2025-09,0,0,1930000.0,63865.546218,1.97,NaN,0.193580
4,1000591190,true,COBRADO,LIQUIDACION_COLOMBIA,214365.000000,2025-09-30,344986.00,SKANDIA,12465987.0,12-2024,...,76543.50,2025-09-11,2025-09,1,1,1930000.0,63865.546218,1.97,NaN,0.193580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32764,99534,false,COBRADO,LIQUIDACION_COLOMBIA,328455.000000,2022-02-14,287861.00,A&V,9030750.0,06-2021,...,390861.45,2022-02-14,2022-02,0,0,1800000.0,328455.000000,1.00,NaN,0.000000
32765,99534,false,COBRADO,LIQUIDACION_COLOMBIA,73231.000000,2022-08-10,287861.00,A&V,9030750.0,06-2021,...,145242.33,2022-08-10,2022-08,0,0,2600000.0,219694.117647,1.97,NaN,0.524534
32766,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146463.000000,2022-09-12,287861.00,A&V,9030750.0,06-2021,...,145242.33,2022-08-10,2022-09,1,0,2600000.0,219694.117647,1.97,NaN,0.524534
32767,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146464.000000,2022-09-28,287861.00,A&V,9030750.0,06-2021,...,145242.33,2022-08-10,2022-09,2,1,2600000.0,219694.117647,1.97,NaN,0.524534
32768,9957452,false,COBRADO,LIQUIDACION_COLOMBIA,798525.000000,2024-08-13,465252.24,SKANDIA,14306600.0,07-2023,...,475122.50,2024-08-13,2024-08,0,0,2800000.0,619327.731092,1.97,NaN,0.397074

In [115]:
referencia_buscada = '3017388628'

resultado = df_resultado[df_resultado['Referencia'] == referencia_buscada]

resultado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,...,amount_promedio,Originado,Mes_año_Originacion,Meses_despues_Originacion,Meses_despues_facturacion,bank_monto,commission_monto,Pri-ult,Monto_Mensualidades,C/A
5158,3017388628,false,COBRADO,LIQUIDACION_COLOMBIA,314321.218487,2025-11-05,340014.7,POWWI,12138500.0,06-2024,...,287340.33,2025-10-31,2025-11,1,0,2480000.0,314321.008403,6.93,NaN,0.562645
5159,3017388628,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,42828.000000,2025-11-04,340014.7,POWWI,12138500.0,06-2024,...,287340.33,2025-10-31,2025-11,1,0,2480000.0,314321.008403,6.93,NaN,0.562645
5160,3017388628,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,226887.000000,2025-11-04,340014.7,POWWI,12138500.0,06-2024,...,287340.33,2025-10-31,2025-11,3,2,2480000.0,314321.008403,6.93,NaN,0.562645
5161,3017388628,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,226890.000000,2025-11-04,340014.7,POWWI,12138500.0,06-2024,...,287340.33,2025-10-31,2025-11,4,3,2480000.0,314321.008403,6.93,NaN,0.562645
5162,3017388628,false,COBRO_PARCIAL,LIQUIDACION_COLOMBIA,41918.000000,2025-11-04,340014.7,POWWI,12138500.0,06-2024,...,287340.33,2025-10-31,2025-11,5,4,2480000.0,314321.008403,6.93,NaN,0.562645
5163,3017388628,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,410959.000000,2025-11-04,340014.7,POWWI,12138500.0,06-2024,...,287340.33,2025-10-31,2025-11,5,4,2480000.0,314321.008403,6.93,NaN,0.562645
5164,3017388628,false,COBRO_PARCIAL,LIQUIDACION_COLOMBIA,903.000000,2025-11-04,340014.7,POWWI,12138500.0,06-2024,...,287340.33,2025-10-31,2025-11,6,5,2480000.0,314321.008403,6.93,NaN,0.562645

In [117]:
# Calcular la diferencia en días (valor absoluto)
#df_resultado['diferencia_dias'] = (df_resultado['Fecha de facturacion'] - df_resultado['Originado']).abs().dt.days

# Filtrar filas donde la diferencia sea menor o igual a 3
#df_filtrado = df_resultado[df_resultado['diferencia_dias'] <= 3]

# Eliminar la columna auxiliar si ya no la necesitas
#df_filtrado = df_filtrado.drop(columns='diferencia_dias')

In [116]:
df_filtrado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro,AM/DB,AM/DB_outlier,Rango_AM_DB,Rango_de_deuda,mes_exacto
77,1000185400,false,COBRADO,LIQUIDACION_COLOMBIA,19405.915966,2025-06-20,520791.11,SKANDIA,22718600.0,02-2025,4.0,0.022924,0,2% – 2.5%,< 35 M,2025-06-01
79,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,15060.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,4.0,0.022924,0,2% – 2.5%,< 35 M,2025-06-01
81,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,55528.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,5.0,0.022924,0,2% – 2.5%,< 35 M,2025-07-01
154,1000591190,false,COBRADO,LIQUIDACION_COLOMBIA,128644.546218,2025-09-12,344986.00,SKANDIA,12465987.0,12-2024,9.0,0.027674,0,> 2.5%,< 35 M,2025-09-01
156,1000591190,true,COBRADO,LIQUIDACION_COLOMBIA,214365.000000,2025-09-30,344986.00,SKANDIA,12465987.0,12-2024,10.0,0.027674,0,> 2.5%,< 35 M,2025-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822273,99534,false,COBRADO,LIQUIDACION_COLOMBIA,328455.000000,2022-02-14,287861.00,A&V,9030750.0,06-2021,8.0,0.031876,0,> 2.5%,< 35 M,2022-02-01
822280,99534,false,COBRADO,LIQUIDACION_COLOMBIA,73231.000000,2022-08-10,287861.00,A&V,9030750.0,06-2021,14.0,0.031876,0,> 2.5%,< 35 M,2022-08-01
822282,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146463.000000,2022-09-12,287861.00,A&V,9030750.0,06-2021,15.0,0.031876,0,> 2.5%,< 35 M,2022-09-01
822284,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146464.000000,2022-09-28,287861.00,A&V,9030750.0,06-2021,16.0,0.031876,0,> 2.5%,< 35 M,2022-10-01
822297,9957452,false,COBRADO,LIQUIDACION_COLOMBIA,798525.000000,2024-08-13,465252.24,SKANDIA,14306600.0,07-2023,13.0,0.032520,0,> 2.5%,< 35 M,2024-08-01

In [117]:
referencia_buscada = '3508191585'

resultado = df_filtrado[df_filtrado['Referencia'] == referencia_buscada]

resultado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro,AM/DB,AM/DB_outlier,Rango_AM_DB,Rango_de_deuda,mes_exacto
758882,3508191585,false,COBRADO,LIQUIDACION_COLOMBIA,18360.0,2025-09-25,422543.09,DING,16529250.0,05-2025,4.0,0.025563,0,> 2.5%,< 35 M,2025-09-01

In [118]:
df_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32769 entries, 77 to 822297
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Referencia            32769 non-null  object
 1   Credito               32769 non-null  object
 2   Status facturacion    32769 non-null  object
 3   Tipo de comision      32769 non-null  object
 4   Monto                 32769 non-null  float64
 5   Fecha de facturacion  32769 non-null  datetime64[ns]
 6   Apartado Mensual      32769 non-null  float64
 7   Vehiculo de ahorro    32769 non-null  object
 8   Deuda inicial Fija    32769 non-null  float64
 9   Mes_Año               32769 non-null  object
 10  Mes_Cobro             32769 non-null  float64
 11  AM/DB                 32769 non-null  float64
 12  AM/DB_outlier         32769 non-null  int64
 13  Rango_AM_DB           32769 non-null  category
 14  Rango_de_deuda        32769 non-null  category
 15  mes_exacto            32769 non-null  datetime64[ns]
dtypes: category(2), datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 4.8+ MB

In [120]:
import os, json, pandas as pd, gspread
from gspread_dataframe import get_as_dataframe
from google.oauth2.service_account import Credentials

# --- Leer MI_JSON desde entorno o Colab ---
mi_json_str = os.environ.get("MI_JSON")

if mi_json_str is None:
    try:
        from google.colab import userdata
        mi_json_str = userdata.get("MI_JSON")
    except Exception:
        raise RuntimeError("No se encontró MI_JSON en entorno ni en Colab.")

# --- Parsear JSON (o decodificar base64 si lo guardaste así) ---
svc_info = json.loads(mi_json_str)
# import base64; svc_info = json.loads(base64.b64decode(mi_json_str).decode())

# --- Autenticación con gspread ---
scopes = ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"]
creds = Credentials.from_service_account_info(svc_info, scopes=scopes)
gc = gspread.authorize(creds)

# --- Abrir la hoja ---
sheet = gc.open_by_key("1jcPPhtF2YK3Kr7P_A0Mgh2OqhOfnVWB2to3UPoSH5tE")
ws = sheet.get_worksheet_by_id(916870612)
if ws is None:
    raise ValueError("No se encontró la hoja con gid=916870612")

# --- Descargar a DataFrame ---
df_mora = get_as_dataframe(ws, evaluate_formulas=True, header=0, keep_default_na=False, na_filter=True)
df_mora = df_mora.dropna(how="all").reset_index(drop=True)

for col in ["FECHA", "Mes_año_Originacion"]:
    if col in df_mora.columns:
        df_mora[col] = pd.to_datetime(df_mora[col], errors="coerce", dayfirst=True)

print("✅ Hoja cargada correctamente:", len(df_mora), "filas ×", len(df_mora.columns), "columnas")

✅ Hoja cargada correctamente: 96966 filas × 16 columnas

/tmp/ipykernel_35719/3512521139.py:36: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_mora[col] = pd.to_datetime(df_mora[col], errors="coerce", dayfirst=True)

In [121]:
df_mora

,REFERENCIA,FECHA,X_COBRAR,PAGO,X_COBRAR_FUTURO,PLAN_PAGADO,PLAN_PAGADO_INCOBRABLE,FECHA_ORIGEN,FECHA_COBRO,RESPONSABLE,FECHA_DE_PAGO,MOROSO,DIAS_EN_MORA,MORA_STATUS,Saldo actual,PAGO_PARCIAL
0,1000185400,2025-06-30,19405.88,89993.915966,70588.24,-70588.035966,-70588.035966,2025-06-19 0:00:00,2025-06-20 0:00:00,Hector Elian Lacera Vega,2025-06-19 0:00:00,False,0,Al día,,0
1,1000185400,2025-07-31,70588.24,0.000000,0.00,0.204034,0.204034,,,Hector Elian Lacera Vega,2025-07-05 0:00:00,False,0,Cerrado,,0
2,1000185400,2025-08-31,0.00,0.000000,0.00,0.204034,0.204034,,,Hector Elian Lacera Vega,,False,0,Cerrado,,0
3,1000591190,2025-09-30,63865.55,128644.546218,64778.99,-407703.996218,-407703.996218,2025-09-11 0:00:00,2025-09-15 0:00:00,Steven Mateo Aroca Garzon,2025-09-11 0:00:00,False,0,Al día,,0
4,1000591190,2025-10-31,64778.99,214365.000000,0.00,-557290.006218,-557290.006218,,,Steven Mateo Aroca Garzon,2025-10-15 0:00:00,False,0,Cerrado,,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96961,99534,2022-09-30,146463.03,292927.000000,0.00,-0.850000,-0.850000,,2022-09-14 0:00:00,Natalia Valentina Castro Jimenez,2022-09-10 0:00:00,False,0,Cerrado,,0
96962,99534,2022-10-31,0.00,0.000000,0.00,-0.850000,-0.850000,,,Natalia Valentina Castro Jimenez,,False,0,Cerrado,,0
96963,9957452,2024-08-31,619327.73,798525.000000,179197.48,-179197.270000,-179197.270000,2024-08-13 0:00:00,2024-08-14 0:00:00,Juan Felipe Hurtado Mercado,2024-08-13 0:00:00,False,0,Al día,,0
96964,9957452,2024-09-30,179197.48,0.000000,0.00,0.210000,0.210000,,,Juan Felipe Hurtado Mercado,2024-09-05 0:00:00,False,0,Cerrado,,0
96965,9957452,2024-10-31,0.00,0.000000,0.00,0.210000,0.210000,,,Juan Felipe Hurtado Mercado,,False,0,Cerrado,,0

In [122]:
df_filtrado = df_resultado.copy()

In [123]:
import pandas as pd
import numpy as np

# --- Copias ---
df_filtrado_ = df_filtrado.copy()
df_mora_ = df_mora.copy()

# --- Alinear tipos de ID: usar string en ambos ---
df_filtrado_['REFERENCIA'] = df_filtrado_['Referencia'].astype(str).str.strip()
df_mora_['REFERENCIA'] = df_mora_['REFERENCIA'].astype(str).str.strip()

# --- 1) Llave mensual en df_filtrado (ignorando día) ---
base = pd.to_datetime(df_filtrado_['Mes_año_Originacion'], dayfirst=True, errors='coerce')
base_period = base.dt.to_period('M')

meses = df_filtrado_['Meses_despues_Originacion'].fillna(0).astype('int64').to_numpy()
target_period = base_period + meses   # Period[M]

df_filtrado_['MES_Y'] = target_period  # llave mensual para el merge

# (Opcional) FECHA "visual": último día del mes, salvo si es mes actual -> hoy
hoy = pd.Timestamp.today().normalize()  # naive
fin_de_mes = target_period.dt.to_timestamp(how='end')  # <-- usar .dt
mismo_mes_actual = (fin_de_mes.dt.month == hoy.month) & (fin_de_mes.dt.year == hoy.year)
df_filtrado_['FECHA'] = fin_de_mes.where(~mismo_mes_actual, hoy)

# --- 2) Llave mensual en df_mora a partir de su FECHA ---
df_mora_['FECHA'] = pd.to_datetime(df_mora_['FECHA'], errors='coerce').dt.normalize()
df_mora_['MES_Y'] = df_mora_['FECHA'].dt.to_period('M')

# Si hay varias filas en el mismo mes por REFERENCIA, quedarnos con la última del mes
df_mora_sorted = df_mora_.sort_values(['REFERENCIA', 'MES_Y', 'FECHA'])
df_mora_mensual = df_mora_sorted.drop_duplicates(['REFERENCIA', 'MES_Y'], keep='last')

# --- 3) Merge por (REFERENCIA, MES_Y) ---
cols_mora = ['REFERENCIA', 'MES_Y', 'MORA_STATUS']
out = df_filtrado_.merge(
    df_mora_mensual[cols_mora],
    how='left',
    on=['REFERENCIA', 'MES_Y'],
    validate='m:1'
)

# --- 4) Limpieza ---
out.drop(columns=['REFERENCIA', 'MES_Y'], inplace=True)

# out = df_filtrado con MORA_STATUS por mes/año

In [124]:
out

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,...,Mes_año_Originacion,Meses_despues_Originacion,Meses_despues_facturacion,bank_monto,commission_monto,Pri-ult,Monto_Mensualidades,C/A,FECHA,MORA_STATUS
0,1000185400,false,COBRADO,LIQUIDACION_COLOMBIA,19405.915966,2025-06-20,520791.11,SKANDIA,22718600.0,02-2025,...,2025-06,0,0,552839.0,19405.882353,1.97,NaN,0.139732,2025-06-30 23:59:59.999999999,Al día
1,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,15060.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,...,2025-06,0,0,552839.0,19405.882353,1.97,NaN,0.139732,2025-06-30 23:59:59.999999999,Al día
2,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,55528.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,...,2025-06,1,1,552839.0,19405.882353,1.97,NaN,0.139732,2025-07-31 23:59:59.999999999,Cerrado
3,1000591190,false,COBRADO,LIQUIDACION_COLOMBIA,128644.546218,2025-09-12,344986.00,SKANDIA,12465987.0,12-2024,...,2025-09,0,0,1930000.0,63865.546218,1.97,NaN,0.193580,2025-09-30 23:59:59.999999999,Al día
4,1000591190,true,COBRADO,LIQUIDACION_COLOMBIA,214365.000000,2025-09-30,344986.00,SKANDIA,12465987.0,12-2024,...,2025-09,1,1,1930000.0,63865.546218,1.97,NaN,0.193580,2025-10-31 23:59:59.999999999,Cerrado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32764,99534,false,COBRADO,LIQUIDACION_COLOMBIA,328455.000000,2022-02-14,287861.00,A&V,9030750.0,06-2021,...,2022-02,0,0,1800000.0,328455.000000,1.00,NaN,0.000000,2022-02-28 23:59:59.999999999,Al día
32765,99534,false,COBRADO,LIQUIDACION_COLOMBIA,73231.000000,2022-08-10,287861.00,A&V,9030750.0,06-2021,...,2022-08,0,0,2600000.0,219694.117647,1.97,NaN,0.524534,2022-08-31 23:59:59.999999999,Mora 1
32766,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146463.000000,2022-09-12,287861.00,A&V,9030750.0,06-2021,...,2022-09,1,0,2600000.0,219694.117647,1.97,NaN,0.524534,2022-10-31 23:59:59.999999999,Cerrado
32767,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146464.000000,2022-09-28,287861.00,A&V,9030750.0,06-2021,...,2022-09,2,1,2600000.0,219694.117647,1.97,NaN,0.524534,2022-11-30 23:59:59.999999999,NaN
32768,9957452,false,COBRADO,LIQUIDACION_COLOMBIA,798525.000000,2024-08-13,465252.24,SKANDIA,14306600.0,07-2023,...,2024-08,0,0,2800000.0,619327.731092,1.97,NaN,0.397074,2024-08-31 23:59:59.999999999,Al día

In [125]:
# Eliminar la columna FECHA y renombrar resultado
df_filtrado = out.drop(columns=['FECHA'], errors='ignore').copy()

# Verificar resultado
df_filtrado.info()
df_filtrado.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32769 entries, 0 to 32768
Data columns (total 33 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Referencia                 32769 non-null  object
 1   Credito                    32769 non-null  object
 2   Status facturacion         32769 non-null  object
 3   Tipo de comision           32769 non-null  object
 4   Monto                      32769 non-null  float64
 5   Fecha de facturacion       32769 non-null  datetime64[ns]
 6   Apartado Mensual           32769 non-null  float64
 7   Vehiculo de ahorro         32769 non-null  object
 8   Deuda inicial Fija         32769 non-null  float64
 9   Mes_Año                    32769 non-null  object
 10  Mes_Cobro                  32769 non-null  float64
 11  AM/DB                      32769 non-null  float64
 12  AM/DB_outlier              32769 non-null  int64
 13  Rango_AM_DB                32769 non-null  category
 14  Rango_de_deuda             32769 non-null  category
 15  mes_exacto                 32769 non-null  datetime64[ns]
 16  amount_total               32769 non-null  float64
 17  n_pagos                    32769 non-null  int64
 18  PaB_total                  32769 non-null  float64
 19  n_pagos_PaB                32769 non-null  int64
 20  requester                  32769 non-null  object
 21  BANCO                      32769 non-null  object
 22  amount_promedio            32766 non-null  float64
 23  Originado                  32769 non-null  datetime64[ns]
 24  Mes_año_Originacion        32769 non-null  object
 25  Meses_despues_Originacion  32769 non-null  int32
 26  Meses_despues_facturacion  32769 non-null  int32
 27  bank_monto                 32769 non-null  float64
 28  commission_monto           32769 non-null  float64
 29  Pri-ult                    32769 non-null  float64
 30  Monto_Mensualidades        10213 non-null  float64
 31  C/A                        32769 non-null  float64
 32  MORA_STATUS                30611 non-null  object
dtypes: category(2), datetime64[ns](3), float64(13), int32(2), int64(3), object(10)
memory usage: 7.6+ MB

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,...,Originado,Mes_año_Originacion,Meses_despues_Originacion,Meses_despues_facturacion,bank_monto,commission_monto,Pri-ult,Monto_Mensualidades,C/A,MORA_STATUS
0,1000185400,false,COBRADO,LIQUIDACION_COLOMBIA,19405.915966,2025-06-20,520791.11,SKANDIA,22718600.0,02-2025,...,2025-06-19,2025-06,0,0,552839.0,19405.882353,1.97,NaN,0.139732,Al día
1,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,15060.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,...,2025-06-19,2025-06,0,0,552839.0,19405.882353,1.97,NaN,0.139732,Al día
2,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,55528.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,...,2025-06-19,2025-06,1,1,552839.0,19405.882353,1.97,NaN,0.139732,Cerrado
3,1000591190,false,COBRADO,LIQUIDACION_COLOMBIA,128644.546218,2025-09-12,344986.00,SKANDIA,12465987.0,12-2024,...,2025-09-11,2025-09,0,0,1930000.0,63865.546218,1.97,NaN,0.193580,Al día
4,1000591190,true,COBRADO,LIQUIDACION_COLOMBIA,214365.000000,2025-09-30,344986.00,SKANDIA,12465987.0,12-2024,...,2025-09-11,2025-09,1,1,1930000.0,63865.546218,1.97,NaN,0.193580,Cerrado

In [126]:
if 'commission_monto' in df_filtrado.columns:
    df_filtrado.drop(columns=['commission_monto'], inplace=True)

In [127]:
df_mora.info()
df_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96966 entries, 0 to 96965
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   REFERENCIA              96966 non-null  int64
 1   FECHA                   96966 non-null  datetime64[ns]
 2   X_COBRAR                96966 non-null  float64
 3   PAGO                    96966 non-null  float64
 4   X_COBRAR_FUTURO         96966 non-null  float64
 5   PLAN_PAGADO             96966 non-null  float64
 6   PLAN_PAGADO_INCOBRABLE  96966 non-null  float64
 7   FECHA_ORIGEN            96966 non-null  object
 8   FECHA_COBRO             96966 non-null  object
 9   RESPONSABLE             96966 non-null  object
 10  FECHA_DE_PAGO           96966 non-null  object
 11  MOROSO                  96966 non-null  bool
 12  DIAS_EN_MORA            96966 non-null  int64
 13  MORA_STATUS             96966 non-null  object
 14  Saldo actual            96966 non-null  object
 15  PAGO_PARCIAL            96966 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(5), int64(3), object(6)
memory usage: 11.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32769 entries, 0 to 32768
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Referencia                 32769 non-null  object
 1   Credito                    32769 non-null  object
 2   Status facturacion         32769 non-null  object
 3   Tipo de comision           32769 non-null  object
 4   Monto                      32769 non-null  float64
 5   Fecha de facturacion       32769 non-null  datetime64[ns]
 6   Apartado Mensual           32769 non-null  float64
 7   Vehiculo de ahorro         32769 non-null  object
 8   Deuda inicial Fija         32769 non-null  float64
 9   Mes_Año                    32769 non-null  object
 10  Mes_Cobro                  32769 non-null  float64
 11  AM/DB                      32769 non-null  float64
 12  AM/DB_outlier              32769 non-null  int64
 13  Rango_AM_DB                32769 non-null  category
 14  Rango_de_deuda             32769 non-null  category
 15  mes_exacto                 32769 non-null  datetime64[ns]
 16  amount_total               32769 non-null  float64
 17  n_pagos                    32769 non-null  int64
 18  PaB_total                  32769 non-null  float64
 19  n_pagos_PaB                32769 non-null  int64
 20  requester                  32769 non-null  object
 21  BANCO                      32769 non-null  object
 22  amount_promedio            32766 non-null  float64
 23  Originado                  32769 non-null  datetime64[ns]
 24  Mes_año_Originacion        32769 non-null  object
 25  Meses_despues_Originacion  32769 non-null  int32
 26  Meses_despues_facturacion  32769 non-null  int32
 27  bank_monto                 32769 non-null  float64
 28  Pri-ult                    32769 non-null  float64
 29  Monto_Mensualidades        10213 non-null  float64
 30  C/A                        32769 non-null  float64
 31  MORA_STATUS                30611 non-null  object
dtypes: category(2), datetime64[ns](3), float64(12), int32(2), int64(3), object(10)
memory usage: 7.3+ MB

In [128]:
df_filtrado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,...,amount_promedio,Originado,Mes_año_Originacion,Meses_despues_Originacion,Meses_despues_facturacion,bank_monto,Pri-ult,Monto_Mensualidades,C/A,MORA_STATUS
0,1000185400,false,COBRADO,LIQUIDACION_COLOMBIA,19405.915966,2025-06-20,520791.11,SKANDIA,22718600.0,02-2025,...,53546.50,2025-06-19,2025-06,0,0,552839.0,1.97,NaN,0.139732,Al día
1,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,15060.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,...,53546.50,2025-06-19,2025-06,0,0,552839.0,1.97,NaN,0.139732,Al día
2,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,55528.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,...,53546.50,2025-06-19,2025-06,1,1,552839.0,1.97,NaN,0.139732,Cerrado
3,1000591190,false,COBRADO,LIQUIDACION_COLOMBIA,128644.546218,2025-09-12,344986.00,SKANDIA,12465987.0,12-2024,...,76543.50,2025-09-11,2025-09,0,0,1930000.0,1.97,NaN,0.193580,Al día
4,1000591190,true,COBRADO,LIQUIDACION_COLOMBIA,214365.000000,2025-09-30,344986.00,SKANDIA,12465987.0,12-2024,...,76543.50,2025-09-11,2025-09,1,1,1930000.0,1.97,NaN,0.193580,Cerrado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32764,99534,false,COBRADO,LIQUIDACION_COLOMBIA,328455.000000,2022-02-14,287861.00,A&V,9030750.0,06-2021,...,390861.45,2022-02-14,2022-02,0,0,1800000.0,1.00,NaN,0.000000,Al día
32765,99534,false,COBRADO,LIQUIDACION_COLOMBIA,73231.000000,2022-08-10,287861.00,A&V,9030750.0,06-2021,...,145242.33,2022-08-10,2022-08,0,0,2600000.0,1.97,NaN,0.524534,Mora 1
32766,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146463.000000,2022-09-12,287861.00,A&V,9030750.0,06-2021,...,145242.33,2022-08-10,2022-09,1,0,2600000.0,1.97,NaN,0.524534,Cerrado
32767,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146464.000000,2022-09-28,287861.00,A&V,9030750.0,06-2021,...,145242.33,2022-08-10,2022-09,2,1,2600000.0,1.97,NaN,0.524534,NaN
32768,9957452,false,COBRADO,LIQUIDACION_COLOMBIA,798525.000000,2024-08-13,465252.24,SKANDIA,14306600.0,07-2023,...,475122.50,2024-08-13,2024-08,0,0,2800000.0,1.97,NaN,0.397074,Al día

In [129]:
import pandas as pd
import numpy as np

def depurar_por_cumsum_unicos(
    df_filtrado: pd.DataFrame,
    keys=("Referencia", "Mes_año_Originacion", "amount_total"),
    col_monto="Monto",
    col_fecha="Fecha de facturacion",
    margen=1.5,                  # 1.00 = 100%; 1.05 = 105%
    eliminar_montos_no_positivos=False,  # True si quieres descartar Monto <= 0
    col_originado="Originado",   # <-- NUEVO: columna con la fecha de originación
    anio_filtro=2024             # <-- NUEVO: año al que se aplica la regla
):
    """
    Igual que antes, pero solo aplica la lógica de cumsum/umbral al subset con Originado en `anio_filtro`.
    El resto de filas se consideran 'keep' sin tocar y no se incluyen en descartadas ni en el resumen.
    """
    # Copia y tipificación base
    df = df_filtrado.copy()
    df["_idx_original"] = np.arange(len(df))  # para reconstruir orden al final

    # Validaciones mínimas
    faltan = [c for c in keys + (col_monto, col_fecha, col_originado) if c not in df.columns]
    if faltan:
        raise ValueError(f"Faltan columnas en df_filtrado: {faltan}")

    # Tipos
    df[col_fecha] = pd.to_datetime(df[col_fecha], errors="coerce")
    df[col_monto] = pd.to_numeric(df[col_monto], errors="coerce")
    df[col_originado] = pd.to_datetime(df[col_originado], errors="coerce")
    if "amount_total" in keys and "amount_total" in df.columns:
        df["amount_total"] = pd.to_numeric(df["amount_total"], errors="coerce")

    # Split: solo procesar el subset del año objetivo
    mask_anio = df[col_originado].dt.year == int(anio_filtro)
    df_obj = df.loc[mask_anio].copy()
    df_otros = df.loc[~mask_anio].copy()  # pasan directos a keep

    # Si no hay filas en el año, devolvemos todo como keep y vacíos los otros outputs
    if df_obj.empty:
        df_keep_final = df.drop(columns=["_idx_original"])
        df_drop_final = df.iloc[0:0].copy()  # vacío con mismas columnas
        resumen = pd.DataFrame(columns=list(keys) + ["umbral", "cumsum_final", "filas_keep", "filas_drop"])
        return df_keep_final, df_drop_final, resumen

    # (Opcional) filtrar montos no positivos SOLO en el subset procesado
    if eliminar_montos_no_positivos:
        df_obj = df_obj[df_obj[col_monto] > 0].copy()

    # Orden dentro del subset: claves + fecha asc
    df_obj = df_obj.sort_values(by=list(keys) + [col_fecha], ascending=[True]*len(keys) + [True], na_position="last")

    # Umbral por fila dentro del subset
    if "amount_total" not in df_obj.columns:
        raise ValueError("Se requiere la columna 'amount_total' para calcular el umbral.")
    df_obj["_umbral"] = df_obj["amount_total"] * float(margen)

    # cumsum por grupo en subset
    df_obj["_cumsum"] = df_obj.groupby(list(keys))[col_monto].cumsum()

    # Si _umbral es NaN (amount_total NaN), NO descartamos nada de ese grupo
    umbral_es_nan = df_obj["_umbral"].isna()

    # Mantener hasta el umbral (priorizando antiguas)
    mask_keep = umbral_es_nan | (df_obj["_cumsum"] <= df_obj["_umbral"])

    # Separar salidas del subset
    cols_diag = ["_cumsum", "_umbral"]
    df_keep_obj = df_obj.loc[mask_keep].copy()
    df_drop_obj = df_obj.loc[~mask_keep].copy()
    if not df_drop_obj.empty:
        df_drop_obj["Motivo_descarte"] = "Excede umbral (amount_total * margen)"

    # Resumen por grupo (solo subset 2024)
    if df_keep_obj.empty:
        cumsum_final = (
            df_keep_obj.groupby(list(keys))[col_monto]
            .sum()
            .rename("cumsum_final")
            .reset_index()
        )
    else:
        cumsum_final = (
            df_keep_obj.groupby(list(keys))["_cumsum"]
            .max()
            .rename("cumsum_final")
            .reset_index()
        )

    umbrales = (
        df_obj
        .drop_duplicates(subset=list(keys))
        .loc[:, list(keys) + ["_umbral"]]
        .rename(columns={"_umbral": "umbral"})
    )
    filas_keep = df_keep_obj.groupby(list(keys)).size().rename("filas_keep").reset_index()
    filas_drop = df_drop_obj.groupby(list(keys)).size().rename("filas_drop").reset_index()

    resumen = (
        umbrales
        .merge(cumsum_final, on=list(keys), how="left")
        .merge(filas_keep, on=list(keys), how="left")
        .merge(filas_drop, on=list(keys), how="left")
        .fillna({"cumsum_final": 0, "filas_keep": 0, "filas_drop": 0})
    )

    # Limpiar columnas auxiliares
    df_keep_obj = df_keep_obj.drop(columns=cols_diag, errors="ignore")
    df_drop_obj = df_drop_obj.drop(columns=[c for c in cols_diag if c in df_drop_obj.columns], errors="ignore")

    # Las filas fuera del año objetivo pasan como KEEP tal cual
    # (sin tocar ni crear resumen/descartes para ellas)
    df_keep_final = pd.concat([df_keep_obj, df_otros], ignore_index=True)
    # Restaurar el orden original
    df_keep_final = df_keep_final.sort_values("_idx_original").drop(columns=["_idx_original"])
    df_drop_final = df_drop_obj.sort_values("_idx_original").drop(columns=["_idx_original"])

    return df_keep_final, df_drop_final, resumen


# ============================
# EJEMPLO DE USO
# ============================
df_limpio, df_descartadas, resumen = depurar_por_cumsum_unicos(
    df_filtrado,
    keys=("Referencia", "Mes_año_Originacion", "amount_total"),
    col_monto="Monto",
    col_fecha="Fecha de facturacion",
    margen=1.5,  # usar 1.00 si quieres 100% estricto
    eliminar_montos_no_positivos=False,
    col_originado="Originado",
    anio_filtro=2024
)

In [130]:
df_limpio

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,...,amount_promedio,Originado,Mes_año_Originacion,Meses_despues_Originacion,Meses_despues_facturacion,bank_monto,Pri-ult,Monto_Mensualidades,C/A,MORA_STATUS
8902,1000185400,false,COBRADO,LIQUIDACION_COLOMBIA,19405.915966,2025-06-20,520791.11,SKANDIA,22718600.0,02-2025,...,53546.50,2025-06-19,2025-06,0,0,552839.0,1.97,NaN,0.139732,Al día
8903,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,15060.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,...,53546.50,2025-06-19,2025-06,0,0,552839.0,1.97,NaN,0.139732,Al día
8904,1000185400,false,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,55528.000000,2025-06-19,520791.11,SKANDIA,22718600.0,02-2025,...,53546.50,2025-06-19,2025-06,1,1,552839.0,1.97,NaN,0.139732,Cerrado
8905,1000591190,false,COBRADO,LIQUIDACION_COLOMBIA,128644.546218,2025-09-12,344986.00,SKANDIA,12465987.0,12-2024,...,76543.50,2025-09-11,2025-09,0,0,1930000.0,1.97,NaN,0.193580,Al día
8906,1000591190,true,COBRADO,LIQUIDACION_COLOMBIA,214365.000000,2025-09-30,344986.00,SKANDIA,12465987.0,12-2024,...,76543.50,2025-09-11,2025-09,1,1,1930000.0,1.97,NaN,0.193580,Cerrado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32088,99534,false,COBRADO,LIQUIDACION_COLOMBIA,328455.000000,2022-02-14,287861.00,A&V,9030750.0,06-2021,...,390861.45,2022-02-14,2022-02,0,0,1800000.0,1.00,NaN,0.000000,Al día
32089,99534,false,COBRADO,LIQUIDACION_COLOMBIA,73231.000000,2022-08-10,287861.00,A&V,9030750.0,06-2021,...,145242.33,2022-08-10,2022-08,0,0,2600000.0,1.97,NaN,0.524534,Mora 1
32090,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146463.000000,2022-09-12,287861.00,A&V,9030750.0,06-2021,...,145242.33,2022-08-10,2022-09,1,0,2600000.0,1.97,NaN,0.524534,Cerrado
32091,99534,false,COBRADO,LIQUIDACION_COLOMBIA,146464.000000,2022-09-28,287861.00,A&V,9030750.0,06-2021,...,145242.33,2022-08-10,2022-09,2,1,2600000.0,1.97,NaN,0.524534,NaN
8901,9957452,false,COBRADO,LIQUIDACION_COLOMBIA,798525.000000,2024-08-13,465252.24,SKANDIA,14306600.0,07-2023,...,475122.50,2024-08-13,2024-08,0,0,2800000.0,1.97,NaN,0.397074,Al día

In [131]:
df_filtrado = df_limpio.copy()

In [132]:
# ============================
# AJUSTE DE COLUMNAS df_resultado
# ============================

# 1) Eliminar la columna 'bank_monto' si existe
if 'bank_monto' in df_filtrado.columns:
    df_filtrado.drop(columns=['bank_monto'], inplace=True)


# 2) Definir el nuevo orden con 'commission_monto' después de 'requester'
columnas_orden = [
    'Referencia', 'Credito', 'Status facturacion', 'Tipo de comision', 'Monto',
    'Fecha de facturacion', 'Apartado Mensual', 'Vehiculo de ahorro',
    'Deuda inicial Fija', 'Mes_Año', 'Mes_Cobro', 'AM/DB', 'AM/DB_outlier',
    'Rango_AM_DB', 'Rango_de_deuda', 'mes_exacto', 'Originado', 'requester',
    'BANCO', 'amount_promedio', 'amount_total', 'n_pagos', 'PaB_total',
    'n_pagos_PaB', 'Mes_año_Originacion', 'Meses_despues_Originacion',
    'Meses_despues_facturacion', 'C/A', 'Pri-ult', 'Monto_Mensualidades',
    'MORA_STATUS'
]

# 3) Reordenar (las columnas que existan + las extras al final)
columnas_existentes = [c for c in columnas_orden if c in df_filtrado.columns]
otras_columnas = [c for c in df_filtrado.columns if c not in columnas_orden]

df_filtrado = df_filtrado[columnas_existentes + otras_columnas]

print("✅ Columnas ajustadas correctamente. Nuevo orden:")
print(df_filtrado.columns.tolist())

✅ Columnas ajustadas correctamente. Nuevo orden:
['Referencia', 'Credito', 'Status facturacion', 'Tipo de comision', 'Monto', 'Fecha de facturacion', 'Apartado Mensual', 'Vehiculo de ahorro', 'Deuda inicial Fija', 'Mes_Año', 'Mes_Cobro', 'AM/DB', 'AM/DB_outlier', 'Rango_AM_DB', 'Rango_de_deuda', 'mes_exacto', 'Originado', 'requester', 'BANCO', 'amount_promedio', 'amount_total', 'n_pagos', 'PaB_total', 'n_pagos_PaB', 'Mes_año_Originacion', 'Meses_despues_Originacion', 'Meses_despues_facturacion', 'C/A', 'Pri-ult', 'Monto_Mensualidades', 'MORA_STATUS']

In [134]:
#if 'Monto_Mensualidades' in df_resultado.columns:
#    df_filtrado = df_filtrado.drop(columns=['Monto_Mensualidades'])

In [133]:
# ---- uploader.py (puedes ponerlo en una celda de Colab o en un .py en tu repo) ----
import os, json, re
import pandas as pd
import gspread
from google.oauth2.service_account import Credentials
from gspread_dataframe import set_with_dataframe

def _load_service_account_credentials():
    """
    Busca credenciales en este orden:
      1) Colab secret userdata['MI_JSON']
      2) Variable de entorno MI_JSON
      3) Archivo local service_account.json
    """
    # 1) Colab
    try:
        from google.colab import userdata  # type: ignore
        creds_str = userdata.get('MI_JSON')
        if creds_str:
            return Credentials.from_service_account_info(
                json.loads(creds_str),
                scopes=["https://www.googleapis.com/auth/spreadsheets"]
            )
    except Exception:
        pass

    # 2) Env var
    mi_json = os.environ.get("MI_JSON")
    if mi_json:
        return Credentials.from_service_account_info(
            json.loads(mi_json),
            scopes=["https://www.googleapis.com/auth/spreadsheets"]
        )

    # 3) Archivo local
    if os.path.exists("service_account.json"):
        with open("service_account.json", "r", encoding="utf-8") as f:
            info = json.load(f)
        return Credentials.from_service_account_info(
            info,
            scopes=["https://www.googleapis.com/auth/spreadsheets"]
        )

    raise RuntimeError("No encontré credenciales. Define MI_JSON (Colab o env var) o aporta service_account.json.")

def _parse_sheet_url(url_or_id: str):
    """
    Devuelve (spreadsheet_id, gid_int|None).
    Acepta URL completa o solo ID.
    """
    if "/d/" in url_or_id:
        spreadsheet_id = url_or_id.split("/d/")[1].split("/")[0]
        m = re.search(r"[?&#]gid=(\d+)", url_or_id)
        gid = int(m.group(1)) if m else None
    else:
        spreadsheet_id = url_or_id
        gid = None
    return spreadsheet_id, gid

def upload_dataframe_to_sheet(
    df: pd.DataFrame,
    spreadsheet_url_or_id: str,
    sheet_name: str | None = None,
    mode: str = "replace"  # "replace" limpia, "append" agrega al final
):
    """
    Sube un DataFrame a una hoja de Google Sheets.
      - Si la URL trae gid, escribe en esa hoja por ID.
      - Si das sheet_name, usa ese nombre (crea la hoja si no existe).
    """
    creds = _load_service_account_credentials()
    gc = gspread.authorize(creds)

    spreadsheet_id, gid = _parse_sheet_url(spreadsheet_url_or_id)
    sh = gc.open_by_key(spreadsheet_id)

    # Resolver worksheet
    ws = None
    if gid is not None:
        # Abrir por gid exacto
        try:
            ws = sh.get_worksheet_by_id(gid)
        except Exception as e:
            raise RuntimeError(f"No pude abrir la hoja con gid={gid}. "
                               f"Verifica permisos y que la hoja exista. Detalle: {e}")
    elif sheet_name:
        try:
            ws = sh.worksheet(sheet_name)
        except gspread.exceptions.WorksheetNotFound:
            ws = sh.add_worksheet(title=sheet_name, rows="100", cols="31")
    else:
        # fallback: primera hoja
        ws = sh.sheet1

    # Escribir
    if mode == "append":
        # Append: conserva encabezados si ya existen; si la hoja está vacía, escribe con encabezados
        values = ws.get_all_values()
        start_row = len(values) + 1 if values else 1
        if not values:
            set_with_dataframe(ws, df, row=1, col=1, include_index=False, include_column_header=True, resize=True)
        else:
            # sin encabezado para no duplicarlo
            set_with_dataframe(ws, df, row=start_row, col=1, include_index=False, include_column_header=False, resize=True)
    else:
        # replace: limpia y escribe
        ws.clear()
        set_with_dataframe(ws, df, include_index=False, include_column_header=True, resize=True)

    # Mostrar el service account para compartir acceso si hace falta
    try:
        print("✅ Subido correctamente.")
        print("👉 Si te da permiso denegado, comparte el Sheet con:", creds.service_account_email)
    except Exception:
        pass

In [134]:
from __main__ import upload_dataframe_to_sheet  # si está en la misma celda/entorno

# 3) Sube tu DataFrame df_resultado a la hoja del gid de tu URL
url = "https://docs.google.com/spreadsheets/d/1xGSzneJkRqREZupLshG9jaNK8wbP8WpV-yjUs_Lm7AA/edit?gid=1534851414#gid=1534851414"
upload_dataframe_to_sheet(df_filtrado, url, mode="replace")  # o mode="append"

✅ Subido correctamente.
👉 Si te da permiso denegado, comparte el Sheet con: robert1214@colabaccess-468021.iam.gserviceaccount.com

In [135]:
# 1) Seleccionar columnas requeridas
columnas = ["Referencia", "Originado", "amount_promedio", "amount_total", "PaB_total", "Pri-ult", "n_pagos", "n_pagos_PaB", "C/A"]
df_resultado_filtrado = df_filtrado[columnas].copy()

# 2) Eliminar duplicados (todas las columnas consideradas)
df_resultado_sin_dups = df_resultado_filtrado.drop_duplicates()

# 3) Subir a una hoja NUEVA llamada "Resultado sin duplicados"
#    (no se usa el gid anterior; se mantiene el mismo Spreadsheet)
url = "https://docs.google.com/spreadsheets/d/1xGSzneJkRqREZupLshG9jaNK8wbP8WpV-yjUs_Lm7AA/edit"

upload_dataframe_to_sheet(
    df_resultado_sin_dups,
    url,
    sheet_name="Resultado sin duplicados",  # nueva hoja
    mode="replace"  # o "append" si prefieres agregar sin borrar
)

✅ Subido correctamente.
👉 Si te da permiso denegado, comparte el Sheet con: robert1214@colabaccess-468021.iam.gserviceaccount.com

Subir base de X_Cobrar

In [136]:
refs_validas = set(df_filtrado['Referencia'].astype(str).str.strip())

c_facturaciones_X_COBRAR = c_facturaciones_X_COBRAR[
    c_facturaciones_X_COBRAR['Referencia'].astype(str).str.strip().isin(refs_validas)
].copy()

In [137]:
columnas_finales = [
    'Id',
    'Status facturacion',
    'Tipo de comision',
    'Referencia',
    'Monto',
    'Saldo',
    'Fecha de facturacion',
    'Fecha de envio de cobro',
    'Fecha de cobro',
    'Fecha de estructurado',
    'Credito'
]

# Mantener solo las que existan (por si algún nombre varía)
columnas_existentes = [col for col in columnas_finales if col in c_facturaciones_X_COBRAR.columns]

c_facturaciones_X_COBRAR = c_facturaciones_X_COBRAR[columnas_existentes].copy()

In [138]:
c_facturaciones_X_COBRAR.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1917 entries, 52422 to 86993
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Id                       1917 non-null   object
 1   Status facturacion       1917 non-null   object
 2   Tipo de comision         1917 non-null   object
 3   Referencia               1917 non-null   object
 4   Monto                    1917 non-null   object
 5   Saldo                    15 non-null     object
 6   Fecha de facturacion     1917 non-null   object
 7   Fecha de envio de cobro  1917 non-null   object
 8   Fecha de cobro           1917 non-null   object
 9   Fecha de estructurado    1917 non-null   object
 10  Credito                  1917 non-null   object
dtypes: object(11)
memory usage: 179.7+ KB

In [140]:
c_facturaciones_X_COBRAR

,Id,Status facturacion,Tipo de comision,Referencia,Monto,Saldo,Fecha de facturacion,Fecha de envio de cobro,Fecha de cobro,Fecha de estructurado,Credito
52422,2350110,POR_COBRAR,LIQUIDACION_COLOMBIA,3184670854,181311.0,NaN,14/8/2024,Sin fecha,Sin fecha,5/10/2025,false
53398,2362070,POR_COBRAR,LIQUIDACION_COLOMBIA,3213490728,372348.9076,NaN,29/8/2024,Sin fecha,Sin fecha,5/9/2025,false
57610,2490929,POR_COBRAR,LIQUIDACION_COLOMBIA,3214995888,1260504.0,NaN,31/10/2024,Sin fecha,Sin fecha,30/7/2025,false
57612,2490931,POR_COBRAR,LIQUIDACION_COLOMBIA,3214995888,1260504.0,NaN,31/10/2024,Sin fecha,Sin fecha,30/8/2025,false
57613,2490932,POR_COBRAR,LIQUIDACION_COLOMBIA,3204230183,355784.0,NaN,31/10/2024,Sin fecha,Sin fecha,5/9/2025,false
...,...,...,...,...,...,...,...,...,...,...,...
86855,3452357,POR_COBRAR,LIQUIDACION_COLOMBIA,3214425430,233162.0,NaN,1/4/2026,Sin fecha,Sin fecha,5/1/2027,false
86856,3452358,POR_COBRAR,LIQUIDACION_COLOMBIA,3214425430,370588.0,NaN,1/4/2026,Sin fecha,Sin fecha,5/6/2026,false
86860,3458775,POR_COBRAR,LIQUIDACION_COLOMBIA,3102912700,1660766.0,NaN,31/3/2026,Sin fecha,Sin fecha,30/5/2026,false
86931,3462862,POR_COBRAR,LIQUIDACION_COLOMBIA,3209167799,261180.0,NaN,8/4/2026,Sin fecha,Sin fecha,15/5/2026,false
86993,3471727,POR_COBRAR,LIQUIDACION_COLOMBIA,3227148050,75495.15126050421,NaN,10/4/2026,Sin fecha,Sin fecha,Sin fecha,false

In [144]:
# ================================
# UPLOADER GOOGLE SHEETS (FULL)
# ================================
import os, json, re
import pandas as pd
import gspread
from google.oauth2.service_account import Credentials
from gspread_dataframe import set_with_dataframe

# ================================
# CARGAR CREDENCIALES
# ================================
def _load_service_account_credentials():
    """
    Busca credenciales en este orden:
      1) Colab secret userdata['MI_JSON']
      2) Variable de entorno MI_JSON
      3) Archivo local service_account.json
    """
    # 1) Colab
    try:
        from google.colab import userdata  # type: ignore
        creds_str = userdata.get('MI_JSON')
        if creds_str:
            return Credentials.from_service_account_info(
                json.loads(creds_str),
                scopes=["https://www.googleapis.com/auth/spreadsheets"]
            )
    except Exception:
        pass

    # 2) Env var (GitHub / local)
    mi_json = os.environ.get("MI_JSON")
    if mi_json:
        return Credentials.from_service_account_info(
            json.loads(mi_json),
            scopes=["https://www.googleapis.com/auth/spreadsheets"]
        )

    # 3) Archivo local
    if os.path.exists("service_account.json"):
        with open("service_account.json", "r", encoding="utf-8") as f:
            info = json.load(f)
        return Credentials.from_service_account_info(
            info,
            scopes=["https://www.googleapis.com/auth/spreadsheets"]
        )

    raise RuntimeError("❌ No encontré credenciales. Define MI_JSON o usa service_account.json.")


# ================================
# PARSEAR URL
# ================================
def _parse_sheet_url(url_or_id: str):
    if "/d/" in url_or_id:
        spreadsheet_id = url_or_id.split("/d/")[1].split("/")[0]
        m = re.search(r"[?&#]gid=(\d+)", url_or_id)
        gid = int(m.group(1)) if m else None
    else:
        spreadsheet_id = url_or_id
        gid = None
    return spreadsheet_id, gid


# ================================
# SUBIR DATAFRAME
# ================================
def upload_dataframe_to_sheet(
    df: pd.DataFrame,
    spreadsheet_url_or_id: str,
    sheet_name: str | None = None,
    mode: str = "replace"  # "replace" o "append"
):
    creds = _load_service_account_credentials()
    gc = gspread.authorize(creds)

    spreadsheet_id, gid = _parse_sheet_url(spreadsheet_url_or_id)
    sh = gc.open_by_key(spreadsheet_id)

    # Seleccionar hoja
    ws = None
    if gid is not None:
        ws = sh.get_worksheet_by_id(gid)
    elif sheet_name:
        try:
            ws = sh.worksheet(sheet_name)
        except gspread.exceptions.WorksheetNotFound:
            ws = sh.add_worksheet(title=sheet_name, rows="100", cols="30")
    else:
        ws = sh.sheet1

    # Subir info
    if mode == "append":
        values = ws.get_all_values()
        start_row = len(values) + 1 if values else 1

        if not values:
            set_with_dataframe(ws, df, row=1, col=1, include_index=False, include_column_header=True, resize=True)
        else:
            set_with_dataframe(ws, df, row=start_row, col=1, include_index=False, include_column_header=False, resize=True)

    else:  # replace
        ws.clear()
        set_with_dataframe(ws, df, include_index=False, include_column_header=True, resize=True)

    print("✅ DataFrame subido correctamente")
    print("👉 Si hay error de permisos, comparte con:", creds.service_account_email)


# ================================
# 🚀 USO DIRECTO
# ================================

url = "https://docs.google.com/spreadsheets/d/1xGSzneJkRqREZupLshG9jaNK8wbP8WpV-yjUs_Lm7AA/edit?gid=1437427326#gid=1437427326"

upload_dataframe_to_sheet(
    c_facturaciones_X_COBRAR,
    url,
    mode="replace"
)

✅ DataFrame subido correctamente
👉 Si hay error de permisos, comparte con: robert1214@colabaccess-468021.iam.gserviceaccount.com

Subir base Cobrado

In [141]:
refs_validas = set(df_filtrado['Referencia'].astype(str).str.strip())

c_facturaciones_COBRADO = c_facturaciones_COBRADO[
    c_facturaciones_COBRADO['Referencia'].astype(str).str.strip().isin(refs_validas)
].copy()

In [142]:
columnas_finales = [
    'Id',
    'Status facturacion',
    'Tipo de comision',
    'Referencia',
    'Monto',
    'Saldo',
    'Fecha de facturacion',
    'Fecha de envio de cobro',
    'Fecha de cobro',
    'Fecha de estructurado',
    'Credito'
]

# Mantener solo las que existan (por si algún nombre varía)
columnas_existentes = [col for col in columnas_finales if col in c_facturaciones_COBRADO.columns]

c_facturaciones_COBRADO = c_facturaciones_COBRADO[columnas_existentes].copy()

In [143]:
c_facturaciones_COBRADO

,Id,Status facturacion,Tipo de comision,Referencia,Monto,Saldo,Fecha de facturacion,Fecha de envio de cobro,Fecha de cobro,Fecha de estructurado,Credito
0,1186301,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,3208712958,294118.0,0.0,4/10/2023,2/1/2024,3/1/2024,27/9/2023,false
1,1186303,COBRADO,LIQUIDACION_COLOMBIA,3182588339,100000.0,NaN,3/10/2023,23/10/2023,24/10/2023,3/10/2023,false
2,1186306,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,3505172416,111566.0,0.0,3/10/2023,4/12/2023,5/12/2023,3/10/2023,false
5,1186316,COBRADO,LIQUIDACION_COLOMBIA,3142688054,2506.0499999999997,NaN,4/10/2023,5/10/2023,6/10/2023,Sin fecha,false
7,1186319,COBRO_PARCIAL_COBRADO,LIQUIDACION_COLOMBIA,3113091560,24750.0,0.0,4/10/2023,12/10/2023,13/10/2023,Sin fecha,false
...,...,...,...,...,...,...,...,...,...,...,...
86929,3462860,COBRADO,LIQUIDACION_COLOMBIA,3006226709,198900.0,NaN,9/4/2026,8/4/2026,9/4/2026,Sin fecha,false
86939,3462892,COBRADO,LIQUIDACION_COLOMBIA,3006139503,8828950.0,0.0,9/4/2026,Sin fecha,10/4/2026,Sin fecha,true
86942,3462895,COBRADO,LIQUIDACION_COLOMBIA,3134046773,9105690.0,0.0,9/4/2026,Sin fecha,10/4/2026,Sin fecha,true
86943,3462896,COBRADO,LIQUIDACION_COLOMBIA,3134046773,360000.0,0.0,9/4/2026,Sin fecha,10/4/2026,Sin fecha,true
86986,3471720,COBRADO,LIQUIDACION_COLOMBIA,3174026523,1660134.7983193276,0.0,10/4/2026,Sin fecha,11/4/2026,Sin fecha,true

In [145]:
# ================================
# UPLOADER GOOGLE SHEETS (FULL)
# ================================
import os, json, re
import pandas as pd
import gspread
from google.oauth2.service_account import Credentials
from gspread_dataframe import set_with_dataframe

# ================================
# CARGAR CREDENCIALES
# ================================
def _load_service_account_credentials():
    """
    Busca credenciales en este orden:
      1) Colab secret userdata['MI_JSON']
      2) Variable de entorno MI_JSON
      3) Archivo local service_account.json
    """
    # 1) Colab
    try:
        from google.colab import userdata  # type: ignore
        creds_str = userdata.get('MI_JSON')
        if creds_str:
            return Credentials.from_service_account_info(
                json.loads(creds_str),
                scopes=["https://www.googleapis.com/auth/spreadsheets"]
            )
    except Exception:
        pass

    # 2) Env var (GitHub / local)
    mi_json = os.environ.get("MI_JSON")
    if mi_json:
        return Credentials.from_service_account_info(
            json.loads(mi_json),
            scopes=["https://www.googleapis.com/auth/spreadsheets"]
        )

    # 3) Archivo local
    if os.path.exists("service_account.json"):
        with open("service_account.json", "r", encoding="utf-8") as f:
            info = json.load(f)
        return Credentials.from_service_account_info(
            info,
            scopes=["https://www.googleapis.com/auth/spreadsheets"]
        )

    raise RuntimeError("❌ No encontré credenciales. Define MI_JSON o usa service_account.json.")


# ================================
# PARSEAR URL
# ================================
def _parse_sheet_url(url_or_id: str):
    if "/d/" in url_or_id:
        spreadsheet_id = url_or_id.split("/d/")[1].split("/")[0]
        m = re.search(r"[?&#]gid=(\d+)", url_or_id)
        gid = int(m.group(1)) if m else None
    else:
        spreadsheet_id = url_or_id
        gid = None
    return spreadsheet_id, gid


# ================================
# SUBIR DATAFRAME
# ================================
def upload_dataframe_to_sheet(
    df: pd.DataFrame,
    spreadsheet_url_or_id: str,
    sheet_name: str | None = None,
    mode: str = "replace"  # "replace" o "append"
):
    creds = _load_service_account_credentials()
    gc = gspread.authorize(creds)

    spreadsheet_id, gid = _parse_sheet_url(spreadsheet_url_or_id)
    sh = gc.open_by_key(spreadsheet_id)

    # Seleccionar hoja
    ws = None
    if gid is not None:
        ws = sh.get_worksheet_by_id(gid)
    elif sheet_name:
        try:
            ws = sh.worksheet(sheet_name)
        except gspread.exceptions.WorksheetNotFound:
            ws = sh.add_worksheet(title=sheet_name, rows="100", cols="30")
    else:
        ws = sh.sheet1

    # Subir info
    if mode == "append":
        values = ws.get_all_values()
        start_row = len(values) + 1 if values else 1

        if not values:
            set_with_dataframe(ws, df, row=1, col=1, include_index=False, include_column_header=True, resize=True)
        else:
            set_with_dataframe(ws, df, row=start_row, col=1, include_index=False, include_column_header=False, resize=True)

    else:  # replace
        ws.clear()
        set_with_dataframe(ws, df, include_index=False, include_column_header=True, resize=True)

    print("✅ DataFrame subido correctamente")
    print("👉 Si hay error de permisos, comparte con:", creds.service_account_email)


# ================================
# 🚀 USO DIRECTO
# ================================

url = "https://docs.google.com/spreadsheets/d/1xGSzneJkRqREZupLshG9jaNK8wbP8WpV-yjUs_Lm7AA/edit?gid=500185036#gid=500185036"

upload_dataframe_to_sheet(
    c_facturaciones_COBRADO,
    url,
    mode="replace"
)

✅ DataFrame subido correctamente
👉 Si hay error de permisos, comparte con: robert1214@colabaccess-468021.iam.gserviceaccount.com

#CC_PaB

In [146]:
referencia_buscada = '3508191585'

resultado = df_resultado[df_resultado['Referencia'] == referencia_buscada]

resultado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,...,amount_promedio,Originado,Mes_año_Originacion,Meses_despues_Originacion,Meses_despues_facturacion,bank_monto,commission_monto,Pri-ult,Monto_Mensualidades,C/A
31442,3508191585,false,COBRADO,LIQUIDACION_COLOMBIA,18360.0,2025-09-25,422543.09,DING,16529250.0,05-2025,...,10924.0,2025-09-30,2025-09,0,0,280200.0,8403.361345,2.96,NaN,0.012022

In [143]:
import os, io, json, time, base64
import pandas as pd, requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

def get_secret(name):
    # 1) Colab.userdata si existe
    try:
        from google.colab import userdata as _ud
        v = _ud.get(name)
        if v:
            return v
    except Exception:
        pass
    # 2) Variables de entorno (GitHub/local)
    return os.environ.get(name)

USER_API   = get_secret("USER_API")
SECRET_API = get_secret("SECRET_API")

if not USER_API or not SECRET_API:
    raise ValueError("Falta USER_API o SECRET_API. En Colab: 'Secretos'. En GitHub: Settings → Secrets → Actions.")

BASE_URL = "https://mutatio-api.gobravo.dev"
RESOURCE = "/accounting/flows/download"

def make_session():
    s = requests.Session()
    retry = Retry(
        total=3, connect=2, read=2, backoff_factor=1.2,
        status_forcelist=[502, 503, 504], allowed_methods={"POST"},
        raise_on_status=False
    )
    s.mount("https://", HTTPAdapter(max_retries=retry))
    s.mount("http://",  HTTPAdapter(max_retries=retry))
    return s

session = make_session()

def _leer_csv_flexible(resp) -> pd.DataFrame:
    resp.raise_for_status()
    txt = resp.text or ""
    if not txt.strip():
        return pd.DataFrame()
    first = txt.splitlines()[0]
    sep = ';' if first.count(';') >= first.count(',') else ','
    return pd.read_csv(io.StringIO(txt), sep=sep, dtype=str)

def _decode_jwt_exp(jwt_token: str):
    try:
        parts = jwt_token.split(".")
        if len(parts) != 3:
            return None
        payload_b64 = parts[1] + "==="  # padding
        payload = json.loads(base64.urlsafe_b64decode(payload_b64))
        return payload.get("exp"), payload
    except Exception:
        return None

def get_token(user: str, secret: str) -> str:
    url = f"{BASE_URL}/auth/generate-token"
    r = session.post(url, json={"user": user, "secret": secret},
                     headers={"Content-Type":"application/json","Accept":"application/json"},
                     timeout=(10, 45))
    r.raise_for_status()
    tok = r.json().get("token")
    if not tok:
        raise RuntimeError(f"Auth OK pero no vino 'token'. Respuesta: {r.text[:300]}")
    return tok

class Client:
    def __init__(self, user, secret):
        self.user = user
        self.secret = secret
        self.token = None

    def ensure_token(self):
        if not self.token:
            self.token = get_token(self.user, self.secret)

    def refresh_token(self):
        self.token = get_token(self.user, self.secret)

    def descargar_pagina_flows(self, page: int) -> pd.DataFrame:
        self.ensure_token()
        try_styles = [
            ("query", {"params": {"pageToDownload": str(page)}, "json": []}),
            ("json",  {"params": {}, "json": {"pageToDownload": page}}),
        ]
        last_resp = None

        for style, kwargs in try_styles:
            url = f"{BASE_URL}{RESOURCE}"
            headers = {
                "Authorization": f"Bearer {self.token}",
                "Accept": "text/csv, text/plain",
                "Content-Type": "application/json",
            }
            resp = session.post(url, headers=headers, timeout=(12, 90), **kwargs)
            last_resp = resp

            if resp.status_code == 200:
                return _leer_csv_flexible(resp)

            if resp.status_code == 401:
                # Intento único de refrescar token y reintentar con el mismo estilo
                exp_info = _decode_jwt_exp(self.token)
                if exp_info:
                    exp_ts, payload = exp_info
                    if exp_ts:
                        ahora = int(time.time())
                        print(f"[DEBUG] JWT expira en {exp_ts} (faltan {exp_ts - ahora}s). Payload (recortado): {json.dumps({k:payload[k] for k in payload if k!='exp'})[:200]}")
                print(f"[WARN] 401 con estilo '{style}'. Intento refrescar token y reintentar una vez...")
                self.refresh_token()
                headers["Authorization"] = f"Bearer {self.token}"
                resp2 = session.post(url, headers=headers, timeout=(12, 90), **kwargs)
                last_resp = resp2
                if resp2.status_code == 200:
                    return _leer_csv_flexible(resp2)
                else:
                    # si vuelve a fallar 401/403, seguimos al siguiente estilo o salimos
                    continue

        # Si llegamos aquí, no hubo 200
        msg = (last_resp.text or "")[:500] if last_resp is not None else ""
        raise RuntimeError(f"Fallo al descargar página {page}. "
                           f"status={getattr(last_resp,'status_code',None)} "
                           f"body='{msg}'")

    def descargar_todo_flows(self, max_pages: int = 500) -> pd.DataFrame:
        frames = []
        for page in range(max_pages):
            df = self.descargar_pagina_flows(page)
            if df.empty:
                break
            frames.append(df)
        return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()

# --- Uso ---
cli = Client(USER_API, SECRET_API)
flujos_pab = cli.descargar_todo_flows(max_pages=200)

print(f"Filas totales: {len(flujos_pab)} | Columnas: {len(flujos_pab.columns)}")
print(flujos_pab.columns.tolist())

Filas totales: 137797 | Columnas: 43
['Id', 'Empresa', 'Tipo de flujo', 'Se paga con credito', 'Referencia', 'Receptor de pago', 'Cuenta de retiro', 'Numero de cheque', 'Empresa pagadora', 'Tipo de financiamiento', 'Fecha de flujo', 'Monto', 'Status de cuenta por cobrar', 'Fecha de facturacion', 'Fecha de envio de cobro', 'Liquidacion Relacionada', 'Fecha de cobro', 'Banco receptor', 'Saldo', 'Numero de factura', 'Status flujo', 'Fecha de vencimiento', 'Concepto', 'Rubro de contabilidad', 'Area', 'Comision estructurada', 'Fecha Comision estructurada', 'Referencia de crédito', 'Numero de factura (Compra)', 'Id liquidacion relacionada', 'Id Quickbase del flujo', 'Fecha de creacion', 'Fecha de actualizacion', 'Creado por', 'Actualizado por', 'Status Sistema Contable', 'Subido a Sistema Contable por', 'Fecha subida a sistema contable', 'Id de Flujo dividido', 'Documento Soporte', 'Status TE Sistema Contable', 'Subido TE a Sistema Contable por', 'Fecha TE subida a sistema contable']

In [144]:
resultado_actualizado

,Referencia,Credito,Status facturacion,Tipo de comision,Monto,Fecha de facturacion,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,Mes_Cobro,AM/DB,AM/DB_outlier,Rango_AM_DB,Rango_de_deuda
0,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,602031.0,2025-06-26,611362.66,SKANDIA,43346600.0,06-2025,0.0,0.014104,0,< 1.5%,35 – 60 M
1,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,627346.0,2025-06-26,611362.66,SKANDIA,43346600.0,06-2025,1.0,0.014104,0,< 1.5%,35 – 60 M
2,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,227237.0,2025-08-05,611362.66,SKANDIA,43346600.0,06-2025,2.0,0.014104,0,< 1.5%,35 – 60 M
3,1000018033,false,COBRO_PARCIAL_COBRADO,INSCRIPCION_COLOMBIA,3852.0,2025-06-26,611362.66,SKANDIA,43346600.0,06-2025,2.0,0.014104,0,< 1.5%,35 – 60 M
4,1000018033,false,COBRADO,MENSUALIDAD_COLOMBIA,227237.0,2025-09-03,611362.66,SKANDIA,43346600.0,06-2025,3.0,0.014104,0,< 1.5%,35 – 60 M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822447,99990,false,COBRADO,MENSUALIDAD_COLOMBIA,157577.0,2021-12-05,519374.00,A&V,29414564.0,06-2021,6.0,0.017657,0,1.5% – 1.99%,< 35 M
822448,99990,true,COBRADO,LIQUIDACION_COLOMBIA,1210878.0,2021-12-23,519374.00,A&V,29414564.0,06-2021,6.0,0.017657,0,1.5% – 1.99%,< 35 M
822449,99990,true,COBRADO,MENSUALIDAD_COLOMBIA,1575770.0,2021-12-23,519374.00,A&V,29414564.0,06-2021,6.0,0.017657,0,1.5% – 1.99%,< 35 M
822450,99990,true,COBRADO,LIQUIDACION_COLOMBIA,112390.0,2022-07-30,519374.00,A&V,29414564.0,06-2021,13.0,0.017657,0,1.5% – 1.99%,< 35 M
822451,99990,true,COBRADO,LIQUIDACION_COLOMBIA,692027.0,2022-10-24,519374.00,A&V,29414564.0,06-2021,16.0,0.017657,0,1.5% – 1.99%,< 35 M

In [145]:
resultado_actualizado_pab = resultado_actualizado.drop(columns=["Credito", "Status facturacion", "Tipo de comision", "Monto", "Fecha de facturacion", "Mes_Cobro"], errors="ignore")

In [146]:
resultado_actualizado_pab.drop_duplicates(inplace=True)

In [147]:
berex_estruct["reference"] = berex_estruct["reference"].astype("object")
flujos_pab["Referencia"] = flujos_pab["Referencia"].astype("object")
resultado_actualizado_pab["Referencia"] = resultado_actualizado_pab["Referencia"].astype("object")

refs_validas = berex_estruct["reference"].unique()

flujos_pab = flujos_pab[flujos_pab["Referencia"].isin(refs_validas)]
resultado_actualizado_pab = resultado_actualizado_pab[resultado_actualizado_pab["Referencia"].isin(refs_validas)]

# (Opcional) Reiniciar índices
flujos_pab.reset_index(drop=True, inplace=True)
resultado_actualizado_pab.reset_index(drop=True, inplace=True)

In [148]:
# Filtrar las filas donde 'destination' sea 'bank'
berex_bank = berex_estruct[berex_estruct["destination"] == "bank"]

# Crear el nuevo DataFrame CC_PAB con las columnas seleccionadas y renombradas
CC_PAB = berex_bank.rename(columns={
    "reference": "REFERENCIA",
    "amount": "X_COBRAR",
    "bank": "BANCO",
    "payment_date": "FECHA_PAGO",
    "requester": "RESPONSABLE",
    "Originado": "FECHA_ORIGEN"
})[["REFERENCIA", "X_COBRAR", "BANCO", "FECHA_PAGO", "RESPONSABLE", "FECHA_ORIGEN"]]

# Reiniciar el índice
CC_PAB.reset_index(drop=True, inplace=True)

In [149]:
resultado_actualizado_pab

,Referencia,Apartado Mensual,Vehiculo de ahorro,Deuda inicial Fija,Mes_Año,AM/DB,AM/DB_outlier,Rango_AM_DB,Rango_de_deuda
0,1000185400,520791.11,SKANDIA,22718600.0,02-2025,0.022924,0,2% – 2.5%,< 35 M
1,1000591190,344986.00,SKANDIA,12465987.0,12-2024,0.027674,0,> 2.5%,< 35 M
2,100076,359735.00,A&V,17041870.0,06-2021,0.021109,0,2% – 2.5%,< 35 M
3,1001082965,2530576.88,SKANDIA,196225650.0,07-2024,0.012896,0,< 1.5%,> 100 M
4,1001244516,214729.55,SKANDIA,10192650.0,11-2023,0.021067,0,2% – 2.5%,< 35 M
...,...,...,...,...,...,...,...,...,...
8304,98672,301717.00,A&V,13160897.0,06-2021,0.022925,0,2% – 2.5%,< 35 M
8305,98702966,1452577.37,SKANDIA,121123008.0,03-2024,0.011993,0,< 1.5%,> 100 M
8306,98709164,515382.43,SKANDIA,12043200.0,01-2025,0.042794,1,> 2.5%,< 35 M
8307,99534,287861.00,A&V,9030750.0,06-2021,0.031876,0,> 2.5%,< 35 M
8308,9957452,465252.24,SKANDIA,14306600.0,07-2023,0.032520,0,> 2.5%,< 35 M

In [150]:
flujos_pab

,Id,Empresa,Tipo de flujo,Se paga con credito,Referencia,Receptor de pago,Cuenta de retiro,Numero de cheque,Empresa pagadora,Tipo de financiamiento,...,Creado por,Actualizado por,Status Sistema Contable,Subido a Sistema Contable por,Fecha subida a sistema contable,Id de Flujo dividido,Documento Soporte,Status TE Sistema Contable,Subido TE a Sistema Contable por,Fecha TE subida a sistema contable
0,209248,RACE_CAPITAL_COLOMBIA_SAS,FINANCIAMIENTO_A_CLIENTE,Si,3174026523,Falabella,BANCOLOMBIA,12300000,RACE_CAPITAL_COLOMBIA_SAS,PAGO_A_BANCO,...,riesgocol,riesgocol,NO_CARGADO,Sin data,Sin fecha,209209,NO,Sin Status,Sin data,Sin fecha
1,209216,GO_BRAVO_COLOMBIA_SAS,FINANCIAMIENTO_A_CLIENTE,No,3227148050,Rapicredit,BANCOLOMBIA,525699,GO_BRAVO_COLOMBIA_SAS,OPERACION_REPARACION_DE_CREDITO,...,Mutatio,Sin registro,NO_CARGADO,Sin data,Sin fecha,Sin id,NO,Sin Status,Sin data,Sin fecha
2,209209,RACE_CAPITAL_COLOMBIA_SAS,FINANCIAMIENTO_A_CLIENTE,Si,3174026523,Falabella,BANCOLOMBIA,12300000,RACE_CAPITAL_COLOMBIA_SAS,OPERACION_REPARACION_DE_CREDITO,...,Mutatio,riesgocol,NO_CARGADO,Sin data,Sin fecha,Sin id,NO,Sin Status,Sin data,Sin fecha
3,209203,RACE_CAPITAL_COLOMBIA_SAS,FINANCIAMIENTO_A_CLIENTE,Si,3134046773,Bancolombia,BANCOLOMBIA,40186133,RACE_CAPITAL_COLOMBIA_SAS,PAGO_A_BANCO,...,riesgocol,riesgocol,NO_CARGADO,Sin data,Sin fecha,209167,NO,Sin Status,Sin data,Sin fecha
4,209182,GO_BRAVO_COLOMBIA_SAS,FINANCIAMIENTO_A_CLIENTE,No,3143557105,Banco de Occidente,BANCOLOMBIA,14690000,GO_BRAVO_COLOMBIA_SAS,OPERACION_REPARACION_DE_CREDITO,...,Mutatio,Sin registro,NO_CARGADO,Sin data,Sin fecha,Sin id,NO,Sin Status,Sin data,Sin fecha
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29550,70043,RESUELVE_TU_DEUDA_COLOMBIA_SAS,FINANCIAMIENTO_A_CLIENTE,No,3212009494,Bancolombia,BANCOLOMBIA,21803994,RESPALDO_COLOMBIA_SAS,OPERACION_REPARACION_DE_CREDITO,...,Sin registro,sgonzalez,NO_CARGADO,Sin data,Sin fecha,Sin id,NO,Sin Status,Sin data,Sin fecha
29551,70042,RESUELVE_TU_DEUDA_COLOMBIA_SAS,FINANCIAMIENTO_A_CLIENTE,No,3106137498,Banco de Bogot?,BANCOLOMBIA,8909,RESPALDO_COLOMBIA_SAS,OPERACION_REPARACION_DE_CREDITO,...,Sin registro,Sin registro,NO_CARGADO,Sin data,Sin fecha,Sin id,NO,Sin Status,Sin data,Sin fecha
29552,70041,RESUELVE_TU_DEUDA_COLOMBIA_SAS,FINANCIAMIENTO_A_CLIENTE,No,3507158039,Banco de Bogota,IRIS,367000,RESUELVE_TU_DEUDA_COLOMBIA_SAS,OPERACION_REPARACION_DE_CREDITO,...,Sin registro,sgonzalez,NO_CARGADO,Sin data,Sin fecha,Sin id,NO,Sin Status,Sin data,Sin fecha
29553,70040,RESUELVE_TU_DEUDA_COLOMBIA_SAS,FINANCIAMIENTO_A_CLIENTE,No,3142462909,?xito,IRIS,845500,RESUELVE_TU_DEUDA_COLOMBIA_SAS,OPERACION_REPARACION_DE_CREDITO,...,Sin registro,Sin registro,NO_CARGADO,Sin data,Sin fecha,Sin id,NO,Sin Status,Sin data,Sin fecha
29554,70037,RESUELVE_TU_DEUDA_COLOMBIA_SAS,FINANCIAMIENTO_A_CLIENTE,No,3007013619,Scotiabank Colpatria,BANCOLOMBIA,8906,RESPALDO_COLOMBIA_SAS,OPERACION_REPARACION_DE_CREDITO,...,Sin registro,andres.giraldo,NO_CARGADO,Sin data,Sin fecha,Sin id,NO,Sin Status,Sin data,Sin fecha

In [151]:
# 1. Eliminar la columna FECHA_PAGO
CC_PAB = CC_PAB.drop(columns=["FECHA_PAGO"], errors="ignore")

# 2. Agrupar por las columnas clave y sumar X_COBRAR
CC_PAB = (
    CC_PAB
    .groupby(["REFERENCIA", "BANCO", "RESPONSABLE", "FECHA_ORIGEN"], as_index=False)
    .agg({"X_COBRAR": "sum"})
)

# 3. Renombrar la columna resultante
CC_PAB.rename(columns={"X_COBRAR": "X_COBRAR_TOTAL"}, inplace=True)

# 4. (Opcional) Verificar el resultado
print(CC_PAB.head())

   REFERENCIA        BANCO                RESPONSABLE FECHA_ORIGEN  \
0  1000185400   Rapicredit   Hector Elian Lacera Vega   2025-06-19
1  1000591190    Falabella  Steven Mateo Aroca Garzon   2025-09-11
2      100076   Davivienda  David Steban Pineda Gallo   2022-12-23
3      100076   Davivienda                No Asignado   2023-01-11
4  1001082965  Bancolombia  Alba Yohana Moreno Martin   2024-12-23

   X_COBRAR_TOTAL
0        552839.0
1       1930000.0
2       2942000.0
3      10200000.0
4        590000.0

In [152]:
CC_PAB

,REFERENCIA,BANCO,RESPONSABLE,FECHA_ORIGEN,X_COBRAR_TOTAL
0,1000185400,Rapicredit,Hector Elian Lacera Vega,2025-06-19,552839.0
1,1000591190,Falabella,Steven Mateo Aroca Garzon,2025-09-11,1930000.0
2,100076,Davivienda,David Steban Pineda Gallo,2022-12-23,2942000.0
3,100076,Davivienda,No Asignado,2023-01-11,10200000.0
4,1001082965,Bancolombia,Alba Yohana Moreno Martin,2024-12-23,590000.0
...,...,...,...,...,...
14905,98702966,Éxito,Jana Milena Lopez Buitrago,2024-09-30,6094000.0
14906,98709164,Bancolombia,Vivian Caterin Rodriguez Verano,2025-08-29,1800000.0
14907,99534,Colsubsidio,Natalia Valentina Castro Jimenez,2022-08-10,2600000.0
14908,99534,Scotiabank Colpatria,Maria Paula Balaguera Penagos,2022-02-14,1800000.0
14909,9957452,Bancolombia,Juan Felipe Hurtado Mercado,2024-08-13,2800000.0